### ISSUE TITLE
Absolute mouse position in v0.9.0

### ISSUE THREAD

**Issue by cloudkite** [gaearon/react-dnd#101]
Thanks for the awesome lib!

Would be nice if `DragDropContext` exposed the absolute mouse position with `DragOffsetStore.getCurrentOffsetFromClient()` instead of just the delta. Any reservations against adding a `getCurrentOffset` alongside `getCurrentOffsetDelta`?

**Comment by gaearon** [comment]
I'll add that. Just wanted someone to ask for it first :+1:

**Comment by gaearon** [comment]
Fixed in 0.9.1 via https://github.com/gaearon/react-dnd/commit/2e785fccb5899388abae4979db8bfb33db389231.
