### ISSUE TITLE
Circle-with-line drop cursor on IE 10/11 (sortable)

### ISSUE THREAD

**Issue by grahamb** [gaearon/react-dnd#107]
Mentioned in #106: in IE 10 & 11, the drop cursor on the sortable example is the circle-with-line icon, which makes it look like you can't drop into the target.

I tried to screen-capture this, but QuickTime isn't capturing the cursor when recording IE running in VirtualBox.

**Comment by gaearon** [comment]
Can you verify whether this is still an issue in the upcoming 1.0 version?
http://rawgit.com/gaearon/react-dnd/dnd-core/examples/index.html#/sortable-simple

**Comment by gaearon** [comment]
This is a consequence of #138 and solved in `v1.0.0-alpha` that is already on NPM.
The final 1.0 will come within a week or so.

Closing.
