### ISSUE TITLE
Can I make more than one drop zone in one component?

### ISSUE THREAD

**Issue by deser** [gaearon/react-dnd#110]
For example now I can't do this:
<pre>
&lt;div className=&quot;component&quot;&gt;<br/>    &lt;div {...this.dropTargetFor(Item1)}&gt;&lt;/div&gt;<br/>    &lt;div {...this.dropTargetFor(Item2)}&gt;&lt;/div&gt;<br/>&lt;/div&gt;
</pre>

I this case I should make 2 different components.
Thanks guys!

**Comment by gaearon** [comment]
You should totally be able to do this. What is the problem?

**Comment by deser** [comment]
Hi, thanks for answer.
The problem is that I want to attach different callbacks. I've wrote wrong examaple. There is it:
<pre>
&lt;div className=&quot;component&quot;&gt;<br/>    &lt;div {...this.dropTargetFor(Item1, Item2)}&gt;&lt;/div&gt;<br/>    &lt;div {...this.dropTargetFor(Item1, Item2)}&gt;&lt;/div&gt;<br/>&lt;/div&gt;
</pre>

I want to attach different handlers for first and second div. Handlers depend on Item1, Item2 DND types but not on div  on what I added ...this.dropTargetFor (Now reactdnd thinks that these DIVs are one drop area but I want them to be different drop areas)

Thank you!

**Comment by gaearon** [comment]
If you want to have different handlers, indeed, you'll either need to extract them into separate components, or give them different types. I think it's a reasonable limitation because having two different handlers for the same type in one component would make code harder to understand.

**Comment by deser** [comment]
Thanks! You are right.

**Comment by gaearon** [comment]
I'm closing this, feel free to comment if you have more questions!
