### ISSUE TITLE
I can drag item from dragzone in drag-around-naive example

### ISSUE THREAD

**Issue by ALF-er** [gaearon/react-dnd#116]
![Look ma! I can drag it away](https://cloud.githubusercontent.com/assets/2158067/6638509/7d3bdb36-c98f-11e4-82df-880b1d3d003e.png)

On http://gaearon.github.io/react-dnd/#/drag-around-naive drag item for left part of it (for example capital "D") to the right border of drag zone. Drop it near the border so some part of it overflow border. Then continuously drag this item in borders of itself. 
Also, after this, you can drag second item on the top of first one that already have been escaped from prison.

**Comment by gaearon** [comment]
I'm happy to accept a PR fixing this. Currently I don't have the time resources to work on fixing this, and it's a minor issue, so I'm closing.
