### ISSUE TITLE
DragLayerMixin: exposes initialOffsetFromContainer

### ISSUE THREAD

**Issue by gre** [gaearon/react-dnd#117]
The current `DragLayerMixin` seems to be only designed to implement drag layer that have the exact same size (width, height) than the initial draggable element.

When you want to have small size for instance, the result will be weird because that layer will be offset (using `getDragLayerState().currentOffset`),
in such case you usually don't want to start from the corner top-left of the initial element but to be center with the cursor for instance. To perform such need, `getDragLayerState()` needs to exposes `initialOffsetFromContainer`, otherwise AFAIK we can't compute the centered position.

**If possible, I would even prefer that the "mouse position" would be exposed. Do you know if this is possible?**

Best Regards,
gre

**Comment by gaearon** [comment]
I don't mind exposing it. Let's expose everything `DragDropContext` already exposes. Can you send a PR? You can change `getStateForDragLayerMixin` (and also `getDragLayerState`) to also return `initialOffsetFromClient`, `currentOffsetFromClient` and `initialOffsetFromContainer`.

**Comment by gaearon** [comment]
If you care about IE btw, you'll need to find some workaround for #88. IE doesn't seem to support `setDragImage`, so drag preview is visible right below custom layer. I wonder if we can temporarily hide the element while it's screenshot or do something else crazy to work around it.

**Comment by gre** [comment]
That will definitely be great to find a solution for #88.

I'm going to submit a first PR which expose these 3 objects, I don't think it will create any new bugs on IE (since those objects are used internally to compute the 2 currently returned but just not exposed).

**Comment by gaearon** [comment]
I'll get this into the next release, anything else you'd like to do before I cut it?

**Comment by gre** [comment]
I guess you can do the release :-)
I don't see much to do for now. That IE bug looks tricky and I don't have an IE ready to test right now.
Thanks
