### ISSUE TITLE
Incorrect hover behavior with fullsize drop targets

### ISSUE THREAD

**Issue by jbelcher** [gaearon/react-dnd#119]
I'm seeing inconsistent behavior with files dragged over an edge to edge drop target. Minimal test case: http://jsbin.com/fisocibeda/2/edit?js,console,output

`isHovering` reports false while `over()` (or in my production case, it reports false until the drag enters another DOM node). If the containing element adds some padding, `isHovering` reports correctly. You can try that out by uncommenting the padding on <body />.

**Comment by gaearon** [comment]
Hmm.. Any idea what's causing that? Does this only happen with files? (i.e. are regular drop targets OK?)

**Comment by gaearon** [comment]
Just to verify, have you checked outside JSFiddle? I have not tested it with iframes.

**Comment by jbelcher** [comment]
My use case is "drag file into window to upload" so I haven't tested it with regular drop targets. I'm seeing similar behavior in my local implementation, but it'd be tough to isolate well enough to reproduce 100%:

![](https://s3.amazonaws.com/f.cl.ly/items/1t1z1Y2V0l0U0p1T422L/Screen%20Recording%202015-03-15%20at%2003.16%20PM.gif)

I know the Khan folks had to do a bit of book keeping with these types of drag entrances (https://github.com/Khan/react-components/blob/master/js/window-drag.jsx), but it looks like react-dnd is doing similar things with EnterLeaveMonitor.

**Comment by gaearon** [comment]
Does this only happen with fullsize targets?
Can you reproduce the same with [this live example](http://gaearon.github.io/react-dnd/#/dustbin-interesting)? (The last box accepts files.)

**Comment by jbelcher** [comment]
Yes, only with fullsize targets as far as I can tell.

I can reproduce the same behavior w/ the live example. I added the following CSS to Native File dustbin:

```
position: absolute;
top: 0;
left: 0;
width: auto;
height: auto;
margin: 0
```

When a file comes into the window, `isDragging` fires, but not `isHovering`. Once you hover the item over the child label, `isHovering` fires:

![](https://s3.amazonaws.com/f.cl.ly/items/0k0I1Y3C1J1h371o3739/Screen%20Recording%202015-03-15%20at%2005.18%20PM.gif)

If that element is not fullsize it seems to work correctly. Here's an example where the dustbin has a bit of right margin:

![](https://s3.amazonaws.com/f.cl.ly/items/1n04400o1k111u1Z0m3R/Screen%20Recording%202015-03-15%20at%2005.19%20PM.gif)

**Comment by jbelcher** [comment]
Digging in a bit—in the fullsize example `createDragDropMixin.handleDragEnter()` is called before `HTML5.handleTopDragEnter()` due to bubbling, and before the `DRAG_START` action as a result.

**Comment by gaearon** [comment]
I can repro this. Working on it.

**Comment by gaearon** [comment]
Should be fixed in 0.9.8. Please verify!

**Comment by jbelcher** [comment]
Yup looks great over here! This is a truly fantastic abstraction and implementation. Thanks for your work on it.

**Comment by gaearon** [comment]
It's only going to get better! ;-)
