### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by vkbansal** [gaearon/react-dnd#120]
React-dnd works in chrome and opera on windows but not on firefox.

**Chrome**:
![chrome](https://cloud.githubusercontent.com/assets/5930351/6662778/9d2350de-cbe5-11e4-916b-d00a6fe6d1b2.gif)

**Firefox**:
![firefox](https://cloud.githubusercontent.com/assets/5930351/6662795/c66a6d24-cbe5-11e4-913e-6772bcb68cb1.gif)

**Comment by gaearon** [comment]
Generally it works in Firefox ([e.g. try examples](http://gaearon.github.io/react-dnd)). If you found a case where it breaks, please find a way to reproduce with a smaller example so we can fix it!

**Comment by vkbansal** [comment]
Yes the examples are working fine. I don't know why my code isn't working.
I replicated the code from examples exactly.

**Comment by vkbansal** [comment]
This is the code for `Columns`.
```jsx
"use strict";

let React = require("react"),
    { DragDropMixin } = require("react-dnd"),
    ItemTypes = require("./item-types");

const itemDragSource = {
    beginDrag(component) {
        return {
            item: {
                name: component.props.name
            }
        };
    }
};

module.exports = React.createClass({
    mixins: [DragDropMixin],
    statics: {
        configureDragDrop(register) {
            register(ItemTypes.COLUMN, {
                dragSource: itemDragSource
            });
        }
    },
    render() {
        return (
            <a href="#" onClick={this.cancelClick}>
                <span {...this.dragSourceFor(ItemTypes.COLUMN)}>
                    <b className="fa fa-columns"/>&nbsp;{this.props.label}
                </span>
            </a>
        );
    },
    cancelClick(event){
        event.preventDefault();
    }
});
```
Can `cancelClick` can be the culprit?

**Comment by gaearon** [comment]
Can you post the full standalone example that reproduces the problem in a separate Github repo? Your code looks fine, so you must be hitting some edge case.

**Comment by gaearon** [comment]
Never mind, I see what's wrong. Will try to fix that now.

**Comment by gaearon** [comment]
This is a Firefox issue. It doesn't fire `dragstart` event if the element is wrapped in `<a>` tag. We're not going to fix this in React DnD any time soon (that would require too much of a rewrite, and I'm pretty sure it's a browser bug).

You can easily work around this: **just move `{...this.dragSourceFor(ItemTypes.COLUMN)}` to be on `<a>` element itself**:

```js
    render() {
        return (
            <a href="#" onClick={this.cancelClick} {...this.dragSourceFor(ItemTypes.COLUMN)}>
                <b className="fa fa-columns"/>&nbsp;{this.props.label}
            </a>
        );
    },
```

This fixes the problem.

**Comment by vkbansal** [comment]
Thanks once again! You are awesome! 
(*Bows down*)

**Comment by gaearon** [comment]
No prob! Thanks for reporting.

**Comment by sandeshsoni** [comment]
Thanks @gaearon for letting us know that this is a Firefox issue. I had used Buttons and it did not work on firefox but was working on chrome.

**Comment by ivansglazunov** [comment]
Then what replacing `dragSourceFor` now?
Or how trigger `onDragStart` event for buttons manually, if root element of `connectDragSource` sets `ref` to it?
Thanks.
