### ISSUE TITLE
Problem in Chrome with itemDropTarget function

### ISSUE THREAD

**Issue by soda29** [gaearon/react-dnd#121]
This is really silly but i got a problem with Chrome (is fine in Firefox) with this function:

```javascript
const itemDropTarget = {
    acceptDrop(component, item) { *
        component.setItem(item);
    }
};
```
It trigger this error:
* Uncaught SyntaxError: Unexpected token (

Chrome doesn't like this either:

```javascript
const DustbinSimple = React.createClass({
    render() {
```
It must be:

```javascript
const DustbinSimple = React.createClass({
    render: function() {
```

What am i missing?

Thanks in advance.

**Comment by soda29** [comment]
I found what was the problem... 
I needed to compile JSX code using --harmony flag with reactify/browserify:

...
bundler.transform(["reactify", {"harmony": true}]);
...

**Comment by gaearon** [comment]
Yeah, it's ES6 syntax. It's optional but I like to use it. I actually advise you to use [Babel](https://babeljs.io/) since it's better than JSX's transformer (and also can handle JSX).

**Comment by soda29** [comment]
I will take a look at Babel. Thank you very much!
