### ISSUE TITLE
DropTargetAPI: Native File / URL not being passed except in Drop

### ISSUE THREAD

**Issue by cuongvo** [gaearon/react-dnd#123]
Love the library! Ran into an issue: 

https://github.com/gaearon/react-dnd/blob/master/modules/utils/createDragDropMixin.js#L359

The check above (and extraction of native file types) only happens in `Drop` and not in `Enter`, `Leave`, `Over`.

Is this due to some limitation of the HTML5 API? Use case: check file extension on `Over` and display a warning if dropping it wouldn't be acceptable.

**Comment by gaearon** [comment]
It's a limitation of the HTML5 API. We can't know anything about the files until the drop event.

:-(
