### ISSUE TITLE
Question: Drag handle, constrain drag movement

### ISSUE THREAD

**Issue by jamie-brown** [gaearon/react-dnd#125]
Hi there, 

I have a couple of questions and wondered if you could take a quick look at them for me please? 

Before submitting these questions here I have taken a look at the API and walk through as well as diving into the source. I believe the answers are staring me in the face but lack of sleep is probably making it invisible :)

1/ I have created a sortable component that is based on the sortable example. This sortable component returns an &lt;li&gt; node that wraps around this.props.children. My question is can I specify one of the nodes within my children to be what invokes the drag so to speak? (i.e. a move icon)

2/ Is there any built in feature that lets me constrain the drag movement to just up/down?

Thank you
Jamie

**Comment by gaearon** [comment]
> My question is can I specify one of the nodes within my children to be what invokes the drag so to speak? (i.e. a move icon)

```js
beginDrag() {
  return {
    item: ...,
    dragPreview: React.findDOMNode(this.refs.myHandle)
  }
}

...

render() {
  return <div><div ref='myHandle />something</div>;
}
```

>2/ Is there any built in feature that lets me constrain the drag movement to just up/down?

It's up to you to react to drag so you can constrain the actual components in any way you like. The “ghost image” cannot be constrained unless you render [custom drag layer](http://gaearon.github.io/react-dnd/#/drag-around-custom) in which case you're free to do anything. (But it won't work in IE (yet?), see #88).

**Comment by jamie-brown** [comment]
Perfect, thank you very much for this.

**Comment by mull** [comment]
For anyone else arriving here check this link (and the source, link at the top of the page) out if you're unsure how to implement dragging by a handle. :)

http://gaearon.github.io/react-dnd/examples-customize-handles-and-previews.html
