### ISSUE TITLE
Not compatible with lodash 3.6.0

### ISSUE THREAD

**Issue by agrauch** [gaearon/react-dnd#127]
With the release of lodash 3.6.0 today, statements like 
```javascript
isObject = require('lodash/lang/isObject')
```
result in module not found errors
```
ERROR in ./~/react-dnd/dist-modules/utils/createDragDropMixin.js
Module not found: Error: Cannot resolve module 'lodash/object/defaults' in /Users/pairing/projects/sombrero/node_modules/react-dnd/dist-modules/utils
 @ ./~/react-dnd/dist-modules/utils/createDragDropMixin.js 14:15-48
```

**Comment by gaearon** [comment]
>Cannot resolve module 'lodash/object/defaults'

It's definitely [still there](https://github.com/lodash/lodash/blob/3.6.0-npm/object/defaults.js). No doubt this would be a breaking change for Lodash.

I also can't reproduce this. After installing `lodash@3.6.0` everything works as expected. Can you try deleting both `react-dnd` and `lodash` from `node_modules` and running NPM again? Might be some NPM issue. Also make sure to restart Webpack dev server :-)

**Comment by agrauch** [comment]
Strange, must have been an NPM issue. We basically saw a clone of `lodash#master` in `node_modules`. Although we did see this on several development machines and a build server. Deleting `node_modules` and running `npm install` again seems to have fixed the problem and webpack is happy again. I have no idea why.

Thanks for the fast reply.

**Comment by gaearon** [comment]
No prob, NPM is weird but it's the best we got so :heart:
