### ISSUE TITLE
IE 9 Support

### ISSUE THREAD

**Issue by balloob** [gaearon/react-dnd#128]
While using React DND I ran into an issue with IE 9. IE 9 will start selecting text instead of dragging the element. I got it working by creating the following mixin:

```javascript
var ReactDNDIE9MixIn = {
  componentDidMount: function () {
    if (navigator.appVersion.indexOf("MSIE 9") !== -1) {
      this.getDOMNode().addEventListener('selectstart', this.ie9fix);
    }
  },

  componentWillUnmount: function () {
    if (navigator.appVersion.indexOf("MSIE 9") !== -1) {
      this.getDOMNode().removeEventListener('selectstart', this.ie9fix);
    }
  },

  ie9fix: function(ev) {
    ev.preventDefault();
    this.getDOMNode().dragDrop();
  },
};
```

I couldn't find if React DND supports IE9. If it does, shall I create a pull request to put it in the DragDropMixin or should it live as a separate mixin?

It if does not,at least this issue might help future people trying to get React DND working with IE9.

**Comment by gaearon** [comment]
Woah. I never even heard about `dragDrop`. Is this the only issue in IE9? I don't officially support it (I only test 10+), but if it's the only problem I guess we can try making it work.

**Comment by balloob** [comment]
We are using a variant of the sortable example with IE 9 and it works good enough after this fix.

Good enough because there is a weird issue that if you drag and drop a lot and fast it breaks the DOM: certain draggable items disappear and others have certain sub-DOM elements missing. It is still possible to drag and drop the other items. It only happens in rare occasions and only on IE 9.

**Comment by GeReV** [comment]
I suggest taking another approach to this fix, just so you don't have to check the `appVersion` string.

The `dragDrop` method should be limited and unique to IE browsers, so it's probably better to check for its existence and verify it's a function, over checking the reported browser version.

This might also give you this fix for other IE version for free, if they support it, regardless of version.

**Comment by balloob** [comment]
I just tested it and calling `dragDrop` doesn't have any side effects on IE 10. But then again, it doesn't need the fix to drag and drop either.

**Comment by gaearon** [comment]
Let's get this in in the next version.

**Comment by gaearon** [comment]
I'm closing the issue because `v1.0.0-alpha` has this behavior and is fairly stable.
The final 1.0 is not yet released but will be in a week's time.

**Comment by gaearon** [comment]
1.0 is released and should have a fix for this issue. Please verify if you have the time.

**Comment by balloob** [comment]
Awesome Dan! I will give it a try soon and let you know.

Paulus

On Mon, May 18, 2015 at 6:20 PM, Dan Abramov <notifications@github.com>
wrote:

> 1.0 is released and should have a fix for this issue. Please verify if you
> have the time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaearon/react-dnd/issues/128#issuecomment-103292255>.
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.
