### ISSUE TITLE
Support for instances of same React component to register different ItemTypes

### ISSUE THREAD

**Issue by willashe** [gaearon/react-dnd#135]
I have a use case in which I have a simple drag-sortable list wherein each list-item also contains a nested drag-sortable list.  The issue I'm running into has to do with the fact that all of the nested-list-items are of the same React class and therefore all get registered with the same ItemType.  The result is that when a user drags a nested item from one list to a different list it is recognized as a drag/over/drop action.  Drag/over/drop actions should only be triggered if the nested item is being dragged within its parent list.

So I need a way to use the same nested-list-item component in different lists with some sort of ItemType that is unique to the list it is contained in.  The closest I've been able to get is to use a mixin to dynamically change the ItemType for each nested item according to its parent list-item, but this does not work because each call to configureDragDrop overrides the previous for all instances of the same class.

Hopefully the above makes sense, I'm attaching a screenshot of the interface to help clarify my situation (the styling is very rough but the nested lists I'm referring to are the ones with the "Parts" headers.  Any insight would be greatly appreciated.

![screen shot 2015-04-09 at 4 43 08 pm](https://cloud.githubusercontent.com/assets/3373615/7077580/9f2bfaac-ded7-11e4-9dd6-57b836468290.png)

**Comment by willashe** [comment]
Thinking about this more...I believe what's happening is that since all of the nested-list-item components share their static methods, each time configureDragDrop is called, every already-existing item is re-registered with the new itemType, effectively over-writing its previous registration.

**Comment by gaearon** [comment]
>Drag/over/drop actions should only be triggered if the nested item is being dragged within its parent list.

Have you tried [`canDrop`](https://github.com/gaearon/react-dnd/blob/master/docs/API.md#candropcomponent-reactcomponent-item-object-boolean)? Returning `false` for certain items should have the same effect as them having a different type.

For example,

```js
canDrop(component, item) {
  return item.listId === component.props.id;
}
```

>The closest I've been able to get is to use a mixin to dynamically change the ItemType for each nested item according to its parent list-item

Don't go there, it's too hackish :-).

In the next version of React DnD, dynamic types dependent on `props` will be supported, but you are still encouraged to use `canDrop` for this purpose as it's much simpler. Conceptually there should be very few types (e.g. `product`, `part`, `constraint` in your example).

Does this help?

**Comment by gaearon** [comment]
Closing this out, let me know if I missed something.
