### ISSUE TITLE
I can't make simple sort work and I have no idea why.

### ISSUE THREAD

**Issue by fungku** [gaearon/react-dnd#137]
I want a user to be able to sort the form fields (a.k.a. properties) 

I [set up the code](https://github.com/SevenShores/Kraken/tree/master/resources/assets/jsx/Forms) almost identical to the Cards in the simple sort demo. There are no console warnings or errors, and I can't figure out why this won't work.

![React Form](https://photos-3.dropbox.com/t/2/AABtB0Jh_3nbFEV_0ClnvOXrAmYEeITOMCnxIZ9n0yZfgw/12/57631425/png/1024x768/3/1429218000/0/2/Screenshot%202015-04-16%2010.58.36.png/CMHFvRsgASACIAMoASgC/C25YA9NpiH8qBRw-DCvc-CMy65F8TBCprj475njB_Fs)

If anybody could help I would greatly appreciate it. It's kind of sad how much time I've actually spent trying to figure this out.

code: https://github.com/SevenShores/Kraken/tree/master/resources/assets/jsx/Forms

**Comment by gaearon** [comment]
How do I run that project?

**Comment by fungku** [comment]
To install the project for dev, there is a few steps...

 1. clone git repo
 2. `composer install`
 3. `cp .env.example .env`
 4. edit .env for db credentials
 5. `php artisan migrate --seed`  # to set up and seed the db
 6. `npm install`
 7. visit the url to your dev server http://your-server.local/forms

or you can see it on the dev server i just set up http://dev.kraken.sevenshores.io/forms/4/edit

**Comment by gaearon** [comment]
@fungku I'm not entirely convinced `<a>` links will work as drag sources. This conflicts with browser's default interpretation of `<a>` dragging as dragging a URL. Try wrapping them in `<div>`s and putting `this.dragSourceFor` and `this.dropTargetFor` on `<div>` instead?

**Comment by fungku** [comment]
@gaearon I've changed the `a` to `div` for now, but it is still the same problem. Thanks

**Comment by gaearon** [comment]
I don't have PHP ecosystem installed.. Can you fire up a server somewhere so I could run just JS code?

**Comment by fungku** [comment]
if you want to send  me your public key i'll give you access to a server i'm firing up fungku@gmail.com if you want

**Comment by fungku** [comment]
After spending nearly *all* day trying to get this working I just fixed it with this

https://github.com/SevenShores/Kraken/commit/397a3486fa07e4019face32be591340aca7859bb

**Comment by gaearon** [comment]
Woah.. how did it not crash before? Did it use global React or something?

**Comment by fungku** [comment]
@gaearon  No errors when compiling from JSX, no warnings or errors in console, and react components rendered fine on the page, but could not drag nor drop...

This is what baffles me.

**Comment by gaearon** [comment]
@fungku 

You might have a second, global React. Two Reacts on the same page will conflict in weird ways: https://github.com/facebook/react/issues/2402. Events not working is a symptom of that.

For some reason you're including React both in http://dev.kraken.sevenshores.io/js/components/bundle.js and http://dev.kraken.sevenshores.io/build/js/vendor-6fd6791d.js on your page. This is how you got two Reacts.

**Comment by fungku** [comment]
@gaearon nice catch!

thanks!
