### ISSUE TITLE
Custom dragPreview offset?

### ISSUE THREAD

**Issue by jbelcher** [gaearon/react-dnd#142]
I'm porting some code over to react-dnd, and I'm using a custom HTMLElement for dragPreview w/ a custom x/y offset (so that the cursor is centered on the preview as you drag it out). Is there an idiomatic way of setting custom dragPreview offsets in react-dnd? Or plans to surface that in the rewrite?

**Comment by gaearon** [comment]
>(so that the cursor is centered on the preview as you drag it out)

Currently we try to do the smarter thing and align the drag preview so it appears “at the same place” as you began dragging it. It feels better than always centering the drag preview (it will jump if you drag far from center, which isn't very nice).

Why do you want to always center it? We can definitely expose a way to do this. Just want to learn more about why the default behavior doesn't work for you.

**Comment by jbelcher** [comment]
You definitely have the right default—this is just a special case where the size/appearance of the dragPreview is unrelated to the source.

![](https://s3.amazonaws.com/f.cl.ly/items/3X041E2B14092e1Z3u1V/Screen%20Recording%202015-04-20%20at%2004.22%20PM.gif)

**Comment by gaearon** [comment]
Oh, I see. Let's make it configurable in 1.0 then. It's coming first week of May.

**Comment by jbelcher** [comment]
Cool—will that have a React 0.13 prereq?

**Comment by gaearon** [comment]
Yes.

**Comment by jbelcher** [comment]
Sounds good, thanks.

**Comment by gaearon** [comment]
Let's keep it open so I don't forget!

**Comment by jbelcher** [comment]
=)

**Comment by gaearon** [comment]
Would you like to take a stab at it? I'm pretty busy with preparing 1.0 release so could use a little help.

**Comment by jbelcher** [comment]
Sure—I'll take a look this weekend.

**Comment by gaearon** [comment]
The new version is somewhat different. The best way to contribute would be to check out `dnd-core` branch, do `npm install && npm start` and then open “custom drag handles” example.

You will find [the logic that does the offset calculation here](https://github.com/gaearon/react-dnd/blob/dnd-core/src/utils/OffsetHelpers.js#L26). I'm not sure whether it makes a lot of sense so I suggest you make something that works for you, and we figure out the minimal API that accommodates both yours and mine use cases.

**Comment by gaearon** [comment]
This probably won't get into 1.0 because I'm releasing it really soon. Feel free to submit a PR though!

**Comment by jbelcher** [comment]
BTW—for my use case I've found this easy enough to implement with the existing API. I'm just using a DragLayer and monitoring `getClientOffset()` directly instead of `getSourceClientOffset()`. I'll leave to you whether this issue should stay open or not, but it feels like most variations of this are possible with what's there and standard props.

**Comment by gaearon** [comment]
Closing for the lack of interest.
