### ISSUE TITLE
Cancelling a drag in the sortable-simple example

### ISSUE THREAD

**Issue by ockham** [gaearon/react-dnd#144]
I've been trying out 1.0.0-alpha.2, and so far, I like it.

I'm trying to use it to implement something sortable, so I've checked out the sortable-simple example. I've noticed that an item is actually being moved already while dragging -- albeit with a different styling to get some sort of placeholder. While this is a nifty idea, it's probably not quite suitable for my purpose: First and foremost, cancelling the drag -- by not actually dropping onto a drop target -- in the example leaves the item where it has been moved during dragging. However, we want our users to be able to actually abort the drag, i.e. return the item to its source position in such a case.

We're considering using special (usually invisible) drop target items to that end, but I wanted to ask if I've overlooked any functionality built into react-dnd that would provide us with such a solution?

**Comment by gaearon** [comment]
>First and foremost, cancelling the drag -- by not actually dropping onto a drop target -- in the example leaves the item where it has been moved during dragging.

That's what Trello does, so I modeled it after them. I think it's a reasonable behavior, but it surely depends on the app :-)

Can I ask you more about the behavior you'd like? Do you still want the placeholder to move while dragged, *but* abort and rollback if released outside the list? Or do you not even want the placeholder to move?

**Comment by ockham** [comment]
> Do you still want the placeholder to move while dragged, but abort and rollback if released outside the list?

Yeah, I think that'd be best.

**Comment by gaearon** [comment]
I pushed a `sortable-cancelable` example to `dnd-core` branch, please check it out. It should do what you wanted.

**Comment by ockham** [comment]
Thanks a lot!
