### ISSUE TITLE
Shallowness?

### ISSUE THREAD

**Issue by twobit** [gaearon/react-dnd#148]
From [The Future of Drag and Drop APIs](https://medium.com/@dan_abramov/the-future-of-drag-and-drop-apis-249dfea7a15f) there is a concept of shallowness:

> In the next version, we’re going to provide an API that makes all of these scenarios possible. Each target will be able to learn if it’s being hovered by calling the isOver(handle, shallow=false) method. When shallow is false, it will return true even if the cursor is over some child drop target. When shallow is true, it will only return true if you’re hovering over the target’s own area exclusively. It is up to the target to choose whether it wants to appear highlighted.

Is this in the roadmap for 1.0 or sometime after? I didn't see any reference to it in the latest RC.

**Comment by gaearon** [comment]
Yeah, you can do that with `monitor.isOver({ shallow: true })`. See the “nested targets” example where greedy and non-greedy targets behave differently. They use `isOver` internally.
