### ISSUE TITLE
Restrict number of "dropped" into Container/Dustbin

### ISSUE THREAD

**Issue by benhowdle89** [gaearon/react-dnd#149]
Is there a way to restrict the number of items dropped into a dropzone, in a React-DnD-specific way, or is it best to set up my own state tracking?

**Comment by benhowdle89** [comment]
Really wish GitHub would let me label this as "This is not urgent, or a bug, just a mild curiosity" :smiley:

**Comment by vkbansal** [comment]
As far as I know, setting up your own state tracking is the way to go.

**Comment by benhowdle89** [comment]
Sounds good to me. Fairly trivial to implement, thanks! :+1:

**Comment by gaearon** [comment]
Yeah, this is totally the app's concern. One of the reasons React DnD is “low-level” is that you can implement stuff like this in your app easily.
