### ISSUE TITLE
Unable to make a single div accept more than one ItemType

### ISSUE THREAD

**Issue by adamellsworth** [gaearon/react-dnd#150]
The below code works if I only keep `ItemTypes.PLAYER` but once I add `ItemTypes.LOCATION` it no longer evaluates for either player or location.

```
<div className="item" {...this.dropTargetFor(ItemTypes.PLAYER)} {...this.dropTargetFor(ItemTypes.LOCATION)}>
    {this.getDropState(ItemTypes.PLAYER).isHovering ? 'Release to drop' : 'Drag item here'}
</div>
```

**Comment by vkbansal** [comment]
try
```
<div className="item" {...this.dropTargetFor(ItemTypes.PLAYER, ItemTypes.LOCATION)}>
    {this.getDropState(ItemTypes.PLAYER).isHovering ? 'Release to drop' : 'Drag item here'}
</div>
```

**Comment by adamellsworth** [comment]
@vkbansal Brilliant, thanks! That did it. I couldn't find an example of that syntax.

**Comment by vkbansal** [comment]
It's mentioned in [docs/walkthrough.md#what-else-is-possible](https://github.com/gaearon/react-dnd/blob/57dcf1c9564c106e2aabe6366bdb6ff7a25bb5ec/docs/Walkthrough.md#what-else-is-possible)

**Comment by gaearon** [comment]
Yep, that's the right way.

**Comment by twobit** [comment]
Can the new API also support this? Accepting either string or array as the first parameter:

```
@DropTarget(['item1', 'item2'], Target, connect => ({
  connectDropTarget: connect.dropTarget()
}))
```

Sure, we could stack decorators but it can be a bit ungainly for a larger list.

**Comment by gaearon** [comment]
It should. For `DropTarget`, `type` can be a string, a symbol, **an array of either**, or `props => whatever I just listed`.
