### ISSUE TITLE
Standalone UMD for Code Playgrounds/CDN

### ISSUE THREAD

**Issue by MadLittleMods** [gaearon/react-dnd#152]
A standalone UMD module would be nice when playing around with ReactDND in a code playground like jsFiddle or CodePen. You could just add a URL to the standalone script and access it via:

`window.ReactDND`

### Creating a standalone bundle with webpack

```
node ./node_modules/webpack/bin/webpack.js --output-library ReactDND --output-library-target umd ./dist/ReactDND.min.js --output-file ReactDND-standalone.js
```

*See [standalone section in webpack for browserify users](http://webpack.github.io/docs/webpack-for-browserify-users.html#standalone)*

### Creating a standalone bundle with Browerify

```
npm install browserify derequire --save-dev
```

```
node ./node_modules/browserify/bin/cmd.js ./dist/ReactDND.min.js --standalone ReactDND | node ./node_modules/derequire/bin/cmd.js -f define -t _defi_ | node ./node_modules/derequire/bin/cmd.js -f require -t _dereq_ > ReactDND-standalone.js
```

**Comment by gaearon** [comment]
It's in the [`dist` folder](https://github.com/gaearon/react-dnd/tree/master/dist).

**Comment by MadLittleMods** [comment]
@gaearon hmmm, I could of swore it didn't emit anything to the `window` object but it seems to be there now.

Looks like it was completely my oversight.
