### ISSUE TITLE
Issues in cross-window dragging.

### ISSUE THREAD

**Issue by egonelbre** [gaearon/react-dnd#156]
I experimented with cross-instance dragging i.e. from one browser window to another, it doesn't seem to work. I didn't do any extensive debugging why it didn't; maybe there was some option to turn it on. Or maybe it's out of the scope of this project, anyways.

You can reproduce using the [Drag Around Naive](https://gaearon.github.io/react-dnd/examples-dustbin-single-target.html) or the [Dustbin](https://gaearon.github.io/react-dnd/examples-dustbin-single-target.html) examples.

**Comment by gaearon** [comment]
It's not currently supported. [It seems](http://stackoverflow.com/a/3694684/458193) that it might be possible to support this, but I'm not sure how much work this is, and there will definitely be many limitations.

I'm open for considering a PR that adds the support for this to HTML5 backend, but I don't have plans to implement cross-window dragging.

**Comment by designbyadrian** [comment]
This would have been so amazing! Is there a feature request section somewhere?

**Comment by knownasilya** [comment]
Is this still not supported?
