### ISSUE TITLE
Can a single component be also a DragSource as well as DropTarget

### ISSUE THREAD

**Issue by mech** [gaearon/react-dnd#157]
I believe a single component can be a DragSource as well as a DropTarget. I am doing a sortable `<Layer>` component sort of like your `<Card>` example. My question is how do I do both without using ES7?

In your `<Card>` example, you have

```js
@DropTarget(ItemTypes.CARD, cardTarget, connect => ({
  connectDropTarget: connect.dropTarget(),
}))
@DragSource(ItemTypes.CARD, cardSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging()
}))
export default class Card {
}
```

But I want to only use ES6, so how do I combine both DragSource and DropTarget in here:

```js
class Layer extends Component {
}

// Where to put the DropTarget??
export default DragSource('layer', layerSource, collect)(Layer);
```

Is it I have to use `_.flow()` from lodash?

**Comment by mech** [comment]
Okay I think I found the answer, probably doing this will do

```js
Layer = DropTarget('layer', layerTarget, collect)(Layer);
Layer = DragSource('layer', layerSource, collect)(Layer);

export default Layer;
```

Sort of stacking on top of each other.

**Comment by gaearon** [comment]
See the FAQ: http://gaearon.github.io/react-dnd/docs-faq.html#how-do-i-combine-several-drag-sources-and-drop-targets-in-a-single-component-

>Because DragSource and DropTarget use the partial application, you may compose them using a functional composition helper such as _.flow. In ES7, you can just stack the decorators to achieve the same effect.

>```js
>var DragSource = require('react-dnd').DragSource;
>var DropTarget = require('react-dnd').DropTarget;
>var flow = require('lodash/function/flow');

>var YourComponent = React.createClass({
>  /* ... */
>});

>module.exports = flow(
>  DragSource(/* ... */),
>  DropTarget(/* ... */)
>)(YourComponent);
>```

**Comment by jawb** [comment]
Hi,

Can you give a full example ? I'm not sure how to stack connectDragSource and connectDropTarget in render method.

Many thanks

**Comment by gaearon** [comment]
@jawb 

Check out [`Card` in `sortable-simple`](https://github.com/gaearon/react-dnd/blob/65a85fc62da5f2ec23d6da25b92007bc56dbfdd3/examples/04%20Sortable/Simple/Card.js#L50-L54).

**Comment by jawb** [comment]
I followed the example here https://github.com/gaearon/react-dnd/blob/master/examples/04%20Sortable/Simple/Card.js , but the issue I'm having is not being able to access component from hover method it's an instance of DragDropContainer.

**Comment by gaearon** [comment]
Good point. I'd say accessing instance is usually an anti-pattern. Why do you need it?

Anyway, you can access the “original” component by `component.getDecoratedComponentInstance()`.

**Comment by jawb** [comment]
I'm using Fluxxor and I need to access `this.getFlux()` to dispatch an action, it's bound to the component.
Thanks for the trick I'll try it, I'm going to switch to Redux soon anyway just trying to finish the dnd things first :smile:

**Comment by Carmezim** [comment]
According to the FAQ: 
```
export default flow(
  DragSource(/* ... */)
  DropTarget(/* ... */)
)(YourComponent);`
```
however it does not allow multiple default exports, stacking as above would be the approach?

Thanks

**Comment by StanislavStadnyk** [comment]
I guess it will be useful for someone
@DropTarget and @DragSource ES7 to ES6
The solution is there: 
https://q-a-assistant.info/computer-internet-technology/how-to-convert-decorator-syntax-to-es6/725444
