### ISSUE TITLE
IE bookmarklet link drag disabled

### ISSUE THREAD

**Issue by Predjo** [gaearon/react-dnd#158]
So this is a pretty specific issue. It affects only IE (tested in IE10 & IE11) and only [bookmarklet](http://en.wikipedia.org/wiki/Bookmarklet) links. 
While using React DnD all bookmarklet links become completely undraggable. Users are unable to drag them to the Favorites bar. Normal links are unaffected. 

Problem might be related with the 'dragstart' listeners in the HTML5 backend. (Tested by commenting them out, which fixed that problem but ofc broke the plugin)

CodePen to showcase the problem: http://codepen.io/npredovan/pen/Kpgdvo

**Comment by freakycue** [comment]
+1. Experienced the same issue and it's very annoying. Any way of fixing this would be very handy.

**Comment by gaearon** [comment]
Can you please test if this branch solves the issue?

https://github.com/gaearon/react-dnd/pull/159

My BrowserStack trial has expired while I tried to fix it..

You can

```js
npm install
npm start

# wait quite a bit
open http://localhost:8080/examples-dustbin-multiple-targets.html
```

and try dragging the test link onto the favorites bar.

If this works, let me know and I'll refactor a little and release this as a patch.

**Comment by gaearon** [comment]
For some context, the problem is that IE interprets links without a valid `href` not as links, but as draggable text. Which got me thinking that we actually should support draggable text, it's a valid use case.

**Comment by Predjo** [comment]
Tried it but getting an error on that page: `Uncaught ReferenceError: Component is not defined IndexPage.js?8307:158`

**Comment by gaearon** [comment]
Are you doing a clean install? It might not work inside your `node_modules` if that's where you're running it.

**Comment by Predjo** [comment]
Yap clean install. Other pages seem to work fine, only problem is with examples.

**Comment by gaearon** [comment]
@Predjo 

You're right. It seems like a Babel bug. 
You should be able to fix it by replacing `Component` with `ExampleComponent` in `IndexPage` on 115 and 120 lines.

**Comment by Predjo** [comment]
@gaearon 
New problem. Everything now works in chrome but in IE this error:
`'Symbol' is undefined File: eval code (583), Line: 39, Column: 1`

**Comment by gaearon** [comment]
@Predjo 

Whoops! I forgot to include the polyfill. Can you just change them back to strings like in the current version?

**Comment by gaearon** [comment]
I'm talking about these lines:

https://github.com/gaearon/react-dnd/pull/159/files?diff=unified#diff-56783ea3de7884c02df6b7259025eb8dL11

**Comment by Predjo** [comment]
@gaearon 
Hehe finally managed to run it and it works. Im able do drag it around and drop it to Favorites bar :+1:

**Comment by gaearon** [comment]
OK, great. I'll refactor and release this in a few days.

**Comment by Predjo** [comment]
Hey @gaearon any ETA on the new release that includes this fix?

**Comment by gaearon** [comment]
This should be fixed in 1.1. Please verify.

**Comment by Predjo** [comment]
Confirmed working, thx @gaearon :+1:

**Comment by gaearon** [comment]
(Also please skip 1.1 and go straight to 1.1.1 because it fixes a Safari bug)
