### ISSUE TITLE
Dropping of native URLs is not working on Chrome

### ISSUE THREAD

**Issue by smvilar** [gaearon/react-dnd#160]
Please check the example at: http://gaearon.github.io/react-dnd/examples-dustbin-multiple-targets.html

I'm testing on Chrome 42

**Comment by smvilar** [comment]
Note: this happened to me only when dragging from the icon of the search bar

**Comment by gaearon** [comment]
What is your use case for supporting drop of the search bar icon? I don't see a problem with any other links, even the ones from the other windows. Could this be a Chrome bug?

**Comment by smvilar** [comment]
Hi @gaearon, it worked perfectly on previous versions of react-dnd (I think 0.9.8).
The strange thing is that the `monitor` object will return `isOver()` and `canDrop()` fine, but the `drop` function is never called. The same thing seems to happen in your example as the hover will work but nothing occurs when dropping.
Also, you can try dragging a link from the icon to a `<input>` tag in Chrome and it will work.

**Comment by gaearon** [comment]
Thanks for the additional info. Can you tell more about your use case?

**Comment by gaearon** [comment]
It appears that 6d54bb55b0e3eaabbc88c05554bac9cbcb3777b6 somehow fixed this too.
Yay!

This is out on NPM as 1.1.
