### ISSUE TITLE
Support for React v0.12

### ISSUE THREAD

**Issue by joshbedo** [gaearon/react-dnd#161]
I installed this a few days ago and it supported React 0.12 but i just tried to update the module and now it's giving me a `peer dependency` saying it's not compatible because we don't use 0.13. I'm thinking it should support both, not too many people are using 0.13 especially since every minor release of React has breaking changes in the api. I was wondering if this was easily supportable or are there newer 0.13 features you're using that can't be used with 0.12.

**Comment by gaearon** [comment]
I'm using callback refs which aren't available in 0.12.
I rely on them pretty heavily so there's just no easy way to support 0.12 at the same time. Sorry!

You can keep using 0.9.x which supports 0.12.

**Comment by joshbedo** [comment]
@gaearon is there any documentation that exists anymore for 0.9.x?

**Comment by gaearon** [comment]
It's here, under the tag: https://github.com/gaearon/react-dnd/tree/v0.9.8/docs

**Comment by joshbedo** [comment]
shweet thanks
