### ISSUE TITLE
DragDropContext wrapping class that is responsible for other contexts

### ISSUE THREAD

**Issue by jackphel** [gaearon/react-dnd#163]
E.g. wrapping the outermost class which is already responsible for providing theme context for inline styles.
Does https://github.com/gaearon/react-dnd/blob/master/src/DragDropContext.js support this?

**Comment by gaearon** [comment]
Shouldn't be a problem. React should compose the unrelated contexts. Please reopen if there is an issue.

**Comment by jackphel** [comment]
suppose there's

```javascript
class App extends React.Component {
  render() {
    return ...
  }
  getChildContext() {
    return { cssTheme: UGLY_CSS };
  }
};
App.childContextTypes = {
  cssTheme: React.PropTypes.string.isRequired
};

var DDApp = DragDropContext(HTML5Backend)(App);
```
won't `DDApp.getChildContext()` https://github.com/gaearon/react-dnd/blob/master/src/DragDropContext.js#L46 not have `cssTheme` on the returned object, and also DDApp.childContextTypes not have `cssTheme`?

**Comment by gaearon** [comment]
Why not? `DragDropContext` wraps your class into another React class that renders your class. It does not overwrite your class.

**Comment by jackphel** [comment]
Isn't this what's going on? http://www.es6fiddle.net/ia03x4zi/

**Comment by jackphel** [comment]
Isn't this necessary? http://www.es6fiddle.net/ia041tcs/

**Comment by gaearon** [comment]
No. :-)
Just run the examples, try it and you'll see that it's not necessary.

React merges the context from different components.
There's no need to do it manually.

**Comment by jackphel** [comment]
Oh, I see. 
The wrapper is a component outside the inner component and react will use both of their contexts. 
Your codebase is really prompting me to figure out more es7. I love all the documentation and specification you have.

**Comment by gaearon** [comment]
Thank you! Yeah, React merges context from all components in the owner tree. (It will switch to the parent tree in 0.14 but that doesn't change anything for us.)
