### ISSUE TITLE
Upgrade guide from 0.9.x to 1.0.0

### ISSUE THREAD

**Issue by vkbansal** [gaearon/react-dnd#165]
I've been using `v0.9.x` of this library and I'm very familiar with that api.

Now I'm looking to upgrade to `v1.0.0`. I went through the docs but the new api seems very confusing to me. Can you provide a simple upgrade guide ?

**Comment by gaearon** [comment]
Unfortunately at the moment I can't spend more time on 1.0 than I did already. Just treat it as a new library and check out [the overview](http://gaearon.github.io/react-dnd/docs-overview.html) and then follow through [the tutorial](http://gaearon.github.io/react-dnd/docs-tutorial.html).

I'm happy to merge an upgrade guide to the docs if somebody steps up to contribute it, but I just don't have the time to do this myself. Sorry!

**Comment by vkbansal** [comment]
OK. No problem. 

Thanks for your efforts for this awesome library. :+1:
