### ISSUE TITLE
Why use lodash instead of ImmutableJS

### ISSUE THREAD

**Issue by ntucker** [gaearon/react-dnd#166]
Seems like immutable is going to be the standard for React applications since those structures work best. I don't like including another giant library (lodash) that isn't needed just for drag&drop

**Comment by gaearon** [comment]
If you look closely, lodash as a whole is not used in React DnD. Only a few individual functions are imported as separate modules. As far as I know, ImmutableJS as a whole is larger than those individual modules from lodash I am using.

**Comment by ntucker** [comment]
Ok, thanks for the feedback, I appreciate your codes! :)
