### ISSUE TITLE
Spec props arg isn't actually the component

### ISSUE THREAD

**Issue by chrishoage** [gaearon/react-dnd#167]
I am using Alt and ES7 decorators. 

Alt's connectToStores requires to be directly on the class to read static getStores and getPropFromStores methods. 

DropTarget/DropSource pass props of the wrapper to the Spec handlers, not the Component itself 

```javascript 
@DropTarget([Draggables.VIDEO_ITEM, Draggables.TIMELINE_ITEM], dropTargetSpec, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver({ shallow: true })
}))
@connectToStores
class Schedule extends Component {
  static getStores() {
    return [EventStore]
  }
  static getPropsFromStores({scheduleId}) {
    const events = EventStore.getEvents(scheduleId)

    return {
      events
    }
  }

````

In this code example events is a prop of the Schedule component, but does not get passed to any of the DropTarget spec handlers. 

props in hover, canDrop, and drop should be the Component itself not the decorator component

**Comment by gaearon** [comment]
There's no way for React DnD to tell that a component is wrapped in an Alt (or any other library's) wrapper. This is why asking the wrapped class to provide static methods is a worse API than directly putting these methods into the decorator call, and this is also the reason React DnD does not ask you to implement any static methods. It just doesn't compose well.

Here's a [good discussion](https://github.com/acdlite/flummox/issues/173) on this topic.

You can use this solution:

```js
function statics(a) {
  return b => Object.assign(b, a)
}


@connectToStores
@statics({
  getStores() {
    return [EventStore]
  },
  getPropsFromStores({scheduleId}) {
    const events = EventStore.getEvents(scheduleId)
    return { events }
  }
})
@DropTarget([Draggables.VIDEO_ITEM, Draggables.TIMELINE_ITEM], dropTargetSpec, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver({ shallow: true })
}))
class Schedule extends Component {

```

This way, `statics` are attached just before `@connectToStores` consumes them, and, on the other hand, `DropTarget` receives the innermost instance and props.

Another, perhaps, a cleaner way, is to separate the [“smart” and “dumb” components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0), extracting a `ScheduleContainer` that connects to a store and renders `<Schedule {...this.props} {...this.state} />`, and only put `DropTarget` on `Schedule` itself. This is how I'd do it.

**Comment by chrishoage** [comment]
Thank you for your time to respond! After posting this I quickly realized why it wouldn't work. Hopefully this thread will help someone in the future when decorators are more common figure out why component.setState isn't setting the state on the component they imagine it should.
