### ISSUE TITLE
react-dnd clobbering other context objects?

### ISSUE THREAD

**Issue by brumm** [gaearon/react-dnd#168]
I'm not 100% clear on how contexts work, but it seems that using the `@DragDropContext(HTML5Backend)` decorator clobbers existing contexts for this component.

the flux implementation in this case is Flummox, which passes the flux instance down via context:
```
React.render(
  <FluxComponent
    flux={flux}
    render={() => <Application />} />, document.body);
```

```
@DragDropContext(HTML5Backend)
class Application extends React.Component {
  render() { console.log(this.context); }
}
Application.contextTypes = { flux: React.PropTypes.object.isRequired };
```

logs `undefined`, whereas the same code without the decorator logs `Object {flux: Flux}`

**Comment by gaearon** [comment]
This doesn't work because you're declaring `contextTypes` on the *wrapped* `Application`, not your class. This will work:

```js
@DragDropContext(HTML5Backend)
class Application extends React.Component {
  static contextTypes = { flux: React.PropTypes.object.isRequired };
  render() { console.log(this.context); }
}
```

This will work too (ES6):

```js
class Application extends React.Component {
  render() { console.log(this.context); }
}

Application.contextTypes = { flux: React.PropTypes.object.isRequired };
Application = DragDropContext(HTML5Backend)(Application);
```

**Comment by brumm** [comment]
Oh dang! I knew I was overlooking something, thank you.

**Comment by gaearon** [comment]
I agree it's not quite obvious, but there's a more general issue there of accessing the statics of the wrapped component. I wouldn't want to whitelist and copy `contextTypes` and `propTypes` over, but leave some statics out, etc.

I'm not sure if there's a great generic solution there. Personally I'd just make a [`statics` decorator](https://github.com/acdlite/flummox/issues/173#issuecomment-100552563) and never think about it, but YMMV.
