### ISSUE TITLE
It's possible to reflect actual state for item in drag?

### ISSUE THREAD

**Issue by kossnocorp** [gaearon/react-dnd#17]
Illustration of the problem (`... <div>{index+1}.</div> ...`):

![](http://i.ncrp.co/image/0f400H2L2C3O/Screen%20Recording%202014-10-28%20at%2012.23%20pm.gif)

Btw thanks for your great work :+1:

**Comment by gaearon** [comment]
This will be possible when #48 is merged (milestone: 1.0).

**Comment by gaearon** [comment]
This is available in 0.8.0 using `DragLayerMixin`.

[Live demo](http://gaearon.github.io/react-dnd/#/drag-around-custom)
[Source code](https://github.com/gaearon/react-dnd/tree/master/examples/_drag-around-custom)
