### ISSUE TITLE
canDrop does not switch while hovered over dropTarget

### ISSUE THREAD

**Issue by chrishoage** [gaearon/react-dnd#172]
I have modified [the chess example](https://github.com/chrishoage/react-dnd/blob/candropbug/examples/00%20Chessboard/Tutorial%20App/BoardSquare.js) to highlight the issue. This is a contrived example, as I am seeing the issue with out the interval, I am doing something similar to this example (checking the item data for validity in that position), except my drop target is one big target with lots of drag sources. 

But if you run this and hold the piece over an area you will not see it change. If you drag it out and in of the drop target area you will see it switch between the states every second.

**Comment by gaearon** [comment]
It definitely can't guess when you change the underlying variable. That it *does* highlight when you drag in and out is just a happy coincidence.

`canDrop` can depend on `props`. If `props` change every second, then you will see changes regardless of whether you drag or just hover the item. Change the component `props`, have `canDrop` depend on them, and it should work.

Or did I miss your point?

**Comment by chrishoage** [comment]
I think you missed my point. I have one large DropTarget area (a timeline) with DragSrouces on them (timeline items, though the fact that they are DragSrouces seems to be irrelevant), while moving an item over this DropTarget if the new calculated timeline item overlaps an existing timeline item (calculated by the Store) canDrop returns false. 

This seemingly should work, as when I log isOver from the monitor it changes while I drag around the item (on and off the drop target, also while just hovering), but canDrop when passed in though the collector only changes when isOver changes.

**Comment by chrishoage** [comment]
After more thought, perhaps I have misunderstood what "monitor" is supposed to do. What it seems like it is supposed to do from the docs is allow you to query info about the dropTarget state at any point in time. Because isOver is updated dynamically, it is easy to make the assumption that when canDrop changes it would update too. 

The way I imagine this works is canDrop is called every mouse move while dragging something and while hovered over a drop target. However this sounds like it is not he case. Have I misinterpreted how monitor.canDrop() is supposed to work?

**Comment by gaearon** [comment]
>The way I imagine this works is canDrop is called every mouse move while dragging something and while hovered over a drop target. However this sounds like it is not he case. Have I misinterpreted how monitor.canDrop() is supposed to work?

Right, this is not the case (for perf reasons). `canDrop` accepts `props`, so if `props` change, it will be recalculate. When drag starts or ends, it is recalculated too. However it won't be recalculated every time you drag a mouse, unless your props also change while you do so.

To solve your specific use case, I'd need some more code samples to understand what you're trying to accomplish. Is there any way to make `canDrop` to depend on `props` in your case?

**Comment by chrishoage** [comment]
Yes, What I have done is the following
```js
if (monitor.canDrop()) component.setState({stagedEvent})
else component.setState({stagedEvent: null})
```

in the hover spec for the drop target. It does work great, I was only a bit confused because in your docs you say those sorts of things are better handled in the render function, and setting state like that on the component is sort of an anti pattern. So this ticket was me trying to do it all in the render function. 

I am going to close this ticket, but if you have a better suggestion on how to handle this scenario I would be glad to hear it.

**Comment by gaearon** [comment]
Is it too much of me to ask you to prepare a simple example so I better understand the context? I still don't quite get what your `canDrop` should depend on.

**Comment by gaearon** [comment]
^^ lol didn't mean this to sound rude or anything :-)

**Comment by chrishoage** [comment]
No problem. The simple sample was the modification I made to the chess example. It would be pretty involved to replicate what I am trying to do. I am going to private message you with a gist of the code in question.
