### ISSUE TITLE
Is it possible to build a jsfiddle-like layout using react-dnd?

### ISSUE THREAD

**Issue by ycavatars** [gaearon/react-dnd#173]
hi, I want to implement a jsfiddle-like layout which divides the screen into 4 blocks, and I can resize each block by moving the horizontal or vertical handler. I'm not sure if I can leverage this lib or have to implement it by myself. Could you give me some hints? Really thanks.

**Comment by gaearon** [comment]
This is not the main use case for this library, but yes, it should be doable. Turn the draggable parts into drag sources, let them return the ID of the block being dragged from `beginDrag()`. Then make the container itself a drop target, and in `hover` handler, resize the child blocks according to the currently dragged boundary (`monitor.getItem()` will tell you the block ID, `monitor.getInitialClientOffset()` and `monitor.getClientOffset()` will help you figure out the movement delta).

**Comment by ycavatars** [comment]
Thanks for the hints. I will try it :)
