### ISSUE TITLE
DragDropContext breaks react-router statics

### ISSUE THREAD

**Issue by bebraw** [gaearon/react-dnd#174]
I noticed `DragDropContext` breaks react-router statics. Demo:

```javascript
var Page = React.createClass({
    mixins: [
        Router.State
    ],

    statics: {
        willTransitionTo: function(transition, params) {
            ...
        },
    },

    render: function() {
        ...
    },
});

module.exports = DragDropContext(HTML5Backend)(Page);
```

Perhaps `DragDropContext` should make sure the same statics exist on the wrapped component as well. That should fix it.

**Comment by gaearon** [comment]
It's a tricky issue and [came up before](https://github.com/gaearon/react-dnd/issues/167#issuecomment-105573862). Even if we proxy the static methods, some libraries may want the *static properties* to be proxied. But then, there are some properties that have special meaning (e.g. `contextTypes` which we shouldn't transfer). It's a mess, and I [don't think](https://github.com/acdlite/flummox/issues/173#issuecomment-100552563) it should be solved on this library's level.

You are free to do this:

```js
var Page = React.createClass({
    mixins: [
        Router.State
    ],

    render: function() {
        ...
    },
});

module.exports = DragDropContext(HTML5Backend)(Page);
module.exports.willTransitionTo = function(transition, params) {
  ...
};
```

If you use decorators, you can make a custom `statics` decorator:

```js
function statics(a) {
  return b => Object.assign(b, a)
}


@statics({
  willTransitionTo(transition, params) {
    ...
  }
})
@DragDropContext(HTML5Backend)
class Page {
    render() {
        ...
    },
});

```

**Comment by bebraw** [comment]
Yeah, that's exactly what I ended up doing. This would make a good FAQ entry as is. Thanks!

**Comment by gaearon** [comment]
I'd appreciate a doc PR :-)
