### ISSUE TITLE
Something like a dragMove event on source

### ISSUE THREAD

**Issue by smussell** [gaearon/react-dnd#176]
It may be slightly outside the scope of this lib, but I really like the api and would like to be able to use it for some more generalized dragging applications, beyond drag+drop.  In order to use it for more general use cases it would be nice to have a way to be called on every move to get the position.  One example application would be a resizable box, you have a handle in a corner of the box you can drag and change the size, I can't find a way to implement this with the current api.

**Comment by gaearon** [comment]
Seems like a common request (#173).

I don't mind seeing this, so if you implement it in DnD Core [with tests](https://github.com/gaearon/dnd-core/tree/master/src/__tests__), it's easy to add support to React DnD.

**Comment by lklesch** [comment]
+1 for an easy way to implement resizable boxes.

**Comment by vkbansal** [comment]
@gaearon Can you guide me on how to implement this?

**Comment by gaearon** [comment]
@vkbansal You can start by getting familiar with [dnd-core](https://github.com/gaearon/dnd-core) and its [tests](https://github.com/gaearon/dnd-core/tree/master/src/__tests__). Once it makes sense, you can add `drag` to drag source contract, similar to how drop targets have `hover`.

**Comment by gaearon** [comment]
Closing as I don't have time resources to implement this. As described above, this is implementable on `dnd-core` level. It is 100% covered by tests so you can learn from existing tests (e.g. for `hover()`) and add send a PR to add this.
