### ISSUE TITLE
Stopping propagation

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#18]
With nested dropzones, we need to make it possible for child dropzone to “take over”, so that parent becomes inactive when item is dragged over child.

While it's possible to do `e.stopPropagation()` inside `over` / `leave` / `enter` / `acceptDrop`, it interferes with how react-dnd works around brower hacks because events never reach `window` in this case.

I'm not sure how to handle this yet.

**Comment by gaearon** [comment]
We should look into using capture phase for global event handlers in order to prevent such problems.

**Comment by nelix** [comment]
I have been playing around with nested drag contexts... I think beginDrag and over can just stopPropagation by default so the person using the api gets the expected behaviour

**Comment by gaearon** [comment]
Superseded by #87.
