### ISSUE TITLE
Drag center issue when zoomed 

### ISSUE THREAD

**Issue by adjohu** [gaearon/react-dnd#180]
Hi,

If I zoom out and start dragging elements, they appear offset from the mouse.

**Comment by gaearon** [comment]
Yep, that's a bug. I'd appreciate somebody looking into this. Some coordinates in [OffsetHelpers](https://github.com/gaearon/react-dnd/blob/master/src/utils/OffsetHelpers.js) seem to be calculated incorrectly on zoom.

**Comment by gaearon** [comment]
Moved to https://github.com/gaearon/react-dnd-html5-backend/issues/12.

**Comment by itoed** [comment]
This bug still exists.  react-dnd/react-dnd-html5-backend#12 isn't being tracked now, right?

**Comment by marcolazzarini** [comment]
Still reproducing this bug when the browser window is zoomed. Any solutions/workaround?

**Comment by hanh090** [comment]
for me, when I config a custom preview layer (use hooks: `useDragLayer`), this problem is disappeared. Not 100% correct but the difference is very minor and acceptable

**Comment by JacobSolomonUCF** [comment]
For anyone still looking for a solution/workaround

Here's a basic implementation demonstrating the workaround that resolved this issue in my case

https://codesandbox.io/s/focused-lalande-1956b?file=/src/Box.jsx

**Comment by joeleduardo** [comment]
How that solution can works for list to be sorted?
