### ISSUE TITLE
Broken Link in Docs

### ISSUE THREAD

**Issue by prakhar1989** [gaearon/react-dnd#181]
Hi Dan,

Just a quick one - there's a broken link in [overview section](https://github.com/gaearon/react-dnd/blob/master/docs/00%20Quick%20Start/Overview.md#higher-order-components-and-es7-decorators) near the section on currying (below)

> Notice how, after specifying the DragSource parameters in the first function call, there is a second function call, where you finally pass your class. This is called currying, or partial application, and is necessary for the ES7 decorator syntax to work out of the box:

The broken link is for the ES7 decorator syntax.

Thanks for the awesome docs!

**Comment by gaearon** [comment]
Thanks, fixed now.
