### ISSUE TITLE
envify dependency missing

### ISSUE THREAD

**Issue by rpedela** [gaearon/react-dnd#182]
I get the below error when executing ```gulp``` which says cannot find dependency ```envify``` for ```invariant```. ```npm install envify``` fixed the problem. Is there something wrong with my NPM config or with this library's NPM config?

```
[11:56:33] Using gulpfile ~/source/gulpfile.js
[11:56:33] Starting 'watch'...
[11:56:33] Finished 'watch' after 24 ms
[11:56:33] Starting 'default'...
[11:56:33] Finished 'default' after 16 μs
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'envify' from '/home/rpedela/source/node_modules/react-dnd/node_modules/invariant'
    at /home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/rpedela/source/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

package.json
```js
{
  "name": "my_app",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.12"
  },
  "dependencies": {
    "async": "0.9.0",
    "aws-sdk": "2.1.32",
    "body-parser": "1.12.4",
    "compression": "1.4.4",
    "cookie-parser": "1.3.5",
    "domready": "1.0.8",
    "express": "4.12.4",
    "express-favicon": "1.0.1",
    "express-session": "1.11.2",
    "helmet": "0.9.0",
    "jade": "1.10.0",
    "jquery": "2.1.4",
    "nconf": "0.7.1",
    "pg": "4.3.0",
    "pg-format": "0.1.4",
    "react": "0.13.3",
    "react-dnd": "1.1.1",
    "react-tools": "0.13.3",
    "reflux": "0.2.7",
    "request": "2.55.0",
    "serve-favicon": "2.2.1",
    "string": "3.1.1",
    "tmp": "0.0.26",
    "underscore": "1.8.3"
  },
  "devDependencies": {
    "browserify": "10.2.1",
    "gulp": "^3.9.0",
    "gulp-react": "3.0.1",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": "1.2.0",
    "reactify": "1.1.1",
    "vinyl-source-stream": "1.1.0",
    "watchify": "3.2.1"
  }
}
```

gulpfile.js
```js
var gulp = require('gulp');
var uglify = require('gulp-uglify');
var source = require('vinyl-source-stream');
var browserify = require('browserify');
var watchify = require('watchify');
var reactify = require('reactify');
var streamify = require('gulp-streamify');

var path = {
    MINIFIED_OUT: 'build.min.js',
    OUT: 'build.js',
    DEST_BUILD: 'build/client/js',
    ENTRY_POINT: 'src/client/main.js',
};

gulp.task('watch', function () {

    var b = browserify({
        entries: [ path.ENTRY_POINT ],
        transform: [ reactify ],
        debug: true,
        cache: {},
        packageCache: {},
        fullPaths: true,
    });

    var watcher = watchify(b);

    watcher.on('update', function () {
        watcher.bundle()
            .pipe(source(path.OUT))
            .pipe(gulp.dest(path.DEST_BUILD));
        console.log('Updated');
    });

    watcher.bundle()
        .pipe(source(path.OUT))
        .pipe(gulp.dest(path.DEST_BUILD));

    return watcher;
});

gulp.task('build', function () {

    var b = browserify({
        entries: [ path.ENTRY_POINT ],
        transform: [ reactify ],
    });

    b.bundle()
        .pipe(source(path.MINIFIED_OUT))
        .pipe(streamify(uglify(path.MINIFIED_OUT)))
        .pipe(gulp.dest(path.DEST_BUILD));
});

gulp.task('production', [ 'build' ]);
gulp.task('default', [ 'watch' ]);
```

**Comment by gaearon** [comment]
Yeah.. I heard that this is the case for Browserify. I should probably add `envify` to the dependencies since `invariant` wants it.

@zertosh what's the right course of action?

**Comment by zertosh** [comment]
@gaearon You need to install `envify`. I didn't make envify an explicit dependency because it brings with it `jstransform` and `esprima`.  Both are pretty big deps that you don't want on the server. https://github.com/zertosh/invariant#browser

**Comment by zertosh** [comment]
@rpedela  FYI, since watchify@2.5.0 `fullPaths: true` isn't required anymore, so unless you're doing that on purpose, you're free to remove it.

**Comment by gaearon** [comment]
>You need to install envify. I didn't make envify an explicit dependency because it brings with it jstransform and esprima. Both are pretty big deps that you don't want on the server. https://github.com/zertosh/invariant#browser

As a library author depending on `invariant` (I'd say the major use case for `invariant`), should I put it into `dependencies` or `peerDependencies`? I'm confused because it seems weird to tell users to install `envify` because they use my drag and drop library. Pardon my ignorance, I'm not using Browserify much.

**Comment by zertosh** [comment]
@gaearon:

> should I put it into dependencies or peerDependencies?

`peerDependencies` aren't going to download anymore in npm@3, so that's not an option. Putting it in your `dependencies` should work, unless some weird deduping happens - so I wouldn't recommend this.

> I'm confused because it seems weird to tell users to install envify because they use my drag and drop library.

It totally is. The real solution is for me to include `envify` as dependency. I'll do that in the next couple of hours. I'm also going to try to switch `envify` to `acorn`, so it's not so heavy.

**Comment by zertosh** [comment]
@gaearon Actually I did it just now. invariant@2.1.0 explicitly depends on envify now.

**Comment by gaearon** [comment]
Oh, cool. Thanks for that!

**Comment by rpedela** [comment]
Thanks for fixing this so quickly!

**Comment by gaearon** [comment]
No problem!

**Comment by wzup** [comment]
Here is similar error https://github.com/rackt/react-router/issues/105

I also had the error but with `react-widget`. I solved it by installing `envify` as a `dependency` of my app. Not a `devDependency` but a  `dependency`:
```
$ npm i envify --save
```
