### ISSUE TITLE
Unable to use the dist/ReactDND.min.js

### ISSUE THREAD

**Issue by prakhar1989** [gaearon/react-dnd#183]
Hi Dan,

A component of [mine](https://github.com/prakhar1989/react-tags/) depends on this library and as a part of the build process, I release a standalone `js` file, much like the file in your `dist` folder. During dev, I simply [load all](https://github.com/prakhar1989/react-tags/blob/master/example/index.html#L17-L20) the dependancies in `script` tags. This was working fine for me until the pre-1.0.0 release.  

However, as soon as I bumped up the ReactDND.min.js in my `vendor` folder (and `node_modules`) to the latest one, the `require` statements in the browser are failing.

```
var { DragSource }  = require('react-dnd');
```
gives me a `Uncaught TypeError: Cannot read property 'DragSource' of undefined` error. In the browser console, however, I can see the `ReactDnD` global object.

Can you let me know if I'm doing something wrong? [Here's](https://github.com/prakhar1989/react-tags/blob/master/webpack.config.js) the webpack file in case that helps.

Thanks for your time!

**Comment by gaearon** [comment]
Maybe I'm doing the UMD build wrong. For now, you can use Webpack's `imports-loader` to import the global.

**Comment by prakhar1989** [comment]
Ah okay! Does this look good?

```
// in webpack.config.js
loaders: [
            { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
            {
                test: require.resolve("react-dnd"),
                loader: 'imports?this=>window'
            }
        ]
```

**Comment by gaearon** [comment]
Pardon, I meant `exports`. Something like `exports?ReactDnD`. Does that work?

**Comment by prakhar1989** [comment]
Nope. I hope I am doing this correctly (sorry, new to webpack)

```
loaders: [
            { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
            {
                test: require.resolve("react-dnd"),
                loader: 'exports?ReactDnD'
            }
        ]
```

**Comment by gaearon** [comment]
Does `exports?window.ReactDnD` work?

**Comment by prakhar1989** [comment]
Sorry Dan, I was travelling so couldn't get to this. Tried `exports?window.ReactDnD` and even that isn't working. I'm sure I'm not trying it correctly. Do you want me to try it in `imports-loader` or with `exports-loader`?

**Comment by gaearon** [comment]
Never mind. I'll take a look at what's up with the build and get back to you :-)

**Comment by prakhar1989** [comment]
Ah okay! Thanks for being patient :grinning:

**Comment by gaearon** [comment]
Just to make sure we understand each other.. Why do you need to use the minified version to build your component? Is something wrong with the version from NPM?

**Comment by gaearon** [comment]
Oh sorry, I [get it now](https://github.com/prakhar1989/react-tags/blob/master/example/index.html#L17-L20). Could your problem be to due to me changing casing in 1.0?

https://github.com/prakhar1989/react-tags/blob/master/webpack.config.js#L12 references `ReactDND` but it's `ReactDnD` now. Hence the trouble.

**Comment by prakhar1989** [comment]
Ah okay. Let me quickly try that out.

**Comment by prakhar1989** [comment]
Great! It works now! :dancer: Thanks Dan!

**Comment by prakhar1989** [comment]
One last question - Actually, I copied the idea of having a standalone `dist` from your react-dnd repo. However almost all of the other components rely exclusively on NPM. Do you think having a standalone version makes sense?

**Comment by gaearon** [comment]
For components, I don't think so. For larger libraries like React DnD or React Router, it makes sense because sometimes people want to split or cache code in production, and may not be aware of techniques like Webpack's code splitting.

**Comment by prakhar1989** [comment]
Oh sure. Thanks for the clarification.
