### ISSUE TITLE
Reuse DropTarget in one Component

### ISSUE THREAD

**Issue by benhowdle89** [gaearon/react-dnd#184]
I have a grid of 8 items. 4 on top, 4 on the bottom. I let users drag items into row 1 and row 2 with:

```
const { connectDropTarget } = this.props;

return (
    <div>
        {
            connectDropTarget(
                <div>
                    
                </div>
            )
        }

        {
            connectDropTarget(
                <div>
                    
                </div>
            )
        }

    </div>
);
```

This doesn't seem to let me drop anything into the top "dropTarget". If I comment out the bottom one, I can drop into the top one fine, which leads me believe it's the multiple uses of `connectDropTarget` causing an issue. How would you recommend proceeding? ie. let users drop into either zone, and programmatically know which "row" (dropTarget) they dropped into?

**Comment by gaearon** [comment]
Yes, you can't use the same `connectDropTarget` more than once. I think the right approach is to extract a `Cell` component with `onDrop` prop. Then `Cell` would be a drop target of its own.
