### ISSUE TITLE
Instructions on how to migrate to v1.x.x

### ISSUE THREAD

**Issue by mistadikay** [gaearon/react-dnd#187]
Hi Dan,

do you have any plans to write some kind of `v1.x.x` migration instructions for people already using React DnD `v0.x.x`? I've managed to work it out, but it was quite time consuming because I didn't really know what should I change in existing code. Thanks. Appreciate your work on this project.

**Comment by gaearon** [comment]
Hey! I'm currently busy with preparing my ReactEurope talk so I can't put more work into this project for the next month. I might write migration instructions in July if there is enough demand.

**Comment by dubert** [comment]
I would be happy to provide some assistance, @mistadikay if you wanted to work together to do it. I'm struggling upgrading my company's application, as it's quite complex and it's not playing nicely with react-router. I'm getting to the point where I think I need to strip react-dnd@0.9.8 completely out of it, and reimplement it separately, which will take so many hours :tired_face:

**Comment by mistadikay** [comment]
@dubert I don't really have time writing migrating instructions myself, plus I don't really know all aspects of React DnD architecture. As for my project — it took a day for me to migrate current application with 6 DnD-components to the new version. There are lots of similar concepts between new version and the old one, but there were some parts caused me bumping my head against the wall.

**Comment by gaearon** [comment]
I'm closing as I don't intend to work on this. (Sorry!)
If somebody's willing to take this task, I can reopen.
