### ISSUE TITLE
Consider lower-casing decorators

### ISSUE THREAD

**Issue by danielberndt** [gaearon/react-dnd#188]
I started playing around with react-dnd this week and once I finished the Overview part of the documentation getting up to speed was really easy. So big props for that! 

I noticed however that eslint's default settings causes a warning with decorators:

![screen shot 2015-06-10 at 17 29 03](https://cloud.githubusercontent.com/assets/856386/8086568/5a6259e4-0f96-11e5-9ead-aa2267ad2243.png)

I currently circumvent this by using `const {DropTarget: dropTarget} = require("react-dnd")`. But it's not ideal. 

I'm not sure wether it's something that should be changed on your side or babel-eslint's one. Decorators are extremely new and there are no established style guides regarding capitalisation yet. But maybe you have an opinion here.

**Comment by gaearon** [comment]
Personally I just don't use `new-cap`. Let's say if many people express agreement with you here, I'm willing to change the casing. But I'm not convinced yet.

**Comment by gaearon** [comment]
Not really an issue so closing, but thanks for feedback.
