### ISSUE TITLE
AMD support/issues

### ISSUE THREAD

**Issue by paulruescher** [gaearon/react-dnd#189]
Does react-dnd support AMD somehow and I'm just missing it?

I tried loading via NPM and require.js and all I get is a `"react-dnd" failed with error: ReferenceError: exports is not defined` error when trying to load up `/modules/DragSource.js`.

If I try loading the minified `/dist/ReactDnD.min.js` file I get another error.

**Comment by gaearon** [comment]
The version on NPM is in CommonJS.
The minified build should support AMD. What error do you get?

**Comment by paulruescher** [comment]
Turns out I was wrong about the error, that was part of my build process.

That being said, is there any reason why `dist` is added to the ignore in `bower.json`?

**Comment by gaearon** [comment]
Hmm. I don't really know how people use Bower this days. Should it provide CommonJS version, just the dist, or both? I probably removed it by mistake. Will happily accept a PR adding it back if that's the right thing..

**Comment by paulruescher** [comment]
I know for my purposes probably adding dist back is enough, but I don't have an answer for the community as a whole. Let me do a little digging around and see what I can come up with.

**Comment by cameronjroe** [comment]
I think people are trying to [avoid bower nowadays](http://www.reddit.com/r/webdev/comments/37bama/why_we_should_stop_using_bower_and_how_to_do_it/), because ideally we all should be using NPM..

**Comment by paulruescher** [comment]
@cameronjroe maybe, maybe not. One, that blog post is fairly recent. I'll believe it when I see some actual traction in multiple large communities. 

Two, even if this were true, the fact of that matter is that say for some reason I couldn't include React-DnD straight from NPM, but had to install via NPM/Bower through the GitHub repo. In its current state, all I'm able to install is a folder full of config files and docs. At bare minimum I'd hope to be able to have a minified dist file. Yes, I'm not getting all the module goodness, but I'm at least able to use the library with my current build process and don't have to manually include the repo (via fork or other means).

**Comment by gaearon** [comment]
>I'll believe it when I see some actual traction in multiple large communities.

NPM is certainly already widely used in front-end community. Most React libraries are only on NPM.

>Two, even if this were true, the fact of that matter is that say for some reason I couldn't include React-DnD straight from NPM, but had to install via NPM/Bower through the GitHub repo.

I'm not opposed to adding the UMD build to the NPM repo for corner cases. Many libraries do that. I'd say let's add the minified build both to bower and NPM?

**Comment by paulruescher** [comment]
I think that should hit most - if not all - corner cases. 

PR's open. Let me know if there's anything else I should think about.

**Comment by gaearon** [comment]
Fixed by #190, will be out in 1.1.3 shortly.
