### ISSUE TITLE
Element is dragged along with its border in Chrome

### ISSUE THREAD

**Issue by moroshko** [gaearon/react-dnd#193]
Steps to reproduce:

    1. git clone git@github.com:moroshko/react-chessboard.git
    2. cd react-chessboard
    3. git checkout 3d602679f5987b5bf3fea7fd2ff981dcd5553776
    4. npm install
    5. npm start
    6. Open http://localhost:3000/examples/dist/index.html in Chrome
    7. Drag a black knight
    You'll see that the black knight is dragged along with the top border.

Chrome 43.0.2357.124 (64-bit)
OS X Yosemite 10.10.3

(In Firefox, this doesn't happen.)

[Video that demonstrates the issue](https://dl.dropboxusercontent.com/u/1893981/Chrome%20border%20bug.mov)

**Comment by gaearon** [comment]
This is clearly a rendering issue and can't be solved in this library.
