### ISSUE TITLE
Is it possible to wrap concrete Components with DragDropContext rather than entire application

### ISSUE THREAD

**Issue by stremlenye** [gaearon/react-dnd#194]
Is it necessary to wrap the entire application with `DragDropContext`?
And could two or more wrapped Components safely exist on the same components nesting level?

**Comment by gaearon** [comment]
A shared `DragDropContext` is needed somewhere close to the top so components share the current drag and drop state. It subscribes to the global events once. If you have two `DragDropContext` with the same backend, they will conflict.

**Comment by gaearon** [comment]
It's just like a router of a Flux library. Since there is a shared state, it needs to be owned by some component at the top. It doesn't make sense to have two `<Router>` or two `<FluxContainer>` components.

**Comment by stremlenye** [comment]
Thanks! :+1:
