### ISSUE TITLE
How to style cannot drop?

### ISSUE THREAD

**Issue by vkbansal** [gaearon/react-dnd#195]
![hover](https://cloud.githubusercontent.com/assets/5930351/8212879/f6f7ff02-153b-11e5-9c43-0cbe8ec4ec37.gif)

As can be seen in the image, I highlight the drop-target with green color if an element is droppable. I want to highlight the target with red if it is not. How can this be achieved?

**Comment by gaearon** [comment]
[The Tutorial](http://gaearon.github.io/react-dnd/docs-tutorial.html) has an example for this.
Search the page for `canDrop`.

```js
function collect(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
    canDrop: monitor.canDrop()
  };
}

...

  render() {
    const { x, y, connectDropTarget, isOver, canDrop } = this.props;
    const black = (x + y) % 2 === 1;

    return connectDropTarget(
      <div style={{ position: 'relative' }}>
        <Square black={black}>
          {this.props.children}
        </Square>
        {isOver && !canDrop && this.renderOverlay('red')}
        {!isOver && canDrop && this.renderOverlay('yellow')}
        {isOver && canDrop && this.renderOverlay('green')}
      </div>
    );
  }

```

**Comment by vkbansal** [comment]
Do i need to define canDrop function in DropTarget spec?

**Comment by vkbansal** [comment]
OK I tried it, but without success.

My situation is that I have two dragSources of type **A** and **B**.
If my dropTarget accepts only **A**, and If I drag **B** over it, nothing happens.

**Comment by gaearon** [comment]
This is by design. If they have different types, they don't interact *at all*.

Otherwise introducing a drag source of some new unrelated type to the app will cause all existing drop targets to highlight red, while what you want is to ignore it (since it's unrelated).

If they need to interact, keep the same type, but add `canDrop()` method that performs some check on the `monitor.getItem()` properties. You can implement your own “subtypes” like

```js
// drag source
beginDrag() {
  return {
    subtype: 'somestuff',
    x: 42
  };
}

// drop target
canDrop(props, monitor) {
  return monitor.getItem().subtype === 'somestuff';
}
```

**Comment by vkbansal** [comment]
Thanks! As per your response, I had to change my implementation a bit to gett it working. :+1:
