### ISSUE TITLE
"Uncaught Error: Invariant Violation: Expected to find a valid target." when using React.Children.map()

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/react-dnd#196]
I'm having a strange issue with react-dnd. Hopefully I can explain it well enough because it only happens in a very specific circumstance.

I'm using the Sortable Simple example code as a start. However, instead of storing the Card elements in a state (ie. this.state.cards), I've converted the component to store the elements as children (ie. this.props.children). I didn't like storing cards in a state because that's not a very declarative way of defining my elements. I wanted to keep things more React-like.

My code looks something like this:

```
export default class Container extends Component {
	...

	render () {
		return (
			<div style={style}>
				{React.Children.map(this.props.children, function (child) {
					return child;
				});
			</div>
		);
	}
}
```

The sorting functionality works well, except that the first time the Card component hovers on top of another Card component I get a `Uncaught Error: Invariant Violation: Expected to find a valid target.` error in the console. Here is the stack trace:

```
invariant @ browser.js:42
canDropOnTarget @ DragDropMonitor.js:82
(anonymous function) @ HTML5.js:524
handleTopDragEnter @ HTML5.js:523
```

If I remove the `React.Children.map()` loop and use `this.props.children` directly -- the error goes away. I can't figure out why it would make any difference...

What exactly does this error mean and what could possibly be causing it?

**Comment by gaearon** [comment]
>I didn't like storing cards in a state because that's not a very declarative way of defining my elements.

I don't understand. Th examples in this repo never store the React elements. `this.state.cards` in the example is an array of JavaScript objects describing the cards (a model, if you will), not the actual `<Card>` components:

```js
    this.state = {
      cards: [{
        id: 1,
        text: 'Write a cool JS library'
      }, {
        id: 2,
        text: 'Make it generic enough'
      }, {
        id: 3,
        text: 'Write README'
      }, {
        id: 4,
        text: 'Create some examples'
      }, {
        id: 5,
        text: 'Spam in Twitter and IRC to promote it'
      }, {
        id: 6,
        text: '???'
      }, {
        id: 7,
        text: 'PROFIT'
      }]
    };
```

This is exactly the React way of dealing with state.

As for your exact problem, I'm not exactly sure how to reproduce it. Can you maybe put a reproducible case somewhere on JSBin or in a separate Github repo?

**Comment by globexdesigns** [comment]
I'm no longer able to reproduce this. No idea what caused it to begin with. Closing for now. Will re-open with an example should it ever appear again.

**Comment by cormacrelf** [comment]
For reference, if you want to make props.children draggable, avoiding this error entails:

1.  getInitialState should store an array made up of this.props.children.

    ```javascript
    // ... getInitialState
    var children = [];
    React.Children.map(this.props.children, function(child) {
        children.push(child); /* sounds like bullying to me */
    });
    return { children: children };
    ```
2.  Any modifications to the ordering should be applied to `this.state.children` as you might expect
3.  render() should render `this.state.children`, and if you want to provide dynamic properties to the children:

    ```javascript
    var children = _.map(this.state.children, function(child) {
        return React.cloneElement(child, { /*props*/ });
    });
    // ... then <div>{children}</div>
    ```

This is probably ill-advised unless you need highly customizable and non-homogeneous items in your sortable list.

**Comment by potapovDim** [comment]
Invariant Violation: Expected targetIds to be registered 
??
