### ISSUE TITLE
How to use react-dnd in the context of a unit test

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/react-dnd#197]
I'm trying to find a way to unit test my draggable component. However, I don't know how to get beyond:

```
Warning: Failed Context Types: Required context `dragDropManager` was not specified in `DropTarget(DragSource(Card))`.
```

Is there a way to test my `Card` component separately from the `Container` element which defines the DragDropContext?

Or is there some way to pass a DragDropContext to `React.addons.TestUtils.renderIntoDocument(<Card/>);`

**Comment by gaearon** [comment]
This should help you:

http://gaearon.github.io/react-dnd/docs-testing.html

**Comment by globexdesigns** [comment]
Thanks. How do you get around the issue that `ReactTestUtils.findRenderedDOMComponentWithClass` and the other ReactTestUtil search method don't work on decorated components?

I'm trying to test a button that's wrapped in a draggable decorator, but ReactTestUtils refuses to find that DOM node in the tree.

**Comment by gaearon** [comment]
`findRenderedComponentWithType` definitely worked for me (it's in that doc too).
`findRenderedComponentWithClass` searches for CSS class name, probably not what you meant?

**Comment by globexdesigns** [comment]
Hmm. My situation is something like this:

```
var stuff = ReactTestUtils.renderIntoDocument(
	<Container>
		<Card>
			<button className="mybutton"/>
		</Card>
	</Container>
);

console.log(ReactTestUtils.findRenderedDOMComponentWithClass(stuff, 'mybutton'));
=> Throws: Error: Did not find exactly one match (found: 0) for class:mybutton
```

**Comment by gaearon** [comment]
What's your `Card` like? Does it actually render `this.props.children`?

**Comment by globexdesigns** [comment]
Yes. Card is very similar to https://github.com/gaearon/react-dnd/blob/master/examples/04%20Sortable/Simple/Card.js except it renders children instead of `this.props.text`

**Comment by gaearon** [comment]
Are you sure the issue you're having is related specifically to React DnD?

**Comment by globexdesigns** [comment]
To be honest, I'm not. It could be related to ES7 decorators. I'll keep investigating.

**Comment by gaearon** [comment]
Decorators are just sugar for function calls. These are still all just normal React components.
