### ISSUE TITLE
Docs > Tutorial: Chess Board Aspect Ratio

### ISSUE THREAD

**Issue by jehoshua02** [gaearon/react-dnd#198]
FWIW ...

> It looks pretty awesome! I don't know how to constrain the Board to maintain a square aspect ratio, but this should be easy to add later.

An approach I've used successfully in many places and it's quite simple:

1. Wrap the board with an "aspect ratio" div.
2. Use height 0 and percentage (of parent width) paddingTop to enforce aspect ratio.
3. Position absolute inner div on space created by padding.

See my code: https://github.com/jehoshua02/react-dnd-experiment/commit/8d2fda10d796c04499f9e1f1328933c15aebc400

Scaling the pieces is another problem.

**Comment by jehoshua02** [comment]
![screen shot 2015-06-18 at 11 07 30 pm](https://cloud.githubusercontent.com/assets/625814/8247477/d8c33a50-160e-11e5-9dd7-aaa1b2d628cc.png)

**Comment by jehoshua02** [comment]
Something weird is going on here:

![is_over_bug](https://cloud.githubusercontent.com/assets/625814/8321693/5b0638c4-19e7-11e5-8983-f7b06d7e2a1a.gif)

`monitor.isOver()` in the `BoardSquare` Component doesn't seem to be doing what I expect it to.

**Comment by gaearon** [comment]
If you got this working, I'd appreciate you amending the tutorial with this one last touch :-)

**Comment by gaearon** [comment]
Closing, as I have no time resources to integrate this.
I'll be happy to accept a PR though.
