### ISSUE TITLE
Browser compatibility is not published

### ISSUE THREAD

**Issue by FractalizeR** [gaearon/react-dnd#199]
This is a great set of components. But what is the browser requirement to run them? Do they work on IE8?

**Comment by gaearon** [comment]
IE10+ should be supported but I'd be happy if somebody investigated and contributed browser requirements.

**Comment by Reggino** [comment]
IE8 is currently not working due to the use of ES6 class getters that can not be polyfilled...

**Comment by FractalizeR** [comment]
Can it be transpiled into ES5? By Babel for example.

**Comment by josephfinlayson** [comment]
@FractalizeR I'm using it with Babel, it can be transpiled to ES5, problem is that IE8 doesn't support the full ES5 spec

**Comment by FractalizeR** [comment]
I see. There is a related es5-shim issue btw: https://github.com/es-shims/es5-shim/issues/297

**Comment by carlosrberto** [comment]
I found a bug (#257) in IE10, but I don't know how to solve yet.

**Comment by gaearon** [comment]
This is the best we can do because we don't actually have any browser testing: https://github.com/gaearon/react-dnd-html5-backend/commit/295805cbeecb1b7544de241a9e6a5ee4dd0e3134
