### ISSUE TITLE
Docs > Tutorial: canMoveKnight knightPosition.x, knightPosition.y

### ISSUE THREAD

**Issue by jehoshua02** [gaearon/react-dnd#203]
In the `canMoveKnight` function knightPosition.x is referenced but knightPosition is an array not an object.

**Comment by jehoshua02** [comment]
Also, `canMoveKnight` can be simplified to this:

```javascript
exports.canMoveKnight = function (x, y) {
  const dx = Math.abs(x - knightPosition[0]);
  const dy = Math.abs(y - knightPosition[1]);

  return (dx === 2 && dy === 1) || (dx === 1 && dy === 2);
};
```

Nit picky, I know ...

**Comment by gaearon** [comment]
Yeah, I think I actually accepted a PR fixing this but haven't republished the site yet.
