### ISSUE TITLE
Could not find the drag and drop manager

### ISSUE THREAD

**Issue by awarberg** [gaearon/react-dnd#205]
I've created a basic DnD setup with a table and rows (MyRow) that should be draggable (for re-ordering). I'm getting this error message when rendering my top-level component (Sandbox):
>Invariant Violation: Could not find the drag and drop manager in the context of MyRow. Make sure to wrap the top-level component of your app with DragDropContext.

I've decorated Sandbox with DragDropContext for the module export and feel pretty sure I'm using the API correctly. Am I using it wrong or could there be some other problem?

[package.json]
...
"react": "^0.13.3",
"react-dnd": "^1.1.3"

[Sandbox.jsx]
```javascript
var React = require('react');
var ReactDnD = require('react-dnd');
var HTML5Backend = require('react-dnd/modules/backends/HTML5');

/**
 * Implements the drag source contract.
 */
var cardSource = {
    beginDrag: function (props) {
        return {
            text: props.customText
        };
    }
};

/**
 * Specifies the props to inject into your component.
 */
function collect(connect, monitor) {
    return {
        connectDragSource: connect.dragSource(),
        isDragging: monitor.isDragging()
    };
}

var MyRow = React.createClass({
    render: function () {
        return this.props.connectDragSource(
            <tr style={{opacity: this.props.isDragging ? 0.5 : 1}}>
                {this.props.children}
            </tr>
        );
    }
});

var MyDragRow = ReactDnD.DragSource("MyDragRow", cardSource, collect)(MyRow);

var Sandbox = React.createClass({
    render: function () {
        return (
            <table>
                <tbody>
                <MyDragRow customText="row 1">
                    <td>hello</td>
                    <td>world</td>
                </MyDragRow>
                <MyDragRow customText="row 2">
                    <td>hello</td>
                    <td>world</td>
                </MyDragRow>
                </tbody>
            </table>
        );
    }
});

module.exports = ReactDnD.DragDropContext(HTML5Backend)(Sandbox);
```

**Comment by gaearon** [comment]
Can you check if you have two copies of React in node_modules by chance? This sometimes causes that problem.

**Comment by awarberg** [comment]
I didn't find another copy of React in node_modules. I also tried removing node_modules and npm install from scratch, same error.

>PS C:\Projects\MyProject> npm list react
>...
>└── react@0.13.3

**Comment by gaearon** [comment]
Can you prepare a reproducible sample project?

**Comment by awarberg** [comment]
I've created a [sample project](https://gist.github.com/awarberg/5226efb8852ce74dd0bc) which doesn't reproduce the issue (although the React-code is the same). I suppose my build system could be causing trouble (browserify)?

**Comment by awarberg** [comment]
The problem turned out to be multiple React imports after all. We are loading React from a CDN so loading it from NPM as well (bundled via browserify) caused problems. We fixed it by loading React-DnD from a CDN as well. Thanks for your help.

**Comment by gaearon** [comment]
:+1: Thanks for getting in touch and telling what the issue was!
