### ISSUE TITLE
`monitor.isOver()` wonky with developer tools opened

### ISSUE THREAD

**Issue by jehoshua02** [gaearon/react-dnd#206]
With dev tools open:

![is_over_bug](https://cloud.githubusercontent.com/assets/625814/8321789/9929cc96-19e8-11e5-989f-c8e8876ce13b.gif)

With dev tools closed:

![is_over_works_fine_without_dev_tools](https://cloud.githubusercontent.com/assets/625814/8321790/a110c3c4-19e8-11e5-8558-06f701486535.gif)

**Comment by gaearon** [comment]
Is this React DnD problem or a Chrome bug?

**Comment by robink** [comment]
AFAIK it is a chrome bug when you set a viewport scale
