### ISSUE TITLE
Firefox doesn't respect `drop` method returning false

### ISSUE THREAD

**Issue by benhowdle89** [gaearon/react-dnd#207]
Here's my drag setup:

```
return (
	<li>
		{
			connectDragSource (
				<a href="">{name}</a>
			)
		}
	</li>
);
```

And my drop setup:

```
const itemDropTarget = {
	drop(props, monitor, component) {
		props.doSomething(monitor.getItem());
	}
};
```

Inside `doSomething`, I `return false;` if I want to stop the item from being dropped. This works fine in Chrome. However, inside the `dropTarget`, I have a `<div />` which is `contentEditable`. In Firefox, when I `return false` from my `doSomething` method, it drops the dragged text into the DIV as plain text. Not ideal.

1) Am I approaching this correctly to stop an item being dropped?
2) Is there anything to be done about Firefox?

I tried adding this to the child element inside the `dropTarget` but, as you can imagine, it prevents *anything* from being dropped. Again, not ideal.

```
cancelDrag(event) {
    event.preventDefault();
    return false;
},

render(){
    return <pre
        onDragOver={this.cancelDrag}
        onDrop={this.cancelDrag}>
    </pre>
}
```

Any advice would be appreciated, and I feel really bad for putting this as an issue as it's such a solid library! Thanks :+1:

**Comment by vkbansal** [comment]
I have come across this problem before and have reported it. see #120

The problem is that firefox does not support drag'n'drop on `<a>` and `<button>`.

**Comment by benhowdle89** [comment]
@vkbansal Hey, yeah I spotted your issue and did try and emulate the fix in my code above...is that not what I need to be doing?

**Comment by vkbansal** [comment]
I think you need to move your logic to `canDrop` instead of `drop`.

try this
```js
const itemDropTarget = {
    canDrop(props, monitor, component) {
        return props.doSomething(monitor.getItem());
    }
};
```

**Comment by gaearon** [comment]
There is no support for `return false` or similar in the library. You need to implement `canDrop`.
