### ISSUE TITLE
Unable to npm start examples [Ubuntu 14.04, npm 1.4.28]

### ISSUE THREAD

**Issue by ttrmw** [gaearon/react-dnd#209]
npm install completes successfully, but npm start throws an ENOENT when it fails to find package.json

**Comment by vkbansal** [comment]
You need to have `webpack`and `webpack-dev-server` installed globally.

Run:
```
npm install -g webpack webpack-dev-server
```

**Comment by gaearon** [comment]
That's actually bad. I'd appreciate a PR fixing all build scripts to use local Webpack and WebpakDevServer.

**Comment by ttrmw** [comment]
Thanks. I've installed these now, but npm start still throws this error.

**Comment by gaearon** [comment]
Can you paste the error you get?

**Comment by ttrmw** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 error Error: ENOENT, open '/home/thomas/src/js/react-dnd/examples/00 Chessboard/Tutorial App/package.json'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Linux 3.16.0-36-generic
8 error command "/usr/bin/node" "/usr/bin/npm" "start"
9 error cwd /home/thomas/src/js/react-dnd/examples/00 Chessboard/Tutorial App
10 error node -v v0.10.37
11 error npm -v 1.4.28
12 error path /home/thomas/src/js/react-dnd/examples/00 Chessboard/Tutorial App/package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

I'm sort of a noob to js, but I'd love to give the PR a go if you can point me in the right direction!

**Comment by gaearon** [comment]
Does running `npm start` in the root project folder help?

**Comment by ttrmw** [comment]
Ah, yeah - starts up the server fine from project root. Should it also be possible to start from within an example's directory?

**Comment by gaearon** [comment]
>Should it also be possible to start from within an example's directory?

It works for me but this might depend on the NPM version.
I'm closing since it's not a DnD issue.

**Comment by ttrmw** [comment]
Alright fair, thanks!
