### ISSUE TITLE
Is it possible to define DropTarget type via props?

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/react-dnd#212]
I have created a re-usable Sortable component using the example in react-dnd, however, I'd like to make it so that each Sortable list can only accept items in that list (ie. you should not be able to drag an item from Sortable list A into Sortable list B).

Because the "type" is defined as the first parameter in the decorator, I can't figure out how to restrict to the parent component using passed in prop. Is it possible to define the "type" in the DropTarget via that component's prop? Or is there some other way I can change that "type" based on the component that is rendering it.

```
// Something like this, where 'accepts' defines the types of drag
<Sortable accepts="A" items=[...] />
<Sortable accepts="B" items=[...] />

// Then in the component definition, I'd like to use "this.props.accepts" that come in...
@DropTarget(this.props.accepts, ..., ...)
export default class Sortable extends Component {
     ...
}
```

**Comment by vkbansal** [comment]
Yes that is possible. You need to use a function.
```js
@DropTarget((props) => { return props.accepts; }, ..., ...)
export default class Sortable extends Component {
     ...
}
```

**Comment by globexdesigns** [comment]
Thanks. That definitely works.

**Comment by globexdesigns** [comment]
@vkbansal Unfortunately, `props` doesn't seem to be enough to isolate the dragging to the owner component. I can't get anything unique from the `props` about the component.

I need something like this:

```
// Items in the first list should not be allowed to be dragged into the second list
<Sortable items=[...] />
<Sortable items=[...] />

// Is there some way I can use that limit the type? Perhaps by using the React Node ID?
@DropTarget((props, component) => { return component._rootNodeId; }, ..., ...)
export default class Sortable extends Component {
     ...
}
```
