### ISSUE TITLE
Firefox attempting erroneous requests on drop if dragSource text highlighted (all OSes)

### ISSUE THREAD

**Issue by ttrmw** [gaearon/react-dnd#219]
I've found an issue where if the text in a DragSource is highlighted prior to drag, Firefox seems to attempt to make an erroneous request:

![2015-06-29-115331_890x970_scrot](https://cloud.githubusercontent.com/assets/3099390/8407241/b05625b8-1e5c-11e5-8cfe-6868db7948a3.png)

I discovered it with [this](https://github.com/ttrmw/piper) application, see screencast below:

![piper](https://cloud.githubusercontent.com/assets/3099390/8407233/9fe468fc-1e5c-11e5-83d5-3010b42f2283.gif)

In this case, the drag source's text is highlighted, then it is dragged & dropped twice to cause the error.

It doesn't appear to be an issue with my code - I checked the examples: 

![example](https://cloud.githubusercontent.com/assets/3099390/8407235/a5cbb644-1e5c-11e5-8a69-cc2e0f34f2e8.gif)

Where the issue can be caused with a single drag & drop, and manifests slightly differently - Firefox at least is able to report on what it attempted to request! 

I first encountered this on Ubuntu 14.04 w/ Firefox 38, but have checked on Windows 7 & Mac OSX, the issue appears to be present on all OSes.

Haven't been able to reproduce in IE or Chrome on any platform.

**Comment by gaearon** [comment]
That's an interesting bug, thanks for reporting.
Sadly I'm currently unable to work on fixing it. (Might take a few weeks before I'm able to.)

[This](https://github.com/gaearon/react-dnd/blob/master/src/backends/HTML5.js) is the relevant source code file. As a temporary workaround, you can disable text selection on the draggable elements via CSS.

**Comment by ttrmw** [comment]
Thanks for the workaround, that was my plan too. 

I will take a look and see if I'd be able to work on it, thank you for the nudge in the right direction :+1:

**Comment by ttrmw** [comment]
Just wanted to let you know I am working on this!

**Comment by ryanhiebert** [comment]
@ttrmw: does the referenced patch work for you? I'm running into a similar issue.

**Comment by ttrmw** [comment]
Hey @ryanhiebert, yep the commits should fix this
