### ISSUE TITLE
DropTarget doesn't account for default props

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/react-dnd#220]
Consider the following:

```
// I was the drop target type to be driven via the `props.type` value (which is derived from the component's default props)
@DropTarget(props => { console.log(props); return props.type; }, spec, collect))
export default class Sortable extends Component {
	static defaultProps = {
		type: "Test"
	}
}
```

However, the console statement returns an empty object (`{}`). Looks like defaultProps never gets passed to the DropTarget.

**Comment by gaearon** [comment]
Yeah, it's a bit of a gotcha.. See http://gaearon.github.io/react-dnd/docs-faq.html#why-won-39-t-my-static-methods-and-properties-work-.

This will work as intended:

```js
@DropTarget(props => { console.log(props); return props.type; }, spec, collect))
export default class Sortable extends Component {
}

Sortable.defaultProps = {
  type: "Test"
}
```

Inner component's default props are just not available to the outer component provided by React DnD.
The link above explains why I don't want to build heuristics for that into the library itself.

**Comment by globexdesigns** [comment]
Thanks for the fast reply.

Unfortunately, I'm not sure this will work for my needs as I need defaultProps to call a function which generates a new unique type for each component instance.

```
@DropTarget(props => { console.log(props); return props.type; }, spec, collect))
export default class Sortable extends Component {
    static defaultProps = {
        // This should be a unique value for each Sortable instance
        type: generateUUID()
    }
}
```

However, if I move this outside of the class definition, then the UUID will not be new for each instance. It will be the same for all component.

Any ideas how to get around this issue?

**Comment by mathieumg** [comment]
Perhaps put that UUID in the state instead?

**Comment by globexdesigns** [comment]
I don't think I can access the state in the DropTarget decorator definition, ie:

```
// This only gives me access to 'props'. Not 'state'
@DropTarget(props => { console.log(props); return props.type; }, spec, collect))
```

**Comment by gaearon** [comment]
>Unfortunately, I'm not sure this will work for my needs as I need defaultProps to call a function which generates a new unique type for each component instance.

As far as I know this is a wrong way of using `defaultProps`. It's against how it's supposed to work in React. They should be static. Here is an example of how this can break with React 0.14 compilation optimizations: https://github.com/facebook/react/issues/3228.

To achieve what you want, there is no other way but to wrap your whole component into another component that generates UUID in the state or its constructor and passes it down.
