### ISSUE TITLE
Move to Redux?

### ISSUE THREAD

**Issue by JustinTulloss** [gaearon/react-dnd#222]
Are there plans to move this library from Flummox to Redux? I personally would be more willing to add Redux as a dependency if this library (which I already depend on) used it.

**Comment by gaearon** [comment]
I don't have plans at the moment, but eventually I'd do that.

**Comment by JustinTulloss** [comment]
Sounds good!

**Comment by gaearon** [comment]
Done in `react-dnd@1.1.6` / `dnd-core@1.2.0`: https://github.com/gaearon/dnd-core/pull/21.

**Comment by ouchxp** [comment]
@gaearon I suppose the documentation should be updated as well.
https://gaearon.github.io/react-dnd/docs-overview.html
The latest official document still saying it's backed by Flux.

**Comment by gaearon** [comment]
Well, technically Redux is still rather similar to Flux. But a PR is welcome.
