### ISSUE TITLE
Problems with DragLayer in IE10

### ISSUE THREAD

**Issue by michael-p** [gaearon/react-dnd#223]
Dear all,

It seems that DragLayer does not work in IE10 and below because one needs to set `pointer-events: none` on the layer which is not supported in those browsers. At least this is the implementation that the [example-app](http://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) in the documentation uses.

Is there a known work-around that makes using DragLayer on IE10 possible?

Thanks a lot!
Michael

**Comment by olavk** [comment]
There was an implementation of "Mouse backend", but it worked on the old version. https://github.com/gaearon/react-dnd/pull/131

This is still something that should be re-made with the newest version, but I could only find time for this in September maybe.

**Comment by gaearon** [comment]
Indeed, you'd need a custom backend if you want to support drag layer on an old browser.

**Comment by methyl** [comment]
@michael-p https://github.com/yahoo/react-dnd-touch-backend/pull/9 if you use TouchBackend with Mouse support, it will work OOTB on IE10 without `pointer-events: none`
