### ISSUE TITLE
Question: How callback refs are used?

### ISSUE THREAD

**Issue by azazdeaz** [gaearon/react-dnd#224]
Hi, thanks for making great tools like this!

I was studying the React DnD source to learn how to make higher-order components which are connecting to the DOM representation and here is my biggest question:
The [bindConnectorMethod.js](https://github.com/gaearon/react-dnd/blob/62971c711650a3966bb112ee2c6e2e25a15d8e67/src/bindConnectorMethod.js#L18) always clone the element with a new callback ref so [React will call](https://github.com/facebook/react/blob/ede27d2e861cbeb89021cfd31ee84ef0909829b9/src/renderers/shared/reconciler/ReactRef.js#L58) the previous one with null then the new one with the component/DOM node. Doesn't this is a performance issue?

Btw, i know you busy but if you'll have time and passion i'm sure the community would love to read posts about the inner workings of React DnD!

**Comment by gaearon** [comment]
I didn't see a performance hit from this so I never bothered to change this.
After all, attaching/detaching refs doesn't seem like huge work (unlike talking to DOM, for example).

**Comment by azazdeaz** [comment]
Okay, thanks!
