### ISSUE TITLE
Mismatch in docs-overview page

### ISSUE THREAD

**Issue by gnapse** [gaearon/react-dnd#226]
In this page there are two different places where the signature of the `collect` function differs.

First when talking about connectors ([source line 23](https://github.com/gaearon/react-dnd/blob/gh-pages/docs-overview.html#L23)) it is stated that the arguments received are `monitor` and `connect`, in that order:

```javascript
function collect(monitor, connect) {
  return {
    highlighted: monitor.canDrop(),
    hovered: monitor.isOver(),
    connectDropTarget: connect.dropTarget()
  };
}
```

Then in the example of "putting it all together" ([source line 125](https://github.com/gaearon/react-dnd/blob/gh-pages/docs-overview.html#L125)) the arguments are given in the reversed order, compared to what was stated before:

```javascript
function collect(connect, monitor) {
  return {
    // Call this function inside render()
    // to let React DnD handle the drag events:
    connectDragSource: connect.dragSource(),
    // You can ask the monitor about the current drag state:
    isDragging: monitor.isDragging()
  };
}
```

I'd fix it in a PR, but I'm not sure which one is it.

**Comment by vkbansal** [comment]
See #225

**Comment by gnapse** [comment]
Ok, this is duplicated, so I'll close it, but that PR needs to be merged in because is confusing in the docs. Thanks.
