### ISSUE TITLE
How to notify customdraglayer when isOver dropTarget

### ISSUE THREAD

**Issue by eguneys** [gaearon/react-dnd#228]
I use custom drag layer to show a custom element for drag preview. I want to change the picture when I am on some dropTarget how can I get notified of that inside custom drag layer?

**Comment by eguneys** [comment]
Also how do I know where the drag source component is on top of drag target.

**Comment by gaearon** [comment]
If you want to only use the documented API, your best bet is to fire callbacks from drop target's `componentWillReceiveProps` when its `monitor.isOver()` changes and save that state somewhere up the component tree, so your drag layer can receive it as props.

If you don't mind using the undocumented (but stable) API, each `DropTarget` component has `getHandlerId()` method on the instance. You can then use that ID to call the **undocumented** `monitor.isOverTarget(handlerId)` inside your drag layer's collecting function.

Relevant code: https://github.com/gaearon/dnd-core/blob/19b7c124ad407017778c86fa9980213c4c47762e/src/DragDropMonitor.js#L102-L126

Note that `isOverTarget(handlerId)` is currently undocumented.

**Comment by eguneys** [comment]
How can I calculate the position of the drag source component on the drop target?

**Comment by eguneys** [comment]
My use case is:

I drag an item on a drop target.

When I am on the drop target I want drag preview to get smaller.
When I drop the item, I want it to get dropped exactly to the position the "smaller drag preview" was before.

I tried passing props and firing actions using redux, but if I fire an action inside { hover } hook, the app just slows down and crashes.

It would be nice if such an example is added.
@gaearon

**Comment by gaearon** [comment]
I'm currently unable to work on adding more examples because I'm focused on Redux right now.
If you put up a project reproducing the problem somewhere on Github I might be able to take a look later.

**Comment by is** [comment]
@eguneys, you can try set the position onto the component directly, not throw action & reducer. 

       hover(props, monitor, component) {
       if (!monitor.canDrop()) {
         return;
       }
       if (!monitor.isOver({shallow: true})) {
         return;
       }

       const posIndex = calcNodeIndexY(
         React.findDOMNode(component),
         (x) => (x.nodeName == 'DIV'),
         monitor.getClientOffset().y);
       component.syncDragPosition(posIndex);
      },

In component

    syncDragPosition(index) {
      if (index != this.vars.dragPosition) {
        this.vars.dragPosition = index;
      } else {
        return;
      }

      let self = this;
      setTimeout(() => {
        if (index == self.vars.dragPosition) {
          self.setState({...self.state, dragPosition: index});
        }
      });
    }

It's not a serious solution, but it works for me.

**Comment by gaearon** [comment]
>I tried passing props and firing actions using redux, but if I fire an action inside { hover } hook, the app just slows down and crashes.

I presume this shouldn't be a problem anymore because of dnd-core rewrite to Redux.
Please let me know if this is still a problem.
