### ISSUE TITLE
Connecting two lists

### ISSUE THREAD

**Issue by kraftwer1** [gaearon/react-dnd#230]
Does anybody know if it's possible to connect two lists (and maybe has a working example for it)?
My app:

```html
<Container>
    <List>
        <Item id="1"></Item>
        <Item id="2"></Item>
    </List>
    <List>
        <Item id="3"></Item>
        <Item id="4"></Item>
    </List>
<Container>
```

Now I'd like to drag the first item of the first list to the second list.
That means, when I use ```setState()```, I'll have to remove an item from the first list and add it to the second list (to the index to where the user has dropped it). Right now, I'm getting a lot of errors when I do that (```encountered two children with the same key...```).

Note: I'm not looking for debugging my app, I'm just asking if this is even possible.

**Comment by gaearon** [comment]
Definitely possible, see https://github.com/gaearon/react-dnd/issues/227.
It has an example (slightly broken one, but I explain how to fix it in the issue).

**Comment by kraftwer1** [comment]
Thanks a lot, the example helped me to solve the issue.
