### ISSUE TITLE
React 0.14-beta peerDependency

### ISSUE THREAD

**Issue by globexdesigns** [gaearon/react-dnd#231]
Currently, I can't use react-dnd with `react 0.14.0-beta1` because npm complains about:
```
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dnd@1.1.3 wants react@>=0.13.0 <0.15.0
```

Is there any way to specify the npm peerDependency on react-dnd so that it accepts `react 0.14.0-beta1`?

**Comment by gaearon** [comment]
I released 1.1.4 that allows React 0.14 Beta 1 as a peerDep.

**Comment by steadicat** [comment]
Can you change this to `>0.14.0-beta` so that it supports all betas? 0.14 is currently at beta 3.

**Comment by gaearon** [comment]
Changed in 1.1.5.
