### ISSUE TITLE
Custom Drag Layer drag preview is offset from mouse position causes confusion on drop.

### ISSUE THREAD

**Issue by eguneys** [gaearon/react-dnd#232]
I am using a CustomDragLayer to show a custom element for drag preview. When I drop the item `monitor.getClientOffset()` is related to the mouse position. But the preview is offset from the mouse position depending on where the user clicked on drag start. This causes confusion on determining where to drop the item. If I use `monitor-getClientOffset()`. The item doesn't exactly drop the preview is showing it to.

One solution is to center the preview with the mouse. Is there a better solution to solve this?

**Comment by gaearon** [comment]
Does `getSourceClientOffset` help?

**Comment by gaearon** [comment]
There is also `getDifferenceFromInitialOffset`.
Check this out: https://github.com/gaearon/react-dnd/blob/809c825a3b70003b784f22ec8afb36815f39cd47/examples/02%20Drag%20Around/Custom%20Drag%20Layer/Container.js#L17-L28.

**Comment by eguneys** [comment]
The problem with this is, The drag sources are within drop target. In my case The drop target is different component from where the drag source is. So the initial offset doesn't matter. This is how I calculate now:

```
function calculateDropPosition(props, onPosition) {
  const rack = document.getElementsByClassName('drop-target-class')[0];
  const rackPosition = rack.getBoundingClientRect();

  const delta = {
    x: onPosition.x - rackPosition.left,
    y: onPosition.y - rackPosition.top
  };

  const position = {
    left: delta.x,
    top: delta.y
  };

  return position;
}

// Usage
const onPosition = monitor.getClientOffset();

// TODO tweak these values to better visual on drop
onPosition.x -= 30;
onPosition.y -= 30;

const dropPos = calculateDropPosition(props, onPosition);
const [left, top] = snapToRack(dropPos.left, dropPos.top);

```

I tweaked the `getClientOffset` a little bit the problem went away. I am not sure if it depends on the layout though.

**Comment by gaearon** [comment]
Yeah I guess you can't avoid tweaking here because it really depends on your app.

**Comment by gaearon** [comment]
Closing as it doesn't appear actionable.

**Comment by mdobro** [comment]
I know this is super old, but here is my solution to get things working nicely. Thanks for the above code @eguneys:

`function calculateDropPosition(onPosition) {
    const rack = document.getElementsByClassName('Canvas')[0];
    const rackPosition = rack.getBoundingClientRect();

    const delta = {
        x: onPosition.x - rackPosition.left,
        y: onPosition.y - rackPosition.top
    };

    const position = {
        x: delta.x,
        y: delta.y
    };

    return position;
}

let dropSpec = {
    drop: function (props, monitor, component) {
        let item = monitor.getItem()
        let currentPointerPosition = calculateDropPosition(monitor.getClientOffset())
        let initialPointerOffset = { x: monitor.getInitialClientOffset().x - monitor.getInitialSourceClientOffset().x, y: monitor.getInitialClientOffset().y - monitor.getInitialSourceClientOffset().y }
        let position = { x: currentPointerPosition.x - initialPointerOffset.x, y: currentPointerPosition.y - initialPointerOffset.y }
        let view = item.view
        let views = component.state.views
        let existingView = views.find(val => val.view.key === view.key)
        if (existingView) {
            existingView.position = position
        }
        else {
            //don't add duplicate view
            views.push({view, position})
        }
        component.setState({
            views
        })
    }
}`

**Comment by tuancaraballo** [comment]
In my case, I had a parent div with a css "transform" property

**Comment by blaues0cke** [comment]
To complete the documentation about this here (since I also landed here using Google having a similar issue), this is my story. In my case I also had a complete customised drag view that had nothing to do with the drag source (a table row). So the offset was always wrong except by dragging from the very left of the table row:

![example-code 2019-06-23 03_18_44](https://user-images.githubusercontent.com/5159398/59970406-e9e75c00-9565-11e9-9196-a17911c2118d.gif)

My code is based on [this example code](http://react-dnd.github.io/react-dnd/docs/api/drag-layer), so I just had to pass `monitor.getClientOffset()` into `getItemStyles()` and modify the calculation to only use this new `clientOffset`:

```diff
export default DragLayer(monitor => (
    {
+       clientOffset:  monitor.getClientOffset(),
        currentOffset: monitor.getSourceClientOffset(),
        initialOffset: monitor.getInitialSourceClientOffset(),
        isDragging:    monitor.isDragging(),
        item:          monitor.getItem(),
        itemType:      monitor.getItemType(),
    }
))(CustomDragLayer)
```

```diff
function getItemStyles (props) {
-   const { initialOffset, currentOffset } = props;
+   const { initialOffset, currentOffset, clientOffset } = props;
```

```diff
-   let { x, y }    = currentOffset;
+   let { x, y }    = clientOffset;
    const transform = `translate(${x}px, ${y}px)`;
```

So with this changes, everything  is fine:

![with-fix 2019-06-23 03_19_11](https://user-images.githubusercontent.com/5159398/59970437-7abe3780-9566-11e9-8267-e017c556b417.gif)

**Comment by tunga2cvp** [comment]
may i ask how can i center the preview since im using useDrag with DragPreviewImage and previewOptions doesn't seem to work

**Comment by oadrian2** [comment]
I've also noticed that the built-in browser preview gets offset based on zoom level and you end up with the preview not being where you think it is.

**Comment by oadrian2** [comment]
> may i ask how can i center the preview since im using useDrag with DragPreviewImage and previewOptions doesn't seem to work

I'm wondering if you could use `transform: translate(-50%, -50%)` in a wrapping div to offset the image.

**Comment by nkemcels** [comment]
Thanks for sharing @blaues0cke. Your solution saved my day

**Comment by MatthewMarkgraaff** [comment]
Thanks for sharing your solution @blaues0cke, it helped get me on the right track!
