### ISSUE TITLE
How to get drag direction?

### ISSUE THREAD

**Issue by longlho** [gaearon/react-dnd#239]
I have a question: How do I determine the drag direction? I'm trying to modify the drop target component depending on whether the source is being dragged down or up :sob: 

Thanks!

**Comment by gaearon** [comment]
You can use `monitor.getDifferenceFromInitialOffset()` inside your `hover` hook.
See the [`DropTargetMonitor` docs](http://gaearon.github.io/react-dnd/docs-drop-target-monitor.html) for more info.

Does this help?

**Comment by longlho** [comment]
Yeah I was looking at that but it's the direction relative to the source. I'm looking for mouse direction rather. So for example, if the source is dragged over the drop target but in the downward direction, I create a placeholder at the bottom. Otherwise I create the placeholder at the top of the drop target. Does that make sense :)?

LH

**Comment by gaearon** [comment]
You can either divide your drop target into several smaller drop targets (one at the top, one at the bottom) so you don't have to calculate anything, or calculate the direction manually based on how `monitor.getClientOffset()` changes over time—not really specific to React DnD.
