### ISSUE TITLE
use invariant from React

### ISSUE THREAD

**Issue by longlho** [gaearon/react-dnd#243]
Any chance we can use `invariant` from React instead of the mirror repo :sob: ? The reason I asked is because every package used in production at Yahoo needs to be whitelisted so minimizing dependencies would be awesome :cry:  Happy to put in a PR for this

**Comment by gaearon** [comment]
React folks explicitly ask not to do this. :-)

**Comment by longlho** [comment]
lol nvm gotcha :)
