### ISSUE TITLE
Trouble dragging close to bottom fixes on hot reload

### ISSUE THREAD

**Issue by eguneys** [gaearon/react-dnd#245]
I have a drag source component. mostly it works fine. But if I try to drag it from close to bottom, it doesn't drag. I have setup logs on `beginDrag` and `endDrag` they both get called one after another, so drag starts and immediately stops even though I didn't release the mouse yet.

This happens only when I try to drag the item from close to bottom. And If I change something so hot reloading happens, the problem goes away.

```
let  dragSource = {
   beginDrag(props)·{
    console.log('begin');
  },

  endDrag(props,·monitor)·{
     console.log('end');
  }
};
```
render method:
```
render() {
  return·connectDragSource(
     <div>
        <span>11</span>
     </div>
   );
}
```

**Comment by eguneys** [comment]
Probably related to this http://stackoverflow.com/questions/14203734/dragend-dragenter-and-dragleave-firing-off-immediately-when-i-drag, the `endDrag` gets called because `dragEnd` event is fired prematurely. I don't know why it only happens when I drag close to bottom and how it fixes on hot reload.

**Comment by gaearon** [comment]
Can you please create a reproducible example? I can't work on it right now, but somebody else might be able to take a peek later.

**Comment by eguneys** [comment]
the problem doesn't happen anymore probably it was a browser issue.

**Comment by zlanich** [comment]
I'm having a similar issue as well. In Chrome only, the drag simply stops immediately. Works fine in FF. Screen-caps:

Fail: http://drop.zachlanich.com/16o6o
Succeed: http://drop.zachlanich.com/1dQzN

Chrome Version: 46.0.2490.80 (64-bit)
Firefox Version: 36.0

Other Notes: 
- Using drag handle (doesn't seem to work either way)
- Other draggable components on the page work fine
- Your DnD drag handle preview works fine in Chrome for me

If I can find a way to make my WP plugin run standalone so you or someone else can play with it, I will, but let me know if you have any initial thoughts. Much appreciated. Thanks!

**Comment by gaearon** [comment]
Sorry, there is no way for me to help you without a reproducible example.
Please extract the relevant part into a standalone mini project so we can test it.

**Comment by zlanich** [comment]
Ok, I will work on getting this thing to function standalone. In the 
meantime, I found it it has something to do with the following scenario:

- On dragStart, I call my AppActions.startDrag(), which simply changes 
the "isDragInitialized" value in my appState, which my top most 
component, among others watch. I use it to put a "drag-initialized" 
className on one of the higher level components so I can style 
conditionally when I'm dragging components around (mostly just making 
the seams between columns red if there isn't any space to drop in that row.)

- In Chrome, it seems the drag starts, my className is applied, the 
styles change, but the html5 drag/preview doesn't occur. However, if I 
comment out the AppActions.startDrag(), removing any need for components 
to re-render down the chain, it seems to work fine (minus anything that 
depends on that className).

- In Firefox, this is not an issue. It works fine.

I'll get a standalone working asap.

Dan Abramov wrote:

**Comment by ariel1828** [comment]
Was there ever a solution to this? I'm having the same problem.

**Comment by rparjun** [comment]
@ariel1828 Seems like a bug in chrome.
http://stackoverflow.com/questions/14203734/dragend-dragenter-and-dragleave-firing-off-immediately-when-i-drag

**Comment by BrouzEx** [comment]
@rparjun thanks a lot! I was struggling with this for 2 days...
