### ISSUE TITLE
css hover state is triggered for drag source when dropped aside

### ISSUE THREAD

**Issue by eguneys** [gaearon/react-dnd#247]
I've reproduced this bug https://github.com/eguneys/react-dnd.

I have a css hover state for drag sources. When a drag source is dropped aside another drag source the other drag source hover is triggered.

To reproduce:
go to custom drag drop on the examples.
check `snap to grid on drop`.
drag an item aside other.

**Comment by gaearon** [comment]
This is just how browser HTML5 implementation works. Nothing we can do AFAIK to change it (other than a custom backend).
