### ISSUE TITLE
"TypeError: connectDropTarget is not a function" when running examples

### ISSUE THREAD

**Issue by SBUtltmedia** [gaearon/react-dnd#250]
Hi, we've been using the library for the past couple of months but today (after updating npm dependencies) we ran into an error: "TypeError: connectDropTarget is not a function" which we also get when running the examples in the repository (Single Target, Multiple Target, etc.) from source.

**Comment by kenfehling** [comment]
I wonder if it could be one of the library's dependencies that recently was updated that's causing the issue?

**Comment by SBUtltmedia** [comment]
Two days later and it's working again. So weird.

**Comment by gaearon** [comment]
Please let me know if you find a way to reproduce this!
