### ISSUE TITLE
Use of React.findDOMNode is incompatible with React v0.14.0-beta1

### ISSUE THREAD

**Issue by rasmusfl0e** [gaearon/react-dnd#252]
The beta deprecates React.findDOMNode in favor of ReactDOM.findDOMNode - only used one place AFAICT:

https://github.com/gaearon/react-dnd/blob/master/src/bindConnectorMethod.js#L22

This is just a heads-up in case this hasn't been caught yet :)

**Comment by gaearon** [comment]
Thanks! We can only “fix” this once 0.14 is out, but that would mean making the library 0.14+.
Better to wait for 0.14 and then a month or so.
