### ISSUE TITLE
Custom drag preview and nested components

### ISSUE THREAD

**Issue by TrustNik** [gaearon/react-dnd#253]
Hi, I am using react-dnd and trying to archive the very basic draggable functionality as in that example https://jqueryui.com/draggable/ So all I want just to drag some window on the page, without drag source being visible while dragging. 
My first try was to follow this example https://gaearon.github.io/react-dnd/examples-drag-around-naive.html But it has one issue - because of the drag preview being done by the browser it looks like the original element with opacity and I dont want that. Also because of that there is blinking on drag start and drag end. All of that is very annoying  on the dark background.
So the next try was to follow this one https://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html and to make the original window component as a drag preview. But in this case another issue occurred. Custom drag layer logic doesn't work if the preview element has DragSource or DropTarget inside of it. Here is the error that occurred:

**Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.**

I have a repro in my fork of this repo https://github.com/TrustNik/react-dnd/tree/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer
You can see the error if you will try to drag boxes here 
[http://localhost:8080/examples-drag-around-custom-drag-layer.html](http://localhost:8080/examples-drag-around-custom-drag-layer.html)
All I've done is just replaced Box component by the DraggableBox component in the BoxDragPreview. So now we have a component that has dnd functionality in the preview and the error occurs.
You may advice to split draggable components and the static ones (like in example Box and DraggableBox) and use static ones as a preview. But in my case window component has lots of nested components inside of it and some of them are draggable too, so it is very difficult to make static preview. Think of a modal window that contains lots of ui elements and some of them are draggable.

The other solution that I can see it to try to move to mouse backend. Though it is not implemented yet.

Any advises?

**Comment by gaearon** [comment]
>Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.

Ugh. That's Flux showing its head from underneath Flummox. We should just use Redux instead (#222)...   Unfortunately I won't be able to get to this any time soon. :-(

**Comment by TrustNik** [comment]
Yeah, this is happening because of the addTarget action when new target are added. In my particular case I've found a workaround. I've made an empty image as dragPreview of the window. And instead of adding some custom preview I am moving the source window in the hover method of the whole App. In this case I don't have any new components added to dom while dragging, just changing the position of the existing one. Although there was one more issue - if you are dragging the source window and this window is already a DropTarget for some element there could be issues because of the cursor being over the target all the time. I've found its better to add pointerEvents : 'none' to the window while dragging. It solves all the issues.

**Comment by gaearon** [comment]
>Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.

This shouldn't be an issue anymore because DnD Core was migrated to use Redux instead of Flummox. If it's still an issue (in a different way) please contribute a failing test case to [DnD Core](https://github.com/gaearon/dnd-core).
