### ISSUE TITLE
"draggable" attribute toggles even on meaningless re-render.

### ISSUE THREAD

**Issue by ibond** [gaearon/react-dnd#256]
I haven't yet done a performance pass on my app so I have some places where I'm effectively re-rendering large portions of my tree, but the resulting virtual DOM ends up being the same.  Despite the lack of changes, I noticed the "draggable" attribute on any DragSources gets toggled true->false->true.

I dug into it a bit, and it appears that this is happening because in "receiveComponent" React is detecting that the refs on the DragSource need updating, which causes React to detach then re-attach the refs, which calls into HTML5Backend.connectDragSource where the "draggable" attribute is explicitly set to false when detached, then true when re-attached.

React thinks the refs need updating because in ReactRef.shouldUpdateRefs it's detecting that 'nextElement.ref !== prevElement.ref' because the ref properties are two distinct lambda functions.  It looks like there are two places in React DnD that are rebuilding the ref lambda functions:

1. cloneWithRef is wrapping the ref handler to provide a seamless passthrough to an existing ref handler.
2. The 'ref' function in bindConnectorMethod is using a lambda to bind the 'nextOptions' parameter.

Just to prove this theory I made a quick hack to React DnD to just pass the original ref function through untouched and React no longer detected that the refs needed to be updated.  I'm not sure what the correct fix for this would be though, or if this is only an issue because I'm doing something wrong.

This is using React v0.13.3, DnD v1.1.4.

**Comment by gaearon** [comment]
Have you verified this is a problem for performance?

**Comment by ibond** [comment]
I haven't, and in my app it would be tough to isolate it from the numerous other performance issues that need to be addressed first.  I suspect that this won't cause much of an issue with a good 'shouldComponentUpdate' in place, though it's possible that the changed ref will cause the element to be re-rendered regardless.

It's not particularly concerning for me right now; It just struck me as being undesirable, if benign, behavior.  I'll probably take another look into it once I've worked through some of my other performance issues.

**Comment by gaearon** [comment]
I don't have intentions to fix this unless this somebody benchmarks and proves this to be a performance issue. In this case please leave a comment and I'll reopen.

**Comment by frabbit** [comment]
This is a problem for me too, because every state change causes a rerender and my draggable element  contains a css looping animation which is always restarted when a state transition occurs, even if this state transition is totally unrelated to the draggable element. It's important to note that one part of my state is the current time, so i have an interval running which updates the current time every 5 seconds.

**Comment by hoelzer-bm** [comment]
even if there is no fix, i would like to know how to work around that problem even if it's a dirty hack ;)

**Comment by frabbit** [comment]
Even if there is no intended fix, i would like to know how to work around that problem even if it's a dirty hack ;)

**Comment by frabbit** [comment]
@ibond can i take a look at your hack?

**Comment by ibond** [comment]
@frabbit Unfortunately I don't have anything specific, I haven't verified that the issue has been fixed, but I haven't noticed seeing this since I upgraded to React 0.14.7 and DnD 2.something ~3 months ago.  Not sure if it was because of the upgrade or because I made some other changes that worked around the issue.

**Comment by frabbit** [comment]
thx, i actually found the problem and it was totally unrelated to this issue, sorry!
