### ISSUE TITLE
monitor.getDifferenceFromInitialOffset() return wrong values in IE10

### ISSUE THREAD

**Issue by carlosrberto** [gaearon/react-dnd#257]
this can be seen in the example: http://gaearon.github.io/react-dnd/examples-drag-around-naive.html

**Comment by gaearon** [comment]
I'd appreciate a fix. Unfortunately I don't have access to IE10.

**Comment by gaearon** [comment]
Moved to https://github.com/gaearon/react-dnd-html5-backend/issues/10.
