### ISSUE TITLE
Problems with text input inside draggable component (Firefox)

### ISSUE THREAD

**Issue by ntdb** [gaearon/react-dnd#260]
There are problems with text inputs inside components that have the HTML5 attribute `draggable` set to `true` in Firefox (because of [this known bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1189486)). I'm working on setting `draggable` to `false` in an `onFocus` handler and setting it back to `true` in an `onBlur` handler ([as recommended here](http://stackoverflow.com/questions/21680363/prevent-drag-event-to-interfere-with-input-elements-in-firefox-using-html5-drag)), but react-dnd has no support for such a workaround and the attribute is immediately set back to `true`.

Given that there doesn't seem to be progress on this bug in FireFox, is there room for a shim in react-dnd to handle this? I'll update this issue if I come up with a good solution regardless.

**Comment by ntdb** [comment]
The root of this might be #256

**Comment by ntdb** [comment]
For now I'm working off of [a fork](http://www.github.com/ntdb/react-dnd) that allows me to manage the `draggable` attribute directly in my app.

**Comment by gaearon** [comment]
Thanks. I'm currently busy with some other projects.
If any of these PRs help you, let me know too: https://github.com/gaearon/react-dnd/pulls

**Comment by gaearon** [comment]
Please don't forget HTML5 backend is only included as a convenience.
You can publish your fixed version on NPM (it's a single file) but still use the main repo for everything else.

**Comment by gaearon** [comment]
You should be able to work around this bug by toggling a state variable in `onFocus` and `onBlur`, and changing your `render` function to *not* call `connectDragSource()` during input:

```js
render() {
  const element = <div><textarea onFocus=... /></div>;
  return this.state.editing ? element : this.props.connectDragSource(element);
}
```
