### ISSUE TITLE
What to do when no top level component exists?

### ISSUE THREAD

**Issue by arekkas** [gaearon/react-dnd#262]
Say we have the following case:

```html
<html>
/* ... */
<body>

<nav>/* Some stuff generated NOT by react, e.g. wordpress */</nav>

<div class="droppable">DROP HERE</div>

<div class="draggable">A</div>
<div class="draggable">B</div>
<div class="draggable">C</div>

<footer>/* Some stuff generated NOT by react, e.g. wordpress */</footer>

</body>
</html>
```

And something like this:

```js
var Draggable = require('components/Draggable'),
      Droppable = require('components/Droppable');

function render() {
    $('.draggable').each(function(elem) {
        React.render(
            <Draggable />,
            elem
        );
    });

    React.render(
     <Droppable />
    , $('.droppable'))
}
```

Is there any way to make this work with react dnd?

*Please note that's pseudo code but I hope you get the point.*

**Comment by gaearon** [comment]
There is no easy way unless you figure out how to put `dragDropManager` into the context with `React.render` call. There was `withContext` but I think it's deprecated an will be removed soon.

I think we should make `dragDropManager` an optional prop (in addition to context variable) for such use cases.

**Comment by gaearon** [comment]
Um, I was being silly, it's perfectly possible.

```js
var Draggable = require('components/Draggable'),
    Droppable = require('components/Droppable'),
    DragDropContext = require('react-dnd').DragDropContext,
    HTML5Backend = require('react-dnd/modules/backends/HTML5');

function render() {
    var ContextHolder = DragDropContext(HTML5)(React.createClass({
        render: function () {
            return this.props.children();
        }
    }));


    function renderWithDnDContext(element, domElement) {
        React.render(
            <ContextHolder>{function() { return element; }}</ContextHolder>,
            domElement
        );
    }

    $('.draggable').each(function(domElem) {
        renderWithDnDContext(
            <Draggable />,
            domElem
        );
    });

    renderWithDnDContext(
     <Droppable />
    , $('.droppable'))
}
```

It will be even easier in React 0.14 where you can remove the need for `ContextHolder` child to be a function and just pass an element instead.

**Comment by JacksonGariety** [comment]
@gaearon is it possible to do a sortable list using that solution? I tired your code and it wraps every component in a `DragDropContext` component, but how to swap them without React throwing an "unmounted component" error?

Do I need a top-level component in this case?

**Comment by JacksonGariety** [comment]
@gaearon I ask simply because we have a fairly big app and we're at a point where adding a top-level component would require some serious refactoring.

**Comment by gaearon** [comment]
>we're at a point where adding a top-level component would require some serious refactoring.

What kind of refactoring and why? You’d need to change one line, e.g.

```js
class Root extends Component {
}

export default Root
```

to

```js
class Root extends Component {
}

export default DragDropContext(HTML5Backend)(Root)
```

**Comment by JacksonGariety** [comment]
@gaearon well, each "draggable" comes in from the backend as a `<div>` with some data bootstrapped in via HAML. React was added later; there's no root component atm.

The only option (without changing all the Rails views) would be to manipulate the DOM structure before loading React, which is sub-optimal.

**Comment by gaearon** [comment]
I think we’d accept a PR that adds `backend` as an optional prop to `DragSource`, `DropTarget`, and `DragLayer`. It would take precedence over the backend in `context`. You have to specify at least one of them.
