### ISSUE TITLE
Tutorial: Uncaught ReferenceError: canMoveKnight is not defined

### ISSUE THREAD

**Issue by spdufeu** [gaearon/react-dnd#263]
I noticed the "Uncaught ReferenceError: canMoveKnight is not defined" error in the console when following the tutorial.

The import statement from Game.js in Board.js needs updating as well as the canMoveKnight check to the handleSquareClick method.

```javascript
import { moveKnight, canMoveKnight } from '../Game';
```

**Comment by gaearon** [comment]
PR is welcome. ;-)
