### ISSUE TITLE
Ctrl-A from an <input> inside a DragSource component broken (Chrome)

### ISSUE THREAD

**Issue by warrd** [gaearon/react-dnd#266]
Does not select the text (at least not for me).

Tested in firefox and works.

**Comment by gaearon** [comment]
Fixed by https://github.com/gaearon/react-dnd/commit/0a36033693868a7985ea2348105da4fb2cef8a00.
Duplicate of #178.

**Comment by gaearon** [comment]
The fix for this issue was released in `react-dnd@1.1.8`.
Please verify that it works.
