### ISSUE TITLE
Using TestUtils.Simulate.dragStart()

### ISSUE THREAD

**Issue by kraftwer1** [gaearon/react-dnd#269]
I'd like to write an integration test. But instead of testing single components like described in the test docs, I'd like to test my app as a whole - without accessing single React components, but DOM nodes instead.

Unfortunately, nothing moves when I use the React native commands:

```
TestUtils.Simulate.dragStart($("#list .element").get(0));
TestUtils.Simulate.drop($("#target").get(0));
```

Can anybody tell me how to achieve my goal? Is this even possible?

**Comment by kraftwer1** [comment]
For clarification, I'm looking for something like https://gist.github.com/rcorreia/2362544, which works great like that:

    $("#list .element:first").simulateDragDrop({ dropTarget: "#target" });

**Comment by bvaughn** [comment]
Disclaimer: I have not tried this myself, but have you tried `TestUtils.SimulateNative.dragStart` ? I've seen people mentioning troubles with other mouse-related events (`mouseEnter`, `mouseLeave`)

**Comment by kraftwer1** [comment]
Interesting thought, but it doesn't work with them, either...

**Comment by gaearon** [comment]
I think `TestUtils` will simulate React events, but React DnD backends work with native events. You can either use something like [simulant](https://github.com/Rich-Harris/simulant) or use TestBackend (but yes, that won't test the DOM).
