### ISSUE TITLE
connected sortable lists

### ISSUE THREAD

**Issue by roine** [gaearon/react-dnd#274]
Is it possible to build a connected sortable list with React Dnd?

[Demo](https://jqueryui.com/sortable/#connect-lists).

If it is possible is there a demo somewhere?

**Comment by vkbansal** [comment]
See #227 
http://notlouieagain.com/~amoenk/dnd/

**Comment by roine** [comment]
Awesome demo thanks @vkbansal

**Comment by maasha** [comment]
meh! Page is not responding ...
