### ISSUE TITLE
dependencies using caret instead of tilde

### ISSUE THREAD

**Issue by mistadikay** [gaearon/react-dnd#276]
I noticed that your dependencies use `^` (caret) symbol, which means that for example when you updated `dnd-core` to `1.2.0`, `react-dnd@1.1.5` will update to this version while probably not having support for it. You may probably consider using `~` (tilde) for your dependencies instead which will prevent things from breaking.

**Comment by gaearon** [comment]
>when you updated dnd-core to 1.2.0, react-dnd@1.1.5 will update to this version while probably not having support for it. 

Actually 1.1.5 should support dnd-core 1.2.0 just fine.
I only bumped react-dnd version to force the dependency to be updated.

If something broke, it's a bug in dnd-core and needs to be fixed there.
