### ISSUE TITLE
Looking for a new maintainer for React DnD!

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#282]
As you noticed I haven't been active in issues lately, and this led to some frustration and slow releases. React DnD maintenance requires that you work an app that actually uses it to catch issues and triage them. Therefore, the biggest problem for this project is that **I don't currently work on any app, and I'm very busy with other projects, so I can't reliably triage and fix issues as they are discovered.**

The core of React DnD appears pretty solid. [DnD Core is fully covered by tests.](https://github.com/gaearon/dnd-core) Most of the issues appear related to HTML5 backend and some edge cases. There has been work on creating mouse (https://github.com/gaearon/react-dnd/pull/131) and touch (https://github.com/gaearon/react-dnd/pull/240) backends, and I'm looking forward to them being published as separate NPM modules so they can be versioned and developed separately. This way their issue will also be local, and easier to fix.

**My plan for the future is to move the HTML5 backend into a project of its own too**, so that people feel more comfortable working on it in separation, and bugfixes in it don't necessitate React DnD version bumps. I believe this will encourage people to fix bugs in it by themselves, and fork it in the worst case, instead of forking the whole React DnD.

I'm looking for a person who is actively invested in keeping React DnD alive and well. **If you are interested in this project, please let me know here, and if we come to a mutual understanding I'll be happy to transition the project to you under [rackt](http://github.com/rackt) organization** to make sure it lives on after I have diverted my attention from it.

**Comment by ryanflorence** [comment]
@mzabriskie you guys using React DnD on anything yet?

**Comment by knowbody** [comment]
Let's bring it to rackt, I'm happy to help with it

**Comment by mzabriskie** [comment]
@ryanflorence I'm not sure. I know a few teams have talked about it. I will ask.

**Comment by gaearon** [comment]
An update:

I've done some work to release [React DnD 2.0](https://github.com/gaearon/react-dnd/releases/tag/v2.0.0) which addresses a few issues including the package split. [The HTML5 backend](https://github.com/gaearon/react-dnd-html5-backend) is now separate and is easier to hack on or fork in extreme cases. We've got [touch backend](https://github.com/yahoo/react-dnd-touch-backend) too now.

Overall React DnD is in pretty good shape so it should be fine without my attention for the next couple of months.

**Comment by globexdesigns** [comment]
I'm interested. We use react-dnd very heavily in our organization and want to see it kept alive and functional.

**Comment by longlho** [comment]
hi guys, any news on this?

**Comment by gaearon** [comment]
No real news—if you'd like helping triage issues and finding browser bugs, feel free to!

**Comment by gaearon** [comment]
So, there's been a few bugs and PRs so @globexdesigns you can take a look if you're up for it.

**Comment by hunterc** [comment]
@gaearon how would you feel about moving this to the @reactjs org?

Seems like it might be a good fit?

**Comment by gaearon** [comment]
Yes but I don’t want it to be stale there. There should be somebody who uses this project and is willing to take over merging fixes, etc.

**Comment by kesne** [comment]
I'll be doing my best to take care of this project and merge PRs. I won't be able to directly contribute as much as I'd like but I'm happy to help where I can!

**Comment by gaearon** [comment]
Thank you!
