### ISSUE TITLE
Tutorial dives needlessly into too many irrelevant issues

### ISSUE THREAD

**Issue by cjohansen** [gaearon/react-dnd#283]
I was looking through the tutorial, and it takes a long time to get to the heart of it: the actual dragging and dropping. There's way too much time spent delving into musings on how to build React applications, application architecture patterns, and all kinds of things not relevant to "drag stuff around". I would suggest seriously thinning it down. Start with a baseline of a very simple component, and focus the tutorial on adding drag drop functionality. This would make it a lot easier to onboard new users.

(Don't get me wrong, it's an interesting writeup on making React applications, but it is just not to-the-point enough for a library tutorial IMO).

**Comment by gaearon** [comment]
How is this a problem? The tutorial [explicitly states](http://gaearon.github.io/react-dnd/docs-tutorial.html)

>If you're new to React and know a thing or two about it, but yet have to gain some experience building components, this tutorial can also serve as an introduction to the React mode of thinking and the React workflow. **If you are a seasoned React developer and only came here for the drag and drop part, feel free to skip to the third and the final chapter of this tutorial.**

Drag and drop is often seen mysterious by developers. I think that showing how it's *an afterthought to a good component organization* is important. If you know better, just skip those parts. :wink:
