### ISSUE TITLE
Request for Example: Items that are both a Source and Target (and updating parent's state as a drop occurs)

### ISSUE THREAD

**Issue by mattgi** [gaearon/react-dnd#285]
Are there any examples where an Item is both a source and target?

Basically would like a simple example where there is a base Container in which you can drop Boxes. Once you've dropped a Box, you can then drop a Box in to that dropped Box as well.

From that, then being able to get a representation of the overall Container state.

e.g.:

```
Container : {
  boxes : [
    {
       name  : 'box1',
       boxes : [
          {
            name : 'box2'
          }
       ] 
    },
    {
      name : 'box3'
    }
  ]
}
```

This seems like something this library was built for but http://gaearon.github.io/react-dnd/examples-nesting-drop-targets.html doesn't quite let me see yet how it might work.

A concrete example is a grid layout builder where you can drag Rows on to a Container.. and then add Columns to a Row.. and then perhaps nest Rows inside Columns, etc.. so nested as far as the user wishes. Would love an updated example on it.

**Comment by vkbansal** [comment]
@mattgi I've made exactly the same thing at my work. But I'm afraid that I wont be able share the code.

**Comment by mattgi** [comment]
tease. : P

**Comment by gaearon** [comment]
Sortable example uses items that are both sources and targets (although for a different purpose).
I don't currently have plans to implement this so closing, but yeah, it should be doable.

**Comment by 3Cbwaltz** [comment]
I know this is a late comment, but I would also be interested in this. I opened a thread wanting a similar thing: #332.
