### ISSUE TITLE
How to create a DragSource without a Context?

### ISSUE THREAD

**Issue by ofersadgat** [gaearon/react-dnd#289]
I have a component which adds dynamically created pieces to a separate component. Before I can even attach the component, I get the error: "Uncaught Error: Invariant Violation: Could not find the drag and drop manager in the context of Window. Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://gaearon.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context" Is there no way to accomplish what I want?

**Comment by gaearon** [comment]
Can you please show the relevant code?

**Comment by ofersadgat** [comment]
It looks like the following:

var Container = React.createClass({
    addItem: function(item){
        var items = this.states.items.slice();
        items.push(item);
        this.setState({items:items});
    },

    render: function(){
        return <div>{this.state.items}</div>;
    }
});
module.exports = DropTarget(types, spec, collect)(Container);

var App = React.createClass({
    render: function(){
        return <Container></Container>;
    }
});
module.exports = DragDropContext(HTML5Backend)(App);

var SomeItem = Rect.createClass({
    onClick: function(){
        Dispatcher.addItemToContainer(<SomeItem data="blah"></SomeItem>);
    },

    render: function(){
        return <div onClick={this.onClick}>...contents...</div>;
    }
});
module.exports = DragSource(type, spec, collect)(SomeItem);


That is the general layout, I've left out how the dispatcher dispatches the request, but that is a common React pattern that I think you're familiar with. As you can see here, since SomeItem creates another SomeItem and passes it outward to be added, it is out of the DragDropContext and thus throws the error. This SomeItem implementation is simple, but I have multiple components which all create other random DragSources. Thoughts?

**Comment by gaearon** [comment]
>That is the general layout, I've left out how the dispatcher dispatches the request, but that is a common React pattern that I think you're familiar with

To be honest I'm a little confused. If you mean Flux architecture, I haven't seen people passing React elements as part of action payload, and this kind of imperative code contradicts the React flow.

Why not store the *data* instead and let `SomeItem` follow the normal React top-down flow? Seems like that would solve your problem since it would have the app's context too.

**Comment by ofersadgat** [comment]
I've been trying to think about how to restructure the data flow like you're describing, but I cant figure out how to do it. Think of a drawing application where you instead of just pictures, you add components. Each component can then itself add more components (possibly with subcomponents themselves). Furthermore, it would feel wrong to make the canvas try to be aware of all the components that can be drawn. Does that make sense, or have I confused you further?

**Comment by gaearon** [comment]
Yeah that makes sense. Give each component a unique string ID (e.g. `'button': Button, 'checkbox': CheckBox, 'awesome_item': AwesomeItem`). Now you can store your data as a tree without actually referencing React components: `{ type: 'button', props: { something: 42, children: { type: 'awesome_item', ... } } }`. Operate on that data.

In `<Canvas>` (or whatever root component you have), render `<Node {...this.props.node} />`. The `Node` might look like this:

```js
import Button from './Button';
import AwesomeItem from './AwesomeItem';
// ...

const COMPONENTS_BY_TYPE = {
  'button': Button,
  'awesome_item': AwesomeItem,
  // ...
};

class Node extends Component {
  render() {
    let NodeComponent = COMPONENTS_BY_TYPE[this.props.type];
    let { children = [], ...rest } = this.props.props;
    return (
      <NodeComponent {...rest}>
        {children.map((child, i) => <Node node={child} key={i} />}
      </NodeComponent>
    );
  }
}
```

This should work recursively.

**Comment by ofersadgat** [comment]
I see, you're basically wrapping React in a typed object system which can render itself..

**Comment by gaearon** [comment]
Yes, the *type* of the immediate children of any `Node` will always `Node`. However it's a good React practice to *not* call instance methods, except some rare exceptions. `Node` can provide an `instanceRef` prop in case a direct child access is required.

**Comment by ofersadgat** [comment]
will that automatically proxy instance methods or will the component have to assume that all of its children are node objects?

**Comment by gaearon** [comment]
>will the component have to assume that all of its children are node objects?

This. Another option is to avoid component recursion at all and have `Node` build a recursive `ReactElement` tree and render it at once. This may be closer to what you wanted.

**Comment by ofersadgat** [comment]
I see, ok thanks!

**Comment by ofersadgat** [comment]
But out of curiosity, if I really wanted to do it by having the container store react elements, is there any way to do that?

**Comment by gaearon** [comment]
>But out of curiosity, if I really wanted to do it by having the container store react elements, is there any way to do that?

React DnD uses context, and React elements created outside the render tree traversal won't receive React context, so no. 

In React 0.14, however, it should work due to changes in how context works.
