### ISSUE TITLE
connectDragSource complaining due to deprecation of 'findDOMNode'

### ISSUE THREAD

**Issue by kanejoe** [gaearon/react-dnd#290]
hi, I am getting the following on implementation of a basic `connectDragSource`.

`Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.`

Does `bindConnectorMethod.js` need to refer to `react-dom` instead?

**Comment by hawkrives** [comment]
Are you running under the React 0.14 RC?

**Comment by gaearon** [comment]
We'll release a 0.14-compatible version when it's stable.

**Comment by kanejoe** [comment]
yes running 0.14-rc should have clarified that.

**Comment by gregfagan** [comment]
There doesn't seem to be any harm in running the current version of React-DnD against 0.14-rc, despite the warning. Eagerly looking forward to the next versions though!

**Comment by gaearon** [comment]
>There doesn't seem to be any harm in running the current version of React-DnD against 0.14-rc, despite the warning

There isn't. React warnings are just that: warnings.

>Eagerly looking forward to the next versions though!

I'll release in a few days when I'm home.

**Comment by bmcconaghy** [comment]
0.14 is out now.  Can you please merge in the PR that fixes this?  Thanks.  Great library, BTW.

**Comment by gaearon** [comment]
>0.14 is out now. Can you please merge in the PR that fixes this? 

https://github.com/gaearon/react-dnd/pull/275#issuecomment-146453431

**Comment by gaearon** [comment]
Really, folks, it doesn't help at all to keep asking this.
I know the warning is annoying, but I'm *just* back from the vacation.
I already said I'll work on it next week. For now I'm locking this thrad.

**Comment by gaearon** [comment]
Fixed in 2.0.0.
Release notes: https://github.com/gaearon/react-dnd/releases/tag/v2.0.0
