### ISSUE TITLE
sortable list with non equal height elements

### ISSUE THREAD

**Issue by eelkeh** [gaearon/react-dnd#291]
I've noticed this behaviour in an app I'm working on, and the easiest way to replicate this behaviour is by heightening one of the sortable elements, so that one item has more height than the rest.
When dragging over this item with one of the smaller items, the items start to flicker. It seems that the stress test example breaks when the items have variable height.
I made a little recording of this here: http://gfycat.com/AcrobaticTastyAustraliansilkyterrier (recorded from: http://gaearon.github.io/react-dnd/examples-sortable-stress.html in Chrome 45.0.2454.93)
Do I need some additional code to make non equal height lists work?

**Comment by gaearon** [comment]
Yes. I think we actually have that code in `Sortable Simple` example now.
https://github.com/gaearon/react-dnd/pull/251

**Comment by eelkeh** [comment]
Ah didn't notice that, thanks!
