### ISSUE TITLE
isDragging loses state after dragging a note to another lane

### ISSUE THREAD

**Issue by bebraw** [gaearon/react-dnd#292]
1. Check out https://github.com/survivejs/webpack_react/tree/is_dragging_bug .
2. Go to **project_source/08_building_kanban/kanban_app**.
3. `npm i`
4. `npm start`
5. Open `localhost:8080`
6. Add some initial data (some lanes and notes within lanes)
7. Drag a note within a lane. It should behave pretty much like [sortable demo](https://gaearon.github.io/react-dnd/examples-sortable-simple.html). So the current note disappears while dragging it.
8. Drag the same note to other lane. You can also try dragging it back to the same. Note that it loses `isDragging` state and as a result the target note won't be hidden while dragging!

It's possible I've done something silly there but it seems a little strange `isDragging` can lose its state. I tried digging into the source but I didn't see what might cause this.

**Comment by gaearon** [comment]
Is it really a bug? The component is unmounted, so the newly created component doesn't know it's *conceptually* the same one that was dragged. To give React DnD a hint, you need to implement a custom `isDragging` function on your drag source:

```js
const noteSource = {
  beginDrag(props) {
    return {
      id: props.id
    };
  },

  isDragging(props, monitor) {
    return props.id === monitor.getItem().id;
  }
};
```

See also https://github.com/gaearon/react-dnd/issues/227#issuecomment-120673183.

**Comment by bebraw** [comment]
Got it. Thanks!

**Comment by weixing2014** [comment]
@gaearon You save my day, again!
