### ISSUE TITLE
2d and 3d canvas

### ISSUE THREAD

**Issue by gedw99** [gaearon/react-dnd#294]
Has anyone tried to apply this to 2d and 3d canvases ?

**Comment by jedwards1211** [comment]
I just did, and `monitor.isOver()` doesn't seem to be working.  I'm investigating...

**Comment by jedwards1211** [comment]
Hmmm, I think the issue was that I'm `React.cloneElement`-ing a parent of what I passed to `connectDropTarget`.  When I put `connectDropTarget` ouside of the `cloneElement`, it worked.

**Comment by jedwards1211** [comment]
In any case what I'm really doing now is making a `<div>` that contains a `<canvas>` a drop target.  Dropping over the `<canvas>` is working.

**Comment by gaearon** [comment]
Closing, as this is not directly actionable.
If you wrote something feel free to share it further in the comments.

**Comment by gedw99** [comment]
@jedwards1211 Can you put the code you used somewhere, i would like to try it and see what i can build.

I want to extend it for specific use cases.

**Comment by jedwards1211** [comment]
Well, are you looking for a way to have different DnD behavior in different regions of the canvas, like make individual things you draw within the canvas draggable or droppable?  I'm not doing anything special like that in my project, I just have a simple drop target on a `<div>` that contains a canvas.

**Comment by gedw99** [comment]
@jedwards1211 

Ok understand. Thanks for the update. I will mess around on this myself and see what i can do.
