### ISSUE TITLE
Can't find DragDropContext

### ISSUE THREAD

**Issue by carlflor** [gaearon/react-dnd#297]
The DragSource and DropTarget look for DragDropContext from their direct parent div. They don't find the context even if I make the topmost component the context

**Comment by gaearon** [comment]
This is not how context works.
Please show the full example code and I'll help you find the issue.

**Comment by carlflor** [comment]
Thank you for your reply! Sorry for not giving details to my problem. If I may, I'd like to explain what I plan to do first and see if it's possible for React-DnD to do that. (btw great work with React-DnD!)

Im making a rails app and Im just mounting separate react components in my rails view. I have a component that produces a table with images that are draggable (DragSource). I would like to drag them to a separately mounted component which produces an area (DropTarget) in my fixed footer.

Would that be possible or should I rebuild my whole view in React for the DragDropContext to work?

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-dnd/issues/262#issuecomment-141228489.

**Comment by carlflor** [comment]
Thanks for the reference, I tried doing a little different though, but no good.. (sorry noob with react)
Basically I have my `<Draggable className= "draggable">` in a `<td>` component
```
var Row = React.createClass({
  render: function(){
    return(
      <tr><td>
        <Draggable />
      </td></tr>
    );
  }
});
```
Then I have my `<Droppable className= "droppable">` in a `<div>` component, and mount it in a separate area (footer)

I can't get the classes rendered through jquery, as with the solution in the reference
```
renderWithDnDContext(
     <Droppable />
    , $('.droppable'))
```

I tried making a context component and export it as `DragDropContext(HTML5Backend)(DragContext)` but it still looks for the context if I do something like this
```
<DragContext><Draggable/></DragContext>

<DragContext><Droppable/></DragContext>
```

Here's what I'm planning to do. The neon green containers are react components

![screen](https://cloud.githubusercontent.com/assets/4861092/10373624/3eba3b50-6e21-11e5-96b3-31a41a04be1f.jpg)

**Comment by gaearon** [comment]
The point wasn't in class names, it was in wrapping every React root into the appropriate context providing component.

Your suggestion with putting Droppable into DragContext *as a child* will work, but only in React 0.14. In React 0.13 it's essential which component *created* the element—not its parent.

**Comment by carlflor** [comment]
I've just decided to convert my whole view in react. Thanks for your help! Really appreciate it :)
