### ISSUE TITLE
Discussion: why not just embed `type` within `item`?

### ISSUE THREAD

**Issue by jedwards1211** [gaearon/react-dnd#299]
Since one can use `monitor.getItem` in the the `canDrop` method of `DropTarget`s, `type` seems redundant and inflexible to me.  I haven't seen other frameworks use any kind of `type` key -- they just rely on `canDrop`.  Is it an optimization for speed?  Or to avoid having to write `canDrop` methods for everything?

**Comment by gaearon** [comment]
People won't implement `canDrop()` by default if it's optional. It's also hard to figure out *what* to write there for beginners.

If `canDrop()` stays optional and there are no types, everything will be droppable on everything in the app. This will have negative consequences: adding a new kind of entity will require you to visit all existing drop targets to change their behavior not to accept it.

Having `type` just forces you to think about it beforehand. I think it's a sane approach.

**Comment by jedwards1211** [comment]
I think you could have easily communicated to beginners that `type` is optional but that `canDrop()` is required if `type` is omitted -- then the API would provide an easy pattern for beginners without hindering expert usage, and I assume would make it easier to use host OS DnD events that aren't one of the 3 types built into the HTML5 backend.

**Comment by gaearon** [comment]
>canDrop() is required if type is omitted -- then the API would provide an easy pattern for beginners without hindering expert usage

I don't find it to be hindering expert usage. I think it's convenient to be able to implement `canDrop()` in terms of “which model is appropriate” without worrying about that an early `return true` will later start accepting invalid items.

It is also important for performance because we can completely skip items with unrelated types when updating because we *know* they can't react.

>I assume would make it easier to use host OS DnD events that aren't one of the 3 types built into the HTML5 backend.

I don't see how.

**Comment by gaearon** [comment]
If this is an issue, you can just use the same type for all items, or even create your own wrappers over `DragSource` and `DropItem` that specify it.

**Comment by jedwards1211** [comment]
Yes, I figure I may create a `USE_CAN_DROP` type like you suggest.

As far as host DnD, here's an example.  Suppose I want to make an editor component that accepts both `text/html` and `text/plain` drops.  As far as I know some DnD events might contain data for several of these types at once.   In that case, I want the word processor to use the `text/html` data instead of `text/plain` data if both are available.  Is that currently possible with React DnD?

**Comment by gaearon** [comment]
The `type` used by React DnD does not match HTML5 drag and drop `dataTransfer.types` one to one. In *some* cases (supported explicitly by HTML5 backend, such as files, images, and plain text), there is a corresponding backend-specific type (e.g. `NativeTypes.TEXT`). For unrecognized data transfer types, React DnD won't do anything.

>In that case, I want the word processor to use the text/html data instead of text/plain data if both are available. Is that currently possible with React DnD?

No, it doesn't support this scenario. React DnD is more fit for dragging components inside application than for dragging arbitrary data (e.g. plain text or HTML). By the time React DnD renders hover, it wants to *know* the exact type of the data that's being dragged, so the drop targets and drag layers know what's going on.

React DnD doesn't support the notion of “multi-type” draggable items you can find in the original HTML5 drag and drop. We don't have plans to implement this, as it's very specific to HTML5 drag and drop API, hard to abstract away in a sensible way, and you are better off doing this manually anyway.

**Comment by jedwards1211** [comment]
Yeah, that's a good point, implementing that stuff manually wouldn't really be that much work.  Being able to use a `DragLayer` with HTML5 events would be nice, but I understand if that's out of scope.
