### ISSUE TITLE
the new connect*() api requiring DOM components breaks everything...

### ISSUE THREAD

**Issue by jquense** [gaearon/react-dnd#305]
first thanks for the great lib, we appreciate all the time and work that goes into developing and maintaining it. thank you :)

Is there no good alternative to the change that requires DOM nodes for connect methods? The newest change there breaks almost every use of react-dnd in our app. Some cases are easily refactorable but most are not, since we make a lot of use of HoC's. I appreciate not wanting to rely on react-dom, but if you _need_ DOM nodes for the api to work, what is the gain in not taking a peer dep on it?

If its backend specific could the instance be stored and then let the backend extract the underlying node. Admittedly I am not very familiar with the code base, but would that be feasible? That way core could not care, while the HTML5 backend can use findDOMNode to it's hearts content

**Comment by gaearon** [comment]
Can you share some code that is hard to refactor? Is wrapping them in divs a big issue?

The problem is, `findDOMNode` really breaks encapsulation. I understand it's a breaking change but I think, future-wise, it's the right one.

From React docs:

>If you need access to the underlying DOM node for that component, you can use ReactDOM.findDOMNode as an "escape hatch" but we don't recommend it since it breaks encapsulation and in almost every case there's a clearer way to structure your code within the React model.

Then, findDOMNode won't even work with 0.14 stateless components:

https://github.com/facebook/react/issues/4936

>A component should be able to define that its internal structure is opaque and outer component shouldn't mess around with its DOM nodes. In fact, it may chose to render null, multiple DOM nodes, nested nodes, change tags, render a Custom Element.

>Therefore, React.findDOMNode(ref) in general is considered a bad idea since it breaks the encapsulation of the component.

By the way I see you were in that discussion too. :-)

The fact that I didn't need to change any of the examples to accommodate this change is what makes me feel I'm doing the right thing restricting it. I'm curious to hear about patterns that are hard to convert. HOCs can wrap their content in divs, can't they?

**Comment by jquense** [comment]
the general issue is the react-dnd is used in lower level components that we use and compose into everything like our `Listview` components, if we were to add an extra div it is going to have really unpredictable results through the entire application and break a lot of style/css assumptions and who knows what else. Ya'll can say that our code should be more resilient to that but such are the realities of css.

The reason we can't just push the `connect*()` calls further down is because in many cases they sit between an arbitrary number of other HoC components. rewriting them to be in the actual lowest component breaks all _our_ encapsulation because not instead of of simple components that you can enhance with various react-dnd stuff we need to hard code that logic into everything like mixins.

```js 
List = makeSortable(List) // which is calling connectDropTarget on List for instance
```
I mean I know you see the advantage to the HoC approach :P but react-dnd is itself very low level, not being able to leverage the same approach to deal with the more complicated cases like (sortable lists) is frustrating, and adding extra div's to the DOM is just often not feasible (and definitely so as a upgrade path on a large app).

On the point of the conversation in #4936 my arguments there still hold I think, while `findDOMNode`  _is_ an escape hatch it is a one we are going to have to use often until React can over all bases of the DOM api well, I think this particular case is illustrative of where its just straight up required, b/c dnd stuff just needs to deal with the low level thing. and yes Stateless components are a problem, but I think this is an example of exactly those use cases mentioned [here](https://github.com/facebook/react/issues/4936#issuecomment-142400065)

My one more philosophical point on this is that since the current api actually _needs_ to work with DOM nodes, its _already_ assuming the DOM, but now that's all implicit (and removes a common usecase) but it seems like all you are gaining from it is not needing to declare react-dom as a dep. Does my initial suggestion not work/make sense which is just to offload dealing with the low level details to the backend which is really the thing that needs to anyway. That way you can keep react-dnd "pure" for lib authors but still allow these cases.

thanks again for the attentive ear

**Comment by gaearon** [comment]
I don't want to depend on `react-dom` anywhere. There have been too many hours wasted by people on duplicate React issue. The best solution to this right now is for all library authors to stop depending on the stateful wannabe singleton `react-dom` and only use `react`.

There is an easy solution to your problem: *you* need to use `findDOMNode` in your HOCs like this:

```js
function hoc(WrappedComponent) {
  @DropTarget(/* ... */)
  class HOC extends Component {
    render() {
      const { connectDropTarget, ...rest } = this.props;
      return (
        <WrappedComponent
          {...rest}
          ref={instance => connectDropTarget(findDOMNode(instance))} />
      );
    }
  }

  return HOC;
}
```

I just confirmed it works and has exactly the same effect. I'll add this to the release notes.

**Comment by gaearon** [comment]
All three workarounds are now [mentioned in the release notes](https://github.com/gaearon/react-dnd/releases/tag/v2.0.0).
If you get "`Only native element nodes can now be passed to ...`" error with React DnD, check them out.

**Comment by jquense** [comment]
thanks for the workaround! I feel your pain on the duplicate React issues, we deal with them often on the react-bootstrap issue tracker. I don't quite agree that not depending on react-dom is a viable option to fix it, but I appreciate where you're coming from.

**Comment by gaearon** [comment]
>I don't quite agree that not depending on react-dom is a viable option to fix it, but I appreciate where you're coming from.

It doesn't fix the problem in React 0.14, but it will in 0.15. Multiple `react`s will work fine together as long as there is just one `react-dom`.

**Comment by jquense** [comment]
Well my original though was just let HTML5 backend use findDOMNode instead of react-dnd, since there is no way someone could be using that backend in an environment without react-dom, because you need to to render the app at all.

Which was my initial concern that react-dnd not depending on react-dom doesn't solve the issue for folks that are using react web, they will still need to figure out how to make sure there is only one copy of React. Is there any future where react-dom isn't going to have to bee a peer dep?

**Comment by gaearon** [comment]
>Well my original thought was just let HTML5 backend use findDOMNode instead of react-dnd, since there is no way someone could be using that backend in an environment without react-dom, because you need ReactDOM.render to put anything on the page.

I like that backends have zero knowledge of React right now, and I'd prefer to keep them this way.

>my Initial concern that react-dnd not depending on react-dom doesn't solve the issue for folks that are using react web. They will still need to figure out how to make sure there is only one copy of React.

I'm not sure what you mean. That's exactly my point: starting from React 0.15, having multiple copies of `react` package will no longer be an issue as long as you have only one `react-dom`.

**Comment by jquense** [comment]
>That's exactly my point: starting from React 0.15, having multiple copies of react package will no longer be an issue as long as you have only one react-dom.

right my thought was that there is no situation where every react (web) lib isn't going to depend on react-dom, there are actual use cases for it. Also react-dom is required at the top level, so what is the harm is depending on it as a peer dependency? If your lib is a react web lib then it will _always_ be in an environment with react-dom (right?). So if a user is getting an error because depending on react-dom is creating duplication issues that is a problem that they will _have_ to solve regardless of whether you depend on it or not.

I can see how the backends not knowing about react at all is an advantage, my thought was that that was coming at the expense of react-dnd needing to assume its in a DOM environment (unless react native "base" components work like DOM nodes? string `type`s and return the underlying component from a ref)

ya seem happy with the current set of tradeoffs, so I'll leave it alone lest I force you into an eternal yak shave. Especially since I have a fine workaround :) I just ultimately wanted to note that we found the DX of this change to be a notable step back, but the workaround mitigates that somewhat. There is always a tradeoff somewhere for things though. Thanks again.

**Comment by gaearon** [comment]
>right my thought was that there is no situation where every react (web) lib isn't going to depend on react-dom, there are actual use cases for it.

Sure but I'd say they're quite rare. Component libraries definitely don't need it in 95% cases because native refs *are* DOM components now, and I don't think it's a coincidence :wink: . We're just rolling with where React goes. I have a feeling `findDOMNode()` might eventually get deprecated and I'd rather do this earlier than later.

>Also react-dom is required at the top level, so what is the harm is depending on it as a peer dependency?

Consider libraries including `react-dnd` as a dependency of their own. Not depending on `react-dom` is such a relief I won't give it up easily. I don't even have to think about these scenarios anymore. :stuck_out_tongue: 

>unless react native "base" components work like DOM nodes? string types and return the underlying component from a ref

That's exactly how RN components will work after RN migrates to use React 0.14. And it's exactly how other “native” components will work, e.g. for WebGL or console renderers. Wouldn't it be cool to support React DnD there too?

**Comment by globexdesigns** [comment]
I'm having a lot of challenges with this migration as well. In my case, I have a very generic `<Sortable/>` component which accepts any children (DOM or HoCs) and makes it sortable. It works fine for DOM elements, but getting react-dnd 2.0 to work with React component has been challenging.

For some reason, the following doesn't seem to work:

```
// The idea here is to clone whatever children the component receives,
// give it a new class and make it draggable. The components are still
// being rendered, but don't seem to have any drag events applied on them
return React.cloneElement(child, {
	className: "sortable-child",
	ref: (instance) => connectDragSource(connectDropTarget(findDOMNode(instance)))
});
```

What's the best way to debug this?

**Comment by gaearon** [comment]
Please provide a minimal sample project that worked with 1.0 but broke with 2.0. It's hard to say what exactly doesn't work without a project to check.

**Comment by bmathews** [comment]
@globexdesigns 

Chaining the calls didn't work for me, but calling them sequentially did:

```javascript
ref={(instance) =>
  this.props.connectDropTarget(findDOMNode(instance))
  this.props.connectDragSource(findDOMNode(instance))
} 
```

**Comment by globexdesigns** [comment]
@bmathews That worked. Thanks so much for posting!
