### ISSUE TITLE
(Redux) Reducer example for a drop handler

### ISSUE THREAD

**Issue by carlflor** [gaearon/react-dnd#306]
I was thinking of implementing redux for handling my drop events.. would you be able to give a sample code for this?
I previously made a `getInitialState(something)` in my parent component,
then I moved it to a `const initialState = {something}` in my reducers.js. 
I'm not sure how to go about handling the action properly though.

(from my parent component, which contains the drop targets)
```
handleDrop(index, item) {
  this.setState( update(this.state, {
    boxes: {
      [index] : { key : { $set : item }
    }
  }));
}
```

to a reducer such as this:

```
case DID_DROP:
  return ?
```

I'm trying to base it here.. but Im having a hard time understanding ES6/ES7
from: https://rackt.github.io/redux/docs/basics/Reducers.html
```
case COMPLETE_TODO:
    return [
      ...state.slice(0, action.index),
      Object.assign({}, state[action.index], {
        completed: true
      }),
      ...state.slice(action.index + 1)
    ];
```

**Comment by gaearon** [comment]
Hi, please ask this on StackOverflow, as it's not really an issue.

**Comment by carlflor** [comment]
alright! sorry about that!
