### ISSUE TITLE
Window events preventing event bubbling, issue with file dropping

### ISSUE THREAD

**Issue by jacobclarke92** [gaearon/react-dnd#308]
I've been trying to implement a file drop upload component in my site and I couldn't work out why dragover / drop events weren't firing so I tried removing the dnd events in chrome inspector and it worked.

Any words of advice for dealing with this?

**Comment by gaearon** [comment]
If you use React DnD, it will catch these events because it lets you handle file uploads too.
It's better to discuss this behavior in [the HTML5 backend repo](https://github.com/gaearon/react-dnd-html5-backend) because that's where it comes from.
