### ISSUE TITLE
Accessing DropTarget in DragLayer

### ISSUE THREAD

**Issue by methyl** [gaearon/react-dnd#312]
I want to change how DragLayer appears for different drop targets. 

Right now it doesn't seem to be possible according to docs - DragLayer monitor have no access to such data. Is there any other way to do it?

EDIT: 
I figured out something ~~nasty~~ not that nasty, just to get an idea if it's possible:
```coffee
diff = monitor.getDifferenceFromInitialOffset()
(diff.x > 0 || diff.y > 0) && monitor.getTargetIds().length == 0
```

Looking at the code I think DragSourceMonitor, DropTargetMonitor and DragLayerMonitor are exactly the same monitor instance. Why does it differ in documentation then? Is it outdated?

**Comment by gaearon** [comment]
>Right now it doesn't seem to be possible according to docs - DragLayer monitor have no access to such data. Is there any other way to do it?

To change its appearance in response to different *sources* (i.e. different items being dragged) you can use `monitor.getItemType()` and `monitor.getItem()`. However responding to *targets* (hovered ones?) outside the targets themselves is not something we plan to support—in this case you'd need to fire Flux actions (or equivalent—pass callbacks to React components and change the state) to reflect different states.

>Looking at the code I think DragSourceMonitor, DropTargetMonitor and DragLayerMonitor are exactly the same monitor instance. Why does it differ in documentation then? Is it outdated?

There is a “lower level” monitor from [DnD Core](https://github.com/gaearon/dnd-core) that we expose directly for the drag layer. For sources and targets, we hide it behind [`createSourceMonitor`](https://github.com/gaearon/react-dnd/blob/master/src/createSourceMonitor.js) and [`createTargetMonitor`](https://github.com/gaearon/react-dnd/blob/master/src/createTargetMonitor.js) which are aware of the specific source or target ID, and add some checks.

So no, they're not exactly the same. The fact that the “lower level” monitor is from DnD Core and others build on top of it is an implementation detail, so we don't acknowledge this in the docs—it shouldn't matter for the end user.

**Comment by methyl** [comment]
@gaearon so just one more question. Can I rely on monitor.getTargetIds() or do I have to find a better solution?

**Comment by gaearon** [comment]
@methyl 

Yes, you can rely on it being there (if it gets the job done).
