### ISSUE TITLE
Strange Hover Behavior after Drop

### ISSUE THREAD

**Issue by OAGr** [gaearon/react-dnd#314]
For some reason, when I drop a card, the browser often thinks that a separate cell (typically a lower cell) is in the hover state.  This has slightly different behaviors in different browsers. 

Chrome:
http://g.recordit.co/eIuIgqiZCf.gif
In Chrome, the hover state lasts appears below the space I dropped the card and lasts until I mouse over and off of the element. 

Firefox:
http://g.recordit.co/XlN1ussWrq.gif
In Firefox, the hover state lasts appears in the previous space I picked up the card, and lasts until I mouse over and off of the element. 

Relevant code is in the 'grid' folder here.  https://github.com/getguesstimate/guesstimate-app/tree/master/src/components/lib/grid.

Right now it would be difficult for someone else to debug it, but I'm just generally curious if other people have experienced this or have any clue what may be causing it.  I'm quite stumped.

**Comment by OAGr** [comment]
I've confirmed the issue with the chess example.  This is what happens when there is a hover state for the squares: 

![](http://g.recordit.co/hkQkGEwnQ4.gif)


Code diff here: https://github.com/gaearon/react-dnd/compare/master...OAGr:master

**Comment by nelix** [comment]
That is really odd, I can only speculate about why that might be happening. The only thing I can think of is to add a note to the FAQ?

**Comment by OAGr** [comment]
If it helps at all, I spent some time trying to figure out how it decides to place the hover positions.  It seems like when you drag it to the bottom of a cell, it is more likely to think the cell below it is hovered, and if you drag it to the left side of a cell, it is more likely to think that side is hovered.  
![](http://g.recordit.co/z29yKMz7Cr.gif)

**Comment by OAGr** [comment]
On further inspection, it seems like this is a Webkit bug. Issue described here: https://code.google.com/p/chromium/issues/detail?id=410328

There are a few hacky ways of dealing with it.  One is to replace the css behavior with js, obviously.

**Comment by gaearon** [comment]
Yeah, unfortunately there is nothing we can do here.
Browsers. ¯\_(ツ)_/¯
