### ISSUE TITLE
DragLayer has an odd name

### ISSUE THREAD

**Issue by nelix** [gaearon/react-dnd#315]
I am using DragLayer to emit events from some ui components (because the drag source does not have a good lifecycle place to attach such events).

I figure something like connectDragMonitor would make more sense?

Its not a big deal, its just that its not really a layer, its just often used to create layers.

**Comment by gaearon** [comment]
Can you describe the use case in more detail?
I'm curious to hear how people use it.

**Comment by gaearon** [comment]
I'll close because I'm not sure I understand the intent, and layer is indeed how people use it. Don't think it's worth a breaking change.
