### ISSUE TITLE
connect.dragSource() can't be called on component - workarounds?

### ISSUE THREAD

**Issue by thedufer** [gaearon/react-dnd#316]
My heirarchy looks like:

```
<ContainerComponent>
  <ol>
    <ItemComponent>
      <li>...</li>
    </ItemComponent>
    <ItemComponent>
      <li>...</li>
    </ItemComponent>
  </ol>
</ContainerComponent>
```

I want to wrap `ItemComponent` as such in places where they should be draggable:

```
<DraggableItemComponent>
  <ItemComponent>...</ItemComponent>
</DraggableItemComponent>
```

The problem is that in `DraggableItemComponent`'s `render`, I want to call `connect.dragSource` on the `ItemComponent`, which causes an error.  I can't wrap in a dummy element, because the `li`s have percent widths.  And I can't make `ItemComponent`s draggable instead of wrapping them, because most `ItemComponent`s are not draggable, so it doesn't make sense for it to know about that behavior.

I'm currently working around this by injecting a prop into `ItemComponent` that is expected to be called on it's contents immediately before returning from `render`, but this feels hacky.  Is there a better way to go about this?

**Comment by gaearon** [comment]
As described in [2.0 release notes](https://github.com/gaearon/react-dnd/releases/tag/v2.0.0), you can put a ref yourself and use `findDOMNode`.

<img width="900" alt="screen shot 2015-10-29 at 23 22 08" src="https://cloud.githubusercontent.com/assets/810438/10831008/fced59a4-7e93-11e5-84e7-b484cc1c016c.png">
