### ISSUE TITLE
How do I connect React DnD with Redux at the application level

### ISSUE THREAD

**Issue by kevinold** [gaearon/react-dnd#317]
I'm trying to get DnD connected with Redux at the top level as the docs say and this throws a syntax error:

```
export default DragDropContext(HTML5Backend)connect(connectSelectors)(App);
```

How should I do this?

**Comment by kevinold** [comment]
Placing the DragDropContext down the component tree seems to work, but is this a good idea?

```
export default DragDropContext(HTML5Backend)(WrapperComponent);
```

**Comment by kevinold** [comment]
Just saw this tweet (in the last hour ironically) of this implementation that connects ReactDnD to Redux

https://github.com/gcedo/react-solitaire/blob/6435b1c3ef2aa683f28617b8b6800ac3f10b44f7/src/components/controller/Game.jsx#L12-L13

**Comment by kevinold** [comment]
Working ES6 syntax:

```
export default DragDropContext(HTML5Backend)(connect(connectSelectors)(App));
```

**Comment by gaearon** [comment]
Or you can 

```
import { compose } from 'redux';

export default compose(
  DragDropContext(HTML5Backend),
  connect(connectSelectors)
)(App);
```
