### ISSUE TITLE
dragSourceFor should image capture the source, not the draghandle

### ISSUE THREAD

**Issue by Georgette** [gaearon/react-dnd#32]
If I attach a drag handle to an element, that is a drag source for its parent, it would be nice that when onDrag is invoked, that it clones the image of the parent...and not just the drag handle.

**Comment by gaearon** [comment]
I think you can do that by explicitly specifying another element else as `dragPreview` in `beginDrag` return value. The only limitation is that DOM element has to be visible at the moment.

**Comment by Georgette** [comment]
Amazingly fast response that saved me some serious hackery and time otherwise. This worked for me:
dragPreview: this.getDOMNode()

Thanks!!!

**Comment by gaearon** [comment]
No problem :-)

You can also pass an `Image` (the one you'd create with `new Image()`) as `dragPreview` if you want more freedom, and there is `ImagePreloaderMixin` to handle its loading. (Browsers often ignore images that have not been loaded.)
