### ISSUE TITLE
Sortable cancel on drop outside - cursor indicator not disabled (X) outside drop zone

### ISSUE THREAD

**Issue by cauburtin** [gaearon/react-dnd#320]
http://recordit.co/4xFfdIUkb4

http://gaearon.github.io/react-dnd/examples-sortable-cancel-on-drop-outside.html has this little issue on Chrome46, the indicator just below the mouse cursor shows I can drop the element while I was completely out of the drop zone

**Comment by gaearon** [comment]
Please can you copy this issue to https://github.com/gaearon/react-dnd-html5-backend?
It is the correct repo to report this bug.
Thank you!

**Comment by cauburtin** [comment]
https://github.com/gaearon/react-dnd-html5-backend/issues/5
