### ISSUE TITLE
Can't scroll list while dragging item

### ISSUE THREAD

**Issue by bgnorlov** [gaearon/react-dnd#324]
I have "overflow:auto" property on ul-list with long set of items. I tried to scroll list after I pressing mouse button to drag item but I can't! In this example http://gaearon.github.io/react-dnd/examples-sortable-simple.html just set "overflow: auto" property and fixed height (for example 200px) on list container's div  and you can reproduce the bug.

**Comment by gaearon** [comment]
This is not a bug, this is how [HTML5 drag and drop](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop) is implemented in (some) browsers.
If you're using [react-dnd-html5-backend](https://github.com/gaearon/react-dnd-html5-backend), that's what powers it.

The solution is to make the container list a drop target too, and scroll the list when the container drop target receives `hover` in the top or bottom area. When it's hovering over top area, begin scrolling to the top, with the speed depending on how close the cursor is to the top edge. Similarly, when hovering over the bottom area, begin scrolling to the end—the lower the cursor, the faster the speed. You can take card dragging behavior in Trello as an inspiration.

If you implement this, feel free to contribute it back to the example.

**Comment by iDVB** [comment]
I'm looking to do the same thing as even with the above suggestion, having a bit of trouble. 
For instance... `hover` seems to only fire when you "move" where as this type of functionality scrolls even when not moving and is only dependent on how close you are to the bottom/top of the page.

Also found this.... https://gist.github.com/gaearon/150fa1bed09c92abdb46 ... but it appears to be outdated?

**Comment by gaearon** [comment]
Yes, it's very outdated, but it shows the approach. Start animation loop on enter, stop it on leave, and inside the animation tick, consider to scroll if condition matches.

**Comment by nickclaw** [comment]
Posting for other people who had this issue. I've built this solution to auto scroll container that works smoothly in every browser I've tried. https://github.com/azuqua/react-dnd-scrollzone

**Comment by ruler47** [comment]
@nickclaw can you give example?

**Comment by nickclaw** [comment]
I'll add a demo tonight if it helps. But it's really as easy as the example on the README, just make sure you set the overflow values to allow the container to scroll.

**Comment by erkishorjangir** [comment]
@nickclaw  Please provide a working example. I know it's simple but I don't why it's not working for me. If working example there then I can cross check it.

**Comment by ctaloc** [comment]
Hey @erkishorjangir, did you find a way to use scrolling with react-dnd?

**Comment by ctaloc** [comment]
For future reference, react-dnd-scrollzone works also on Safari and Firefox. You can see this closed ticket: https://github.com/azuqua/react-dnd-scrollzone/issues/11

**Comment by David-OConnor** [comment]
Does anyone know why Jquery UI isn't bitten by this issue? I'm considering hacking it into my React app because being able to scroll around while dragging is that important for my use.

**Comment by David-OConnor** [comment]
I've written a module to work around this; auto-scroll divs at the top and bottom that are hidden unless you drag something. Unfortunately, I'm unable to get the npm version to import properly; the standalone index.js file in the repo works though. This is different from react-dnd-scrollzone, in that it uses the full window with its normal scroll bar, instead of making a sub-window with its own scrollbars.

https://github.com/David-OConnor/dnd-scroll

**Comment by Tsourdox** [comment]
I did my own implementation of this, just added the List component as a DropTarget, then on hover checking the position of the mouse and scroll the element accordingly.

As @iDVB mentionen above, when holding the element still the hover event for each list item isn't triggered. How did you guys solve that issue? (not looking for a separate package to install)

**Comment by shariquekhan1997** [comment]
When I drag my card from one lane to the last lane the scroll-x doesn't get scroll and it's like my viewport is at a fixed width.

**Comment by NagaiKoki** [comment]
I think this works for me.

### hooks for long tap
```ts
export type TapTimeline = 'pending' | 'start' | 'tapping' | 'end';

export const useLongPressImage = () => {
  const [tapTimeline, setTapTimeline] = useState<TapTimeline>('pending');

  useEffect(() => {
    let timerId: NodeJS.Timeout | undefined;
    if (tapTimeline === 'start') {
      timerId = setTimeout(() => setTapTimeline('tapping'), 200);
    }
    return () => {
      clearTimeout(timerId as NodeJS.Timeout);
    };
  }, [tapTimeline]);

  return {
    tapTimeline,
    ref: tapTimeline === 'tapping',
    onTapStart: () => setTapTimeline('start'),
    onTapEnd: () => setTapTimeline('end'),
  };
};
```

### useDrag(React-DnD API)

```ts
export const useDragAndDrop = (tapTimeline: TapTimeline) =>  {
  // ...
  const [{ isDragging }, drag, preview] = useDrag({
    item,
    type,
    canDrag: timeline === 'tapping',
    collect: (monitor) => ({
      isDragging: tapTimeline === 'tapping' ? monitor.isDragging() : false,
    }),
  });
  return {
    dragRef,
    dropRef,
    drag,
    drop,
    preview,
    isDragging,
  };
}
```

### Drag Item Component
```tsx
const Component = () => {
  const { tapTimeline, onTapStart, onTapEnd } = useLongPressImage();
  const { dragRef, dropRef, drag, drop, preview, isDragging } = useDragAndDrop(tapTimeline)
  
  return (
  // ...
   <div
       ref={dragRef}
       onTouchStart={onTapStart}
       onTouchEnd={onTapEnd}
     >
  // ...
  )
}
```

**Comment by quantran020173** [comment]
React-dnd-scrollzone is not working with 4+. Using react-dnd-scrolling is working for me https://github.com/TechStark/react-dnd-scrolling

**Comment by Yohanson555** [comment]
> React-dnd-scrollzone is not working with 4+. Using react-dnd-scrolling is working for me https://github.com/TechStark/react-dnd-scrolling

It works! Thanks!
