### ISSUE TITLE
Customize the cursor during drag

### ISSUE THREAD

**Issue by dshorowitz** [gaearon/react-dnd#325]
Fantastic library! Thanks for all your hard work in putting it together. I have a quick question: is it possible to customize the cursor such that during a drag operation, the cursor is **always** set to the same thing (specifically I want to set it to the *dragging* icon)?

In other words, regardless of whether you are over a drop zone or not, the cursor remains the same. This is similar to how Trello has the cursor while dragging a note, for example.

Thanks in advance!

**Comment by gaearon** [comment]
You can probably set a `cursor` style on the whole body (or application root `div`) while `isDragging` is `true`. You can use `DragLayer` to listen to `isDragging` changes.

**Comment by dshorowitz** [comment]
Thanks, I wish that worked! Unfortunately, the cursor style is overridden by something (I'm on Chrome), even when setting the cursor style to document.body and marking it as "!important". Any other ideas?

**Comment by gaearon** [comment]
Maybe it's just how HTML5 drag and drop API works. In this case the only solution is to create a custom backend that uses mouse events instead of HTML5 drag and drop events.

**Comment by dshorowitz** [comment]
I was hoping you wouldn't say that :) Thanks!

**Comment by gazpachu** [comment]
I've just found out about this issue. Unfortunately, it seems not posible to change the icon while dragging :(

**Comment by alexeymolchan** [comment]
Anyone managed to resolve this?

**Comment by augbog** [comment]
Also went and looked into this. Yes it seems that this is sadly a browser limitation in that the API for `DataTransfer.effectAllowed` only supports a handful of options:

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed

So the only way to get around this is, as @gaearon mentioned, which is to use a different custom backend :/ This might be something worth including in the `DragLayer` documentation as that might not be something intuitive to people.

**Comment by larspa** [comment]
Well a very wrong but working solution would be adding a `dragging` class to the body so that body and every DOM Object inside the body will get `cursor: grabbing !important`. Nothing will than override it.

**Comment by simonewebdesign** [comment]
Another approach using JS could be something like this:

```javascript
document.addEventListener('dragover', () => {
  document.body.style.cursor = 'grabbing';
})
```
It doesn't seem to be working consistently though...

**Comment by dwilt** [comment]
I can't get any of the suggested solutions here to work. Anything update on this?

**Comment by nathanbrud** [comment]
Switching to TouchBackend & using css to set cursor worked for me.
```
<DndProvider backend={TouchBackend} options={{ enableTouchEvents: false, enableMouseEvents: true }}>
  <div className=`my-app ${isDragging ? 'dragging' : ''}`>
      .... draglayers here
  </div>
</DndProvider>
```
```
.dragging {
  cursor: grabbing
}
```

**Comment by niron1** [comment]
> Switching to TouchBackend & using css to set cursor worked for me.
> 
> ```
> <DndProvider backend={TouchBackend} options={{ enableTouchEvents: false, enableMouseEvents: true }}>
>   <div className=`my-app ${isDragging ? 'dragging' : ''}`>
>       .... draglayers here
>   </div>
> </DndProvider>
> ```
> 
> ```
> .dragging {
>   cursor: grabbing
> }
> ```

not working for me

**Comment by jinxin0112** [comment]
+1

**Comment by shiranZe** [comment]
someone managed to resolve this?

**Comment by kurochkinSergei** [comment]
> Switching to TouchBackend & using css to set cursor worked for me.
> 
> ```
> <DndProvider backend={TouchBackend} options={{ enableTouchEvents: false, enableMouseEvents: true }}>
>   <div className=`my-app ${isDragging ? 'dragging' : ''}`>
>       .... draglayers here
>   </div>
> </DndProvider>
> ```
> 
> ```
> .dragging {
>   cursor: grabbing
> }
> ```

switching to TouchBackend worked for me

DnD provider:
```
import { DndProvider } from 'react-dnd';
import { TouchBackend } from 'react-dnd-touch-backend';

...
<DndProvider backend={TouchBackend} options={{enableMouseEvents: true}}>
...
</DndProvider>
```

Drag handlers implementation:
```
    import { useDrag, useDrop } from 'react-dnd';
    ....

    const [...] = useDrag({
      ...
      begin: () => {
        document.body.classList.add('dragging');
        ...
     },
      end: () => {
        document.body.classList.remove('dragging');
        ...
      },
    });
```

css file
```
   body.dragging: {
      cursor: crosshair !important;
   },
```

**Comment by FullstackJack** [comment]
Amazing that the touch backend actually worked. Hopefully that doesn't introduce any regressions.

**Comment by MoSheikh** [comment]
Anyone have any success with this at all? Setting the document.body class does not work using HTML5 backend.

**Comment by MrNovado** [comment]
I don't understand why you ppl keep downvoting presented solutions. While not ideal, they could be used as a solid workaround.

I had trouble getting custom drag-layers to work with `html`-backend, but I believe you could still work this out with what @kurochkinSergei suggested, adding classes to `body` or other containers on `begin/end` drag-handlers.

So what you certainly need is a selector that covers all elements of a container (say `body` for example), like in @larspa comment
```css
body.dragging * {
  cursor: grabbing !important;
}
```

This is ugly, of course, but it will get the job done. You need the cursor to be fixed in a certain (`grabbing`) state regardless of what element you actually hover over.

After that, all you need to do is to add the `dragging` class to `body` when dragging starts and remove it when it ends. 

---
If you work with custom layers, it could look something like this:

App:
```tsx
const App = () => {
  return (
    <DndProvider backend={TouchBackend} options={{ enableMouseEvents: true }}>
      <Content />
      <DndCustomLayer />
    </DndProvider>
  )
}
```

DndCustomLayer :
```tsx
const DndCustomLayer = (): JSX.Element | null => {
  const { isDragging, initialOffset, currentOffset } = useDragLayer(monitor => ({
    isDragging: monitor.isDragging(),
  }));

  useLayoutEffect(
    function overrideCursor() {
      if (isDragging) {
        document.body.classList.add('dragging');
      } else {
        document.body.classList.remove('dragging');
      }
    },
    [isDragging],
  );

  if (!isDragging) {
    return null;
  }

  return ...
};
```

---
And if custom layers aren't an option, you could still do this in the `useDrag` hook
```ts
const [...] = useDrag({
  begin: () =>  document.body.classList.add('dragging');  
  end: () =>  document.body.classList.remove('dragging'); 
});
```

**Comment by nahumzs** [comment]
@FermiDirak I just the tested the codesandbox on chorme 94.0.4606.81` and seems ok tome @hmeyerx

**Comment by cyberscorpion** [comment]
Any working solution for this in Chrome and Safari together?

**Comment by HSunboy** [comment]
set `dropEffect` in `useDrag` 
```javascript
useDrag({
    ...
    options: {
      dropEffect: 'copy'
    }
  });
```

**Comment by oscarestigz** [comment]
Still nothing to fix this?

**Comment by HTMLhead** [comment]
What about using state on wrapper component? 
```javascript
const style = (dragging: boolean) => ({
  cursor: dragging ? "grabbing" : "unset",
  width: 400
});

export const Container: FC = () => {
  {
    const [dragging, setDragging] = useState(false);
    ....

    return (
      <>
        <div style={style(dragging)}>
          {cards.map((card, i) => renderCard(card, i, dragging, setDragging))}
        </div>
      </>
    );
  }
};
```
Similar to FermiDirak's solution. The difference is that the useDrag method is used in the child component. 
Thanks for your solution @FermiDirak. It saved my day.
[minimum reproduction](https://codesandbox.io/s/vibrant-hellman-w1mkuk?file=/src/Container.tsx)

**Comment by shahbazyanartur** [comment]
On time drag cursor sometimes changes to pointer, sometimes changes to grabbing, but I want to each time drag it changed to grabbing, have you any solution ?

`return (
        <div ref={preview}
             className='field-name field-name-border'
             style={{width: `${columnWidths[index + 1]}px`}}
             onMouseOver={onMouseMove}
             onMouseOut={onMouseMove}
        >
            <div
                className={`card field-card rounded-0 m-0 h-100 border-1 d-flex justify-content-center align-items-center 
                              noselect cursor-grab ${isOver && "border-dashed"}`}
                onDoubleClick={() => handlePreferredValuePopUpOpen(index)}
                ref={drop}
            >
                <div ref={drag}
                     className={`${isDragging ? 'cursor-grabbing drag-icon-hide' : 'cursor-move'} ${isMouseOver ? 'drag-icon-show' : 'drag-icon-hide'}`}
                     data-handler-id={handlerId}
                >
                    {dragIcon}
                </div>
                <span style={{opacity}}>{headerName.name}</span>
            </div>
        </div>
    )`

**Comment by daliusd** [comment]
It looks like many people still try to use HTML5 backend and set cursor. That's not possible and here is Chrome bug for that (BTW Firefox works better with that): https://bugs.chromium.org/p/chromium/issues/detail?id=1232555 - feel free to star it at least - maybe that will help with visibility of this issue from Chrome side. Regular users do not care about this problem, it affects only `grabbing` cursor obsessed developers (or UX designers).

In the end using Touch backend is the way to go - you still need to understand what you are doing but at least setting cursor works and is not blocked by Chrome somehow. IMHO touch backend is not worse than HTML5 backend and actually I found it being more responsive with custom drag layer.

**Comment by hein-j** [comment]
For those using a custom drag layer, I got mine working with TouchBackend. It didn't compromise any other functionality, as @daliusd suggests.

Provider:
```javascript
 <DndProvider backend={TouchBackend} options={{ enableMouseEvents: true }}>...
```

CustomDragLayer:
```javascript
...
  return (
    <div className='layer'>
      <div
        className='preview' >
        {preview}
      </div>
    </div>
  );
```

CustomDragLayer scss:
```scss
.layer {
    position: fixed;
    pointer-events: none;
    z-index: 100;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
}

body {
// you can conditionally set this, only when dragging
* {
   cursor: grabbing !important; 
   user-select: none // without this I get the text cursor in Safari 
}
}

```

**Comment by daliusd** [comment]
> the above solution by @hein-j worked for me. the css wasn't required, just added this
> 
> ```
>  useEffect(() => {
>     if (isDragging) document.body.style.cursor = 'grab !important';
>     else document.body.style.cursor = 'normal';
>   }, [isDragging]);
> ```

Test on Safari and Firefox. In the end you might need css anyways.

**Comment by TheMikeyRoss** [comment]
any update on this one?

**Comment by daliusd** [comment]
> any update on this one?

Read comments. It is Chrome bug.

**Comment by TheMikeyRoss** [comment]
> Read comments. It is Chrome bug.

Oh ok, I'm so sorry to bother you

**Comment by daliusd** [comment]
> > Read comments. It is Chrome bug.
> 
> Oh ok, I'm so sorry to bother you

Sorry for the tone 😄 I just tried to answer quickly 😉

**Comment by TheMikeyRoss** [comment]
> Sorry for the tone 😄 I just tried to answer quickly 😉

all good brother 😁👍

**Comment by longnt80** [comment]
> > any update on this one?
> 
> Read comments. It is Chrome bug.

Looks like same problem with Safari too.

**Comment by Cristian-T250** [comment]
Custom cursor designs are the digital signature of user experience, offering a personal touch that resonates with visitors. For any forward-thinking <a href=“https://striveenterprise.com/website-design/agency-las-vegas”>marketing agency in Las Vegas</a>, leveraging these bespoke elements is essential for crafting immersive and memorable interactions.

**Comment by abdullahmehboob20s** [comment]
anyone found solution ? I have same problem even I have set and it's not working.
```javascript
<button className={`${isDragging ? "cursor-grabbing" : ""}`}><Icon /></button>
```

**Comment by syafilm** [comment]
any solution for this? 🫠

**Comment by trend-alan-bie** [comment]
This works for react-beautiful-dnd, and it may work for react-dnd too.

```
  useEffect(() => {
    if (isDragging) {
      document.body.style.cursor = 'move';
    } else {
      document.body.removeAttribute('style');
    }
  }, [isDragging]);
```

**Comment by syafilm** [comment]
why no one workin on this

**Comment by larspa** [comment]
> why no one workin on this

Because react-dnd was designed to be a simplistic library allowing you to built anything with it. As you can see here, people find solutions that work for them and the library allows it. So no need to start supporting small requested features and as a bi-product bloat the library

**Comment by allenlongbaobao** [comment]
use can fix my problem, 
```
.canDrop * {
  cursor: copy;
}

```
https://codesandbox.io/p/sandbox/github/react-dnd/react-dnd/tree/gh-pages/examples_js/05-customize/drop-effects?from-embed=

**Comment by WillsWebsites** [comment]
Worked for me, hopefully works for you too, I saw that when I was dragging an item the classname `dragging-file` was being added to the `body`. Then I just used @hein-j  's solution of adding css and it worked:

```css
body.dragging-file * {
  cursor: grabbing !important;
  user-select: none;
}
```

not sure if that class was being added from the library or from something custom in our codebase, but you could try adding a class to the body yourself and hopefully that gives you the same results.

**Comment by Maadtin** [comment]
Is there anyway to remove the "not-allowed" cursor while dragging?

**Comment by umkl** [comment]
This did the job for me thanks to @trend-alan-bie 

```
// overwrite the default cursor on the drag object

 const { isDragging } = useSortable({ id });

className={`${isDragging ? 'opacity-50 cursor-grabbing' : 'cursor-grab'}`}


// change the cursor everywhere else in the document

  useEffect(() => {
    if (isDragging) {
      document.body.style.cursor = 'grabbing';
    } else {
      document.body.removeAttribute('style');
    }
  }, [isDragging]);


```
