### ISSUE TITLE
Is there any way to test ReactDnD interaction by not installing `react-dnd-test-backend`

### ISSUE THREAD

**Issue by weixing2014** [gaearon/react-dnd#326]
Maybe it's a silly question, but I'm working on a rails app without Bower/NPM and wondering if it's possible to test ReactDnD dragging and dropping interaction without `npm install --save-dev react-dnd-test-backend`. Any thoughts?

Thanks all.

**Comment by gaearon** [comment]
If you build the package yourself and maintain it, you can use it. :wink:
Not sure how to answer this.
We provide the package precisely because we suggest you to use it.

**Comment by gaearon** [comment]
I *guess* you can try the Browserify CDN build: https://wzrd.in/standalone/react-dnd-test-backend@latest
That's in case you need a UMD build.

**Comment by weixing2014** [comment]
Thanks @gaearon ! It's so helpful.
