### ISSUE TITLE
Body level drop target?

### ISSUE THREAD

**Issue by vgatto** [gaearon/react-dnd#328]
I'd like to implement a body level drop target for our app which is already using react-dnd.  We have the recommended top level DragDropContext:

`DragDropContext(HTML5Backend)(App)`

But when I change this to:

`DropTarget(types, spec, collect)(DragDropContext(HTML5Backend)(App) )`

The troubleshooting guide for "Could not find the drag and drop manager in the context" makes the claim 
*"It doesn't have to be the topmost component, but it has to be higher in the hierarchy than any of your component using React DnD"*

So it seems like what I'm trying shouldn't work.  I can try creating an extra component that is nothing more than a wrapper to add an extra level in the hierarchy, but it feels like I must be doing it wrong.

Is there a good way to do this?  Ideally, I'd attach to the body element and not to any react component, but I understand why that might not work.

**Comment by gaearon** [comment]
`DragDropContext` should be the outer wrapper, but in your example it's inside drop target.
You probably want `DragDropContext(HTML5Backend)(DropTarget(types, spec, collect)(App))` instead.
