### ISSUE TITLE
react-dnd with tables?

### ISSUE THREAD

**Issue by ericqt** [gaearon/react-dnd#331]
I'm currently using react-dnd with table following the simple sortable example and it sort of works. The problem is that the <tr> that I'm dragging doesn't hover and displace elements around it when I move up or down. 

Is there support for html tables?

**Comment by kocur4d** [comment]
You can have similar problem to what I had #333 

Basically the problem was with a key value I was setting up from a parent component.

[SO question](http://stackoverflow.com/questions/33725333/react-dnd-element-style-is-not-updated-on-drag-move/33725963#33725963)

**Comment by gaearon** [comment]
Closing for lack of reproducible example.
I will be happy to reopen if you provide a fiddle or a repo that reproduces the problem.
