### ISSUE TITLE
In Chrome target monitor.getItem() returns null in drop handler

### ISSUE THREAD

**Issue by yamelkaya** [gaearon/react-dnd#336]
I've ran very simple example with dustbin(single target) from your repository https://github.com/gaearon/react-dnd/tree/master/examples/01%20Dustbin/Single%20Target . When I try to get parameter which was passed in Box source (its name) through `monitor.getItem()` in `drop` handler in target I receive **null**. What should I do if I need this object in target (not source `endDrag` handler)? 

p.s. I've checked `hover` and `canDrop` handlers and they both receive object from `monitor.getItem()`. By the way I see the following exception in console (maybe it will help): 
`Uncaught Error: Invariant Violation: Cannot call endDrag while not dragging.`
`invariant @ browser.js?9520:42
endDrag @ dragDrop.js?8117:170
(anonymous function) @ DragDropManager.js?26ce:74
endDragIfSourceWasRemovedFromDOM @ HTML5Backend.js?0327:230
handleTopDrop @ HTML5Backend.js?0327:527`

**Comment by yamelkaya** [comment]
I also noticed that it does not work in stress test example http://gaearon.github.io/react-dnd/examples-dustbin-stress-test.html. I receive `Uncaught TypeError: Cannot read property 'name' of null` in 
`Container.prototype.handleDrop = function handleDrop(index, item) {
    var name = item.name;`

This is  because `monitor.getItem()` returns null

**Comment by yamelkaya** [comment]
The issue occurs in Chrome (Version 46.0.2490.80 m). I've checked it in different browsers (IE and Edge) everything works fine.

**Comment by gaearon** [comment]
Please file this in https://github.com/gaearon/react-dnd-html5-backend instead.
This is the HTML5 backend bug, not React DnD bug.
Thanks!

**Comment by gregdetre** [comment]
See https://github.com/gaearon/react-dnd-html5-backend/issues/6
