### ISSUE TITLE
Surfacing of event

### ISSUE THREAD

**Issue by tquetano-r7** [gaearon/react-dnd#338]
I have been playing around with this and its working as expected for anything where the drop container is fully visible, however I'm struggling when the container is scrollable. What I am trying to set up is a horizontal list that can be scrollable, and if they were to drag outside of the area either left or right then it would scroll the container to allow dropping to the previously-hidden area. It appears that the event is not surfaced, plus all events are stifled (tried to bind my own mousemove event to it, no luck).

Is there a way to handle this scenario? I must believe I'm not the first to encounter something like this.

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-dnd/issues/324#issuecomment-154042432.
