### ISSUE TITLE
Drop event is not triggered when item is removed from DOM after dragging starts and dropped outside of browser window in Chrome

### ISSUE THREAD

**Issue by hakanderyal** [gaearon/react-dnd#34]
Thanks for awesome lib.

On Chrome, if I remove the item from DOM after dragging starts, and drop the item outside of the browser window, drop event is not triggered. (I'm checking it on DragDropStore).

No problems on FF, when mouse is moved out of the browser window, drop event triggers immediately.

As a workaround, I've removed the [isFirefox()](https://github.com/gaearon/react-dnd/blob/d309adcae85e07a212e9c941ef052127bbcd4719/modules/utils/NativeDragDropSupport.js#L79) check from the `_lastDragSourceCheckTimeout` in  [NativeDragDropSupport.js](https://github.com/gaearon/react-dnd/blob/d309adcae85e07a212e9c941ef052127bbcd4719/modules/utils/NativeDragDropSupport.js), but haven't tested much yet if it breaks normal functionality in Chrome.

Looked around the source code a little bit for another fix, but couldn't come up with any.

**Comment by gaearon** [comment]
Thanks for reporting. I'll take a look on Monday.

**Comment by gaearon** [comment]
Would you mind sending a PR of the code that works for you?

**Comment by gaearon** [comment]
Released in 0.6.3, can you give it a go?

**Comment by gaearon** [comment]
Btw thanks for following through on this.
Browsers are nasty.

**Comment by hakanderyal** [comment]
I'm already using it, no problems so far.

Thank you for awesome work.
