### ISSUE TITLE
In Safari, cannot preserve appearance of link while dragging

### ISSUE THREAD

**Issue by ceguster** [gaearon/react-dnd#341]
I am trying to preserve the appearance of a div containing an <a> tag while dragging it. In Chrome and Firefox, I have no trouble, but in Safari, when I begin dragging the element, its appearance changes to the native browser implementation of a dragged link.

I verified the discrepancy in Safari by cloning your repo and changing the markup in `react-dnd/examples/02 Drag Around/Naive/Box.js` to include an <a> tag (see diff below). 

Even with that change, Chrome and Firefox are still able to show the original image while dragging.

Running OS X Yosemite (10.10.5)
Browsers:
* Safari: 9.0.1 (10601.2.7.2)
* Chrome: 46.0.2490.86 (64-bit)
* Firefox: 42.0

<img width="714" alt="react-dnd-safari-link-drag-diff" src="https://cloud.githubusercontent.com/assets/8506721/11409567/de40f3c0-938e-11e5-91de-585a122f8e8a.png">

**Comment by gaearon** [comment]
Moved to https://github.com/gaearon/react-dnd-html5-backend/issues/11.

**Comment by gaearon** [comment]
FYI—closed as wontfix because apparently we can't fix it.
https://github.com/gaearon/react-dnd-html5-backend/issues/11#issuecomment-167253149
