### ISSUE TITLE
shouldComponentUpdate prevents context changes from triggering render

### ISSUE THREAD

**Issue by grassick** [gaearon/react-dnd#343]
decorateHandler's shouldComponentUpdate has the side-effect of preventing context changes from triggering a re-render (https://github.com/facebook/react/issues/2517).

I am building a component that allows sorting/dragging between an arbitrary number of lists. I'm keeping track of the state at the top level and using context to pass it to arbitrarily nested list components.

However, changing the context of the top-level component does *not* trigger a render of nested list components, as the shouldComponentUpdate of the decorator returns false. 

The effect is that if any piece of the tree uses react-dnd, context changes will not cause re-renders of any components inside of them, thus breaking my components and any others that depend on re-rendering when the context changes.

**Comment by gaearon** [comment]
You can pass a custom `arePropsEqual` function as [part of the `options` argument](https://github.com/gaearon/react-dnd/blob/2df9e0d7dfc91cb6af97d3300ccddfed998bea47/src/decorateHandler.js#L20) to it.

Passing something like `arePropsEqual: () => false` should solve your problem (but make the app less efficient). A better solution would be to avoid using context, or to only use it for change subscription (e.g. pass `subscribe()` in context), and not the actual data, until facebook/react#2517 is fixed.
