### ISSUE TITLE
Can't use DragDropContext with DropTarget

### ISSUE THREAD

**Issue by geohuz** [gaearon/react-dnd#350]
I'm trying to follow the 'Cancel on drop outside' example, but with ES5 syntax, So in the container I use:

module.exports = flow( 
	DragDropContext(HTML5Backend),
	DropTarget(ItemTypes.CARD, boxTarget, collect))(Container);

But I get Could not find the drag and drop manager..., is there any thing wrong with my syntax?

Thanks!

**Comment by guerrero** [comment]
@geohuz you should invert the order of the functions:

```js
module.exports = flow(
  DropTarget(ItemTypes.CARD, boxTarget, function (connect) {
    return {
      connectDropTarget: connect.dropTarget()
    };
  }),
  DragDropContext(HTML5Backend)
)(Container)
```

**Comment by geohuz** [comment]
All right, that works perfectly!
