### ISSUE TITLE
Need suggestion on ways to confining the drop to an area

### ISSUE THREAD

**Issue by geohuz** [gaearon/react-dnd#351]
I tried the example 'drag around', but I can drop the 'drag me box' outside the container, especially on the left side of the window, and the 'cancel on drop outside', it looks I can make sure the source box can be always confining in the target box, I'm not sure which way is the best to fulfil the requirement. Could somebody help me?

Thanks!

**Comment by gaearon** [comment]
You have [full control](https://github.com/gaearon/react-dnd/blob/2f97cda8814d68741905d21e4719544d730ade88/examples/02%20Drag%20Around/Naive/Container.js#L17-L22) over where the box gets moved. It is up to you to trim the coordinates before updating your state.
