### ISSUE TITLE
DropTarget spec isOrigin

### ISSUE THREAD

**Issue by jisaacks** [gaearon/react-dnd#354]
I am wondering if it makes sense to have an *isOrigin* to drop targets spec to be able to differentiate it from other drop targets. 

I feel like it would be helpful but I am new to this project and it might not make sense or maybe there is another way I am ignorant of?

If it would make a good addition I wouldn't mind taking a stab at it if pointed in the right direction.

**Comment by gaearon** [comment]
Not sure what you mean. If you want to specially treat a component that acts both as drop target and drag source, for current drag operation, you’ll want to include some data that uniquely identifies it (such as an ID from props) in the object you return from `beginDrag()`, and check `props.id === monitor.getItem().id` in the drop target spec methods.
