### ISSUE TITLE
Jest tests are failing if a component is wrapped with DropTarget

### ISSUE THREAD

**Issue by yborunov** [gaearon/react-dnd#357]
When I run jest tests, some of them, that are using react-dnd, are failing with the following error: 
`Invariant Violation: Expected "spec" provided as the second argument to DropTarget to be a plain object. Instead, received [object Object]. Read more: http://gaearon.github.io/react-dnd/docs-drop-target.html`

Full trace log:
```
Invariant Violation: Expected "spec" provided as the second argument to DropTarget to be a plain object. Instead, received [object Object]. Read more: http://gaearon.github.io/react-dnd/docs-drop-target.html

at Object.invariant [as default] (node_modules/fbjs/lib/invariant.js:39:15)
at DropTarget (node_modules/react-dnd/lib/DropTarget.js:56:25)
at eval (src/js/containers/Item.jsx:93:645)                
at Object.eval (src/js/components/Main.jsx:9:666)
at Spec.eval (src/__tests__/containers/Main-test.jsx:25:15)
```

Component is written with ES6 syntax (+ES7 decorators for DropTarget and DragSource wrapping) and using babel-jest preprocessor for transpilling to normal JS before running actual tests.

**Comment by yborunov** [comment]
I also posted an issue with some of my new insights in Jest repo: 
https://github.com/facebook/jest/issues/688

I'm not sure if it still `react-dnd`'s problem or not, thus I'll leave it opened till it's resolved.

**Comment by gaearon** [comment]
I don’t know enough about Jest. We’re just doing a plain object check there with `isPlainObject` from Lodash. If Jest wraps your spec object, you will need to disable this behavior. (Maybe something like [`jest.dontMock()`](https://facebook.github.io/jest/docs/api.html#jest-dontmock-modulename) could help here.)

**Comment by yborunov** [comment]
I figured out that the problem was with mocking lodash library. I had manually specify lodash library in Jest's unmock configuration, even though I'm not using it in the project and it's only a dependency for react-dnd

**Comment by yborunov** [comment]
So it's kind of an odd behaviour of Jest mocking mechanism
