### ISSUE TITLE
Replacing target with source on hover throws "Expected to find a valid target" error

### ISSUE THREAD

**Issue by tko** [gaearon/react-dnd#360]
I'm making a grid where each of the cells is either occupied (drag source) or empty (drop target), both implemented as separate components. When moving an item in the 'hover' callback I'm getting `Uncaught Invariant Violation: Expected to find a valid target` logged in the console presumably because the move replaces the target with a source. Everything appears to be in working order though, just spamming the console.

```
Uncaught Invariant Violation: Expected to find a valid target.
    invariant            @ browser.js?9520:40
    canDropOnTarget      @ DragDropMonitor.js?0588:88
    (anonymous function) @ HTML5Backend.js?0327:442
    handleTopDragEnter   @ HTML5Backend.js?0327:441
```

Simplified example in http://jsbin.com/nesufabuyo/1 -- the output only mode shows the behavior accurately, but the error breaks the output in edit mode.

**Comment by giladv** [comment]
hi, i think i have a similar problem, did you find a solution?

**Comment by gaearon** [comment]
Unfortunately the bin has expired :-(.
Can you please create it again?
I would like to look into this.

**Comment by gaearon** [comment]
This is probably fixed in 2.1.0.
I’ll close but please let me know if not, and I’ll reopen.

**Comment by tko** [comment]
I've cloned it into http://jsbin.com/mocepikiko/1 but couldn't find cdn urls for 2.1.0 so didn't update those.

**Comment by gaearon** [comment]
Here they are:

https://npmcdn.com/react-dnd@latest/dist/ReactDnD.min.js

https://npmcdn.com/react-dnd-html5-backend@latest/dist/ReactDnDHTML5Backend.min.js
