### ISSUE TITLE
Layer monitor.getItemType() sometimes returning __NATIVE_URL__

### ISSUE THREAD

**Issue by Mokto** [gaearon/react-dnd#364]
Hi,

It is hard to explain this, but when I drag DnD items, I SOMETIMES got this as props in Layer :

monitor.getItemType() => '__NATIVE_URL__'
monitor.getItem() => {urls: null, get urls: function}

Sometimes it works, sometimes it throws an error. I have no clue.

Please let me know if you need anything else.

**Comment by gaearon** [comment]
Please provide an example reproducing the problem.
Otherwise it is impossible to guess what the issue is.
I’ll be happy to reopen if you provide an example.
