### ISSUE TITLE
error when handling hover: findDOMNode is not defined

### ISSUE THREAD

**Issue by IljaDaderko** [gaearon/react-dnd#366]
I'm implementing dnd into my project and so far everything seems to work fine but I get a console error when I handle hover of item over its target.

This is the error

`Uncaught ReferenceError: findDOMNode is not defined`

related code

```
hover(props, monitor, component) {
    console.log("Hovered");
    const clientOffset = monitor.getClientOffset();
    const componentRect = findDOMNode(component).getBoundingClientRect();
    const isJustOverThisOne = monitor.isOver({ shallow: true });
    const canDrop = monitor.canDrop();
  }
```

**Comment by wdhorton** [comment]
The problem is that findDOMNode isn't defined globally, it's defined on the
ReactDOM object. So you should reference it as ReactDOM.findDOMNode,
assuming you've imported/required ReactDOM somewhere else already.
