### ISSUE TITLE
Passing props from original component to drag layer

### ISSUE THREAD

**Issue by IljaDaderko** [gaearon/react-dnd#367]
I've successfully implemented DragLayer following this post https://gaearon.github.io/react-dnd/docs-drag-layer.html however there is one issue I still cant solve. Item that is being dragged originally has two parameters (type and title) that I need to set as parameters within my DragLayer component i.e renderItem function, so something like this

```
renderItem(type, item) {
    switch (type) {
    case ItemTypes.BOX:
      return (
        <BoxDragPreview type={item.type} />
      );
    }
  }
```

but this is not working. Do I need to pass the title in here from somewhere else? Issue here is that each dragable element has unique type, so I need to grab one from item that is currently dragged and can't pass it in manualy

**Comment by wdhorton** [comment]
Have you tried this?
```
return (
  <BoxDragPreview type={item.type} title={item.title}/>
);
```

You're allowed to set multiple props on the same component, if you want access to both type and title. Let me know if I misunderstood your issue.

**Comment by IljaDaderko** [comment]
@wdhorton I did, it returns undefined in both cases.

**Comment by wdhorton** [comment]
Looking at your code and the [docs for DragLayerMonitor](https://gaearon.github.io/react-dnd/docs-drag-layer-monitor.html), I see that `item` comes from `monitor.getItem()`. The variable `item` in this case is whatever object you returned from the `beginDrag()` method of your DragSource. So in `beginDrag()`, you just want to be sure the object you return has both `type` and `title`. If you need more explanation, please share your DragSource code so I can take a look.

**Comment by gaearon** [comment]
This comment is correct: https://github.com/gaearon/react-dnd/issues/367#issuecomment-179491948.
If you don’t see those properties on the `item`, you were not returning them from `beginDrag()`.

I don’t think it’s an issue with the library so I’m closing but feel free to continue the discussion.
