### ISSUE TITLE
clamp motion of drag preview?

### ISSUE THREAD

**Issue by rpedela** [gaearon/react-dnd#371]
Is it possible to clamp the motion of the drag preview? I have draggable, horizontal tabs and I want the preview to move horizontally but not vertically. In addition, I want the preview to only move horizontally the width of the tab bar rather being moved over other things. I think I just need a way to manually set the position of the preview. Is that possible? If so, how?

**Comment by hawkrives** [comment]
I think that you could tweak the [custom drag layer example](https://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) to do what you want.

(Note: I haven't experimented with the custom drag layers in my own app yet, so I'm not fully aware of any limitations that it might have.)

**Comment by gaearon** [comment]
Yup, that’s the example you should be looking for.
