### ISSUE TITLE
Safari (9.0.3): Start dragging on disabled input doesn't work.

### ISSUE THREAD

**Issue by raphaelparent** [gaearon/react-dnd#372]
I'm building an app where users can drag "items" around allowing them to organize them as they want. These items have a disabled input that can be enabled to change the value of the item name.

Starting to drag on the disabled input works fine in Chrome v48.0.2564.97 and in Firefox v44.0 (even though events on disabled elements are just canceled and don't propagate) but not in Safari v9.0.3.

I did quite a bit of research and found nothing about Safari having problems with drag events and disabled inputs so I thought I would post it here.

My codebase is quite large so I can't really post code here but, if required, I will create a small repo with a working example of the bug.

Here's a (slow) gif of the problem :)

![Gif example of the problem](http://i.imgur.com/Psskv12.gif)

**Comment by gaearon** [comment]
Thank you for the detailed description and the screenshots.

This would be more relevant to https://github.com/gaearon/react-dnd-html5-backend than this repo.
Nevertheless I think there is no point to moving the issue there.

I tried looking into this, and Safari just triggers the `dragend` event immediately when the input is disabled.
I don’t think we can work around this in any way from the library side.
It’s just an unfortunate browser quirk.

**Comment by raphaelparent** [comment]
Ok perfect! Anyhow, it's good to have it documented somewhere since I didn't found anything while making research and others will probably have the same problem.
