### ISSUE TITLE
Only works for stateless components

### ISSUE THREAD

**Issue by liorbentov** [gaearon/react-dnd#374]
My D&D items are components that are statefull, but now, since i've add ReactDND, they are not re-rendering properly.

Help please...

**Comment by raphaelparent** [comment]
I am using ReactDND with stateful component. Can you post some code or create a small repo containing only code related to the issue?

I had a problem with the state that didn't behaviour as expected. I have something like the [sortable example](http://gaearon.github.io/react-dnd/examples-sortable-simple.html) and when I was iterating to render my component, the key was actually the `i` from iterating. Changed it to a `unique id` (in my case something from the database).

```
{this.props.items.map((item, i) => {
	return (
		<TreeItem key={'UniqueComponentString'+item.id} /> // item.id instead of i
	);
})}
```

**Comment by liorbentov** [comment]
Well.. I'll try to supply something soon.. 
Meanwhile, I'll try to describe my problem - 
There are set of rows that are sortable, each row contain a button. when you click on a row's button, a modal of this row's details pops up.

When I use DND, the dragging and the sorting works, but when I press the button the modal doesn't pop up (it is only when I dragging again)

**Comment by gaearon** [comment]
Hi, have you been able to resolve the issue?

**Comment by liorbentov** [comment]
Hey, I thought I had it, but don't...

On Sun, Feb 14, 2016 at 5:29 PM Dan Abramov <notifications@github.com>
wrote:

> Hi, have you been able to resolve the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaearon/react-dnd/issues/374#issuecomment-183905517>.
>
-- 
<www.blazemeter.com>
Lior Shub
Frontend Developer
P: (+972) 546-378-787
<https://twitter.com/BlazeMeter>
<https://www.linkedin.com/company/2364558>
FEB
11
Webinar: Why App Performance Testing Must Evolve in the Digital Era
<http://info.blazemeter.com/evolve_your_application_performance_testing_digital_era_webinar?utm_source=BM&utm_medium=Signature&utm_campaign=SignaturePromo>
Register
<http://info.blazemeter.com/evolve_your_application_performance_testing_digital_era_webinar?utm_source=BM&utm_medium=Signature&utm_campaign=SignaturePromo>

**Comment by gaearon** [comment]
I am happy to help it you can publish a project reproducing the issue.
