### ISSUE TITLE
Should I really wrap the entire application?

### ISSUE THREAD

**Issue by granteagon** [gaearon/react-dnd#375]
The [React-DND website](http://gaearon.github.io/react-dnd/docs-tutorial.html) recommends wrapping the application with DragDropContext.  I'm writing a large application.  Is this really what's needed, or should I wrap the particular "module" I'm dealing with?

In my case, I have a table on some pages that have drag and drop columns.  Columns would never be dropped on anything outside the table.

If I'm really supposed to wrap the entire app, what are the implications of doing so (if you have time to answer that question)?  Thanks!

**Comment by gaearon** [comment]
It’s only important to wrap the part of the app that contains `DragSource`s and `DropTarget`s.
