### ISSUE TITLE
can't use DropSource

### ISSUE THREAD

**Issue by zwlzwt** [gaearon/react-dnd#376]
Always Warning:Failed Context Types: Required context `dragDropManager` was not specified in `DragSource(Page)`. Check the render method of `Tab`.

Here is a part of my code, I have 4 fixed pages and a resort list .... I want to dropresort a list ..I don't konw how to fix the worng things,need some help ... This all in one page application .
![66 pic](https://cloud.githubusercontent.com/assets/5884940/12953103/0acf19e2-d054-11e5-9666-54b8fb56e69c.jpg)
![69 pic](https://cloud.githubusercontent.com/assets/5884940/12953102/0ace2582-d054-11e5-89bf-0c37910f8c2d.jpg)
![70 pic](https://cloud.githubusercontent.com/assets/5884940/12953104/0ad526b6-d054-11e5-95e2-58cf7ff846eb.jpg)
![71 pic](https://cloud.githubusercontent.com/assets/5884940/12953105/0add061a-d054-11e5-9da4-6c877ceadce6.jpg)

**Comment by gaearon** [comment]
You are wrapping your root component with `DragDropContext` and then not using it.
Instead of:

```js
ReactDOM.render(
  <EditPage />,
  document.getElementById('preview')
)

module.export = DragDropContext(HTML5Backend)(EditPage)
```

you want something like

```js
// EditPage.js
module.exports = DragDropContext(HTML5Backend)(EditPage)

// index.js
ReactDOM.render(
  <EditPage />,
  document.getElementById('preview')
)
```

or, alternatively,

```js
EditPage = DragDropContext(HTML5Backend)(EditPage)

ReactDOM.render(
  <EditPage />,
  document.getElementById('preview')
)
```

The idea is that whatever you render should already be wrapped in `DragDropContext`. Just exporting it from the same model where you call `ReactDOM.render` has no effect because this export isn’t used anywhere.

**Comment by zwlzwt** [comment]
ok，I got it ,thank you very much

**Comment by zwlzwt** [comment]
code`

**Comment by zwlzwt** [comment]
`ReactDom.render();`

**Comment by zwlzwt** [comment]
`EditPage = DragDropContext(HTML5Backend)(EditPage)

ReactDOM.render(
  <EditPage />,
  document.getElementById('preview')
)`

**Comment by zwlzwt** [comment]
`EditPage = DragDropContext(HTML5Backend)(EditPage)

ReactDOM.render(
  <EditPage />,
  document.getElementById('preview')
)`

**Comment by zwlzwt** [comment]
`EditPage = DragDropContext(HTML5Backend)(EditPage)`

**Comment by zwlzwt** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```
