### ISSUE TITLE
Custom Drag Layer Snapping To Drop Target

### ISSUE THREAD

**Issue by saschfred** [gaearon/react-dnd#381]
Hi there,

is there a way to make a custom drag layer aware of the drop traget which is hovered right now? I would like to get the drag preview to snap to the inside edges of the drop target.

Thanks for any suggestions

**Comment by gaearon** [comment]
I would suggest using some kind of global state (parent component or a store) for this. In target’s `componentWillReceiveProps`, note when `isOver` changes, and fire an action (or modify parent state in some other way). You can pass the information about the target in a callback. Then have drag layer receive that part of the state as a prop.
