### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by stinoga** [gaearon/react-dnd#382]
Any plans to implement an accessible alternative to drag and drop? Here is an example of an approach I've used in the past:

http://www.sitepoint.com/accessible-drag-drop/

**Comment by gaearon** [comment]
This library is not actively developed so its feature set is unlikely to change unless somebody takes charge. What you describe might be possible to implement as a custom backend. It can even wrap the [HTML5 backend](https://github.com/gaearon/react-dnd-html5-backend) to enhance it with this functionality.

If you’d like to work on this, please do, and share the results!

**Comment by dwjohnston** [comment]
@gaearon  - Hey Dan - this thread is the top google result for "react dnd accessibility" - is your reply above still accurate? It seems like react-dnd is a actively maintained library. What's the state of play in terms of accessibility?

**Comment by gaearon** [comment]
>  is your reply above still accurate

I don't know — I'm not involved with it. The current maintainers would know.
