### ISSUE TITLE
Set isOver in drop target based on drag layer bounds

### ISSUE THREAD

**Issue by stinoga** [gaearon/react-dnd#383]
Currently, when dragging a drag layer over a drop target, the drop target isn't active until my cursor is over it. In my case though the drag layer is much larger than my cursor. Is there a good way to have my drop target activate based on the boundary of the drag layer?

**Comment by gaearon** [comment]
You could make an invisible target the size of the drag layer and flip some kind of global state (e.g. parent component state or a store state) when its `isOver` changes. Pass that part of the state to your drop target so it activates *either* if `isOverMe` or `isOverLayer` (names I made up).

**Comment by stinoga** [comment]
@gaearon I'm not sure how that solves the problem though. In the example below, I'm dragging out of the target on the left, and into the target on the right. Since my cursor is in between the two, neither has an active `isOver` state. I'd like the right one to be active.

![DnD image](https://raw.githubusercontent.com/stinoga/stinoga.github.com/master/DnD.png)

**Comment by gaearon** [comment]
Oh, I think I see what you mean. You could do this?

```js
function collect(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    canDrop: monitor.canDrop(),
    isOver: monitor.isOver()
  }
}
```

in the component, `this.props.canDrop` is `true` when you’re dragging something compatible, and `this.props.isOver` is `true` when it’s over the target.

Does this help?

**Comment by stinoga** [comment]
@gaearon I can see the direction you are going, but that's not exactly what I need. In the image above, I want the right dropTarget to be active when the dragLayer is over top of it, not just when the cursor is. Does that make sense?

**Comment by gaearon** [comment]
I think my comment above is still relevant:

>You could make an invisible target the size of the drag layer and flip some kind of global state (e.g. parent component state or a store state) when its isOver changes.

Combine this hoisted state with `canDrop` to tell whether the drop target should be active.

**Comment by iamjager** [comment]
@stinoga Have you eventually found the solution? Currently struggling with this as well.
