### ISSUE TITLE
Dynamically set DropTarget type via the parent component

### ISSUE THREAD

**Issue by mordra** [gaearon/react-dnd#388]
In all the examples, I've seen a hardcoded DropTarget type, e.g 
```javascript
DropTarget(DragDropTypes.Item, target, collect)(ShopContainer);
```

But what I'd like to do is for the parent component to pass down a type so I can reuse the container for other DropTarget types.

```javascript
<ShopContainer dropTargetType={DragDropType.AnotherType} />
//and for my drop target to dynamically set the type
DropTarget(props.dropTargetType, target, collect)(ShopContainer);
```

I'm currently trying to work around this by exporting multiple DropTarget containers, one for every type that I want.

**Comment by mordra** [comment]
Actually, I just figured it out. Read the doco for the 5th time and finally understood what was meant by:
`A string, an ES6 symbol, an array of either, or a function that returns either of those, given component's props. `
i.e
DropTarget((props) => {return props.dropTargetType;}, target, collect)(ShopContainer);

**Comment by andrew-culver** [comment]
@mordrax I read it more than 5 times and never did get it. Now I do.

**Comment by andrew-culver** [comment]
@gaearon There should be an example like this in the docs and/or tutorial. Aside from that, I am finding them both excellent.

**Comment by nsuthar0914** [comment]
@mordrax saved my day

**Comment by mordrax** [comment]
@nsuthar0914 I've moved on to Elm, give it a go, I might save you a week this time ;)
