### ISSUE TITLE
Scroll jumping when dropsource hovers drop target

### ISSUE THREAD

**Issue by IljaDaderko** [gaearon/react-dnd#389]
I came across annoying issue that I believe is cause by react dnd.
I have a functionality where user can post a link and it places related image inside a block, block being a droptarget here. I'm not sure, but because of this, now when I hover over such block with dropsource the window scrolls to the top some amount. DropTargets are inside a div that has `overflow-y: scroll;` maybe it is not picking up change in height after image is loaded, but essentialy I wanted to ask if anyone came across this issue before or if you have any ideas to what could be causing this?

**Comment by gaearon** [comment]
It’s hard to say without a reproducible example on JSBin or similar website. In any case, React DnD doesn’t touch your DOM except for setting `draggable` attributes or adding event handlers, so whatever issue you have is likely a DOM issue and not related to this library.

For this reason I will close, but feel free to drop a link showing the wrong behavior. Maybe we can figure out why it happens. Or if you have definite proof that it’s React DnD that’s messing up scroll position, I am happy to reopen.
