### ISSUE TITLE
How to avoid this  :(

### ISSUE THREAD

**Issue by roth1002** [gaearon/react-dnd#392]
I can drop and drag as below infinity:

![giphy](https://cloud.githubusercontent.com/assets/8485590/13346610/67709824-dca2-11e5-91f6-de6afc499c62.gif)

**Comment by gaearon** [comment]
You might find this helpful: https://github.com/gaearon/react-dnd/pull/309

**Comment by roth1002** [comment]
:+1:   Thanks
