### ISSUE TITLE
Accessing top level store from a drop target

### ISSUE THREAD

**Issue by mordra** [gaearon/react-dnd#396]
My problem is that I need to perform some logic on my state to see if the drop is legal prior to firing actions. But I don't know how to access the store from the drop callback, it only takes in source and it's own props.
I've tried a few hacks such as passing parts of the state through the source so I can do business logic on the drop but that feels really hacky.
I also tried to pass down a function from a smart container component as a prop but even that component does not have access to the full state in it's dispatch prop.

I think it's a larger issue of me not knowing how to access a normalised state from event sources which require logic from any part of the state which is not included in the current component.
The alternative would be to include the root state in all components.

What am I doing wrong?

I've avoided putting in code cause it's kind of everywhere... but if you want a clearer picture of what I'm talking about, have a look at the drop function (line 37) here: https://github.com/mordra/cotwmtor/blob/master/client/shop/shopContainer.jsx

This is where I want to query the store with the ids that I have.

**Comment by mcrawshaw** [comment]
I call my parent component (smart container) to make the decision...

`@DropTarget(
  [EntityTypeEnum.Flow.toString(), EntityTypeEnum.Application.toString()],
  {
    canDrop(props: Props, monitor: any) {
      return props.onBeforeDrop(monitor.getItemType().toString(), Number(monitor.getItemType()));
    },
    drop(props: Props): {coordId: string} {
      return {coordId: props.cell.coord.id};
    }
  },
  (connect: any, monitor: any) => ({
    dndDropTarget: connect.dropTarget(),
    dndIsOver: monitor.isOver()
  })
)
@Radium
export default class MapCell extends React.Component<Props, State> {
...
}`

Does that help at all?

**Comment by mcrawshaw** [comment]
I use an event handler prop to call up the component hierarchy until I can make the decision...

``` javascript
@DropTarget(
  [EntityTypeEnum.Flow.toString(), EntityTypeEnum.Application.toString()],
  {
    canDrop(props: Props, monitor: any) {
      return props.onBeforeDrop(monitor.getItemType().toString(), Number(monitor.getItemType()));
    },
    drop(props: Props): {coordId: string} {
      return {coordId: props.cell.coord.id};
    }
  },
  (connect: any, monitor: any) => ({
    dndDropTarget: connect.dropTarget(),
    dndIsOver: monitor.isOver()
  })
)
@Radium
export default class MapCell extends React.Component<Props, State> {
...
}
```

Is that helpful at all?

**Comment by gaearon** [comment]
I would argue that if you need access to store state in `canDrop()`, this store state should have been selected as a prop in `connect()` call. Then you’d have it in your `props`.

**Comment by mordra** [comment]
My parent component is called `<Container>` and it handles knowing which `<Item>` is in the container. When I'm moving items around containers, I can use the container id and the item id. In their respective components, I'm able to pass the state.items and state.containers to resolve the actual data.
However, in the canDrop or the drop functions, what I need is access to both containers and items to decide whether an item is allowed to go into a container.

So this means that I'm passing down a reference to two collections (state.items, state.containers) into my props through connect. Then in my drop, I'll do a `state.items[source.id]` to get the item dropped from the source?
I can do this but it feels wrong because the more collections that's required from the normalized state tree, the more props I'd pass into the component. This leads to passing the whole root level state doesn't it?

**Comment by mcrawshaw** [comment]
I agree, probably not the best example to put up.  :-)

In my case I can't quite make the call in the context of the MapCell.  The surrounding cells (in a hex grid) can sometimes block the drop of certain source types.  As I write this I'm already questioning the decision, maybe I need to give the MapCell more context...  Ignore me.

Back to you @morda...

**Comment by mcrawshaw** [comment]
Trying to understand your code a little better, but personally finding it hard without some context of the real-world problem or what it looks like.

Are you using canDrop at all?  Are you aware it's possible to make a call on the target about whether it should go ahead, then dispatch actions from the source?  Does that make the state problem better?

**Comment by mordra** [comment]
canDrop probably won't help because the source knows even less than the destination. The destination is the one that needs to work out whether the dropped target will fit.

What I'm making is a game. There's a concept of a `Container` which is a bag, backpack, carrying thing of sorts and then a concept of `Item`.

Here is where I define a container with items:
https://github.com/mordra/cotwmtor/blob/master/client/shop/shopComponent.jsx#L52

I then drag items around into different containers. These containers are also items themselves (e.g you can put a bag in a bag). The logic that I need to put in is whether the item being dragged is going to exceed the container item's weight limit.

So if you think of my state tree like this:
```javascript
let state = {
  items:{
    id,
    weight,
    containerId
  },
  containers:{
    id,
    itemIDs:[]
  }
}
```

Then when I drop an item into a new container, I've got the source item's id (iid), the source container id (cid) the destination iid/cid.
So in my drop function, I need to query `state.items[dest_iid]` to get the weight of the item I'm moving and I need to query `state.items[dest_cid]` to get the current weight it's holding.
However, the drop is wrapped around the `Container` component and this component doesn't have a list of items in it's props. Dan suggested to pass in the items and containers into props, but that would mean my Container component becoming a data access object, not to mention updating on every item or container change. I can't pass just the item/container that I'm interested in because you don't know which item the user will drag.

So I don't know if this made it any clearer. I'm stumped.

**Comment by mcrawshaw** [comment]
Great explanation, thanks.

I think there are 3 ways to get this done...

1. Send all the data down (current solution). LEAKY ABSTRACTION
2. Handle the decision further up the component hierarchy (my initial suggestion). LEAKY ABSTRACTION
3. Provide the destination `Container` with just enough information to make a decision.  Is it possible to define a `currentTotalWeight` field?  This way you only need the source `Item` weight (can be passed at drop time by the drop source).  This should work well for the `Container` in a `Container` problem as well.  GOOD ABSTRACTION?

I do this with my application's hex-based grid.  When there are changes to how an item is placed on the grid I need to modify the grid weight (this helps with path-finding algorithms).  To accomplish this I split my reducers into 2 phases; (1) handle changes to items, (2) handle item changes that impact the grid.  Does that make sense?

Now, it's trickier for you because `Container` can contain itself...  Should a backpack fit into another backpack anyway?? ;-P

Does that help at all?

**Comment by mordra** [comment]
I do like that 3rd point. And it would be nicer to give that container all the items and say, render this and keep track of the current weights. But (and it's a small but) the logic is everywhere. So in my connect, I'll map the items, in my component, I'll calculate the existing weights, in my drop, I'll do the comparison before triggering a prop that does the action. This prop will be defined back in the connect (mapDispatchToProps). Really everywhere.

I thought that if I just had the containerId and the itemId, I could do some state queries from the onDrop method without passing things around... I guess that would be a very global approach. And by passing the items directly into the containers, it would mean that the container would only update when an item changed. Ok, I'll give it a go.

Re your two phases, it sounds like me just firing off multiple bunches of dispatches. So when an item moves, I have to update the containers that it's moving from/to. Then I have to update the current weight of the container item. And if the item was equiped, I have to fire off more dispatches to update the player's new stats based on the equipment change! This is all preceeded by the weight check, the shop buy/sell check etc etc...

What you're doing sounds interesting too, hexes, weight, path finding. Sounds like a turn-based strategy game ;)

**Comment by mordra** [comment]
I've re-factored my code so that components are passed in actual objects rather than their ids and they pass these objects to the dragSource which in turn are passed to the dropSource so I no longer have the problem of trying to access bits of the store in the drop or in my connect function.
It's working well, thank you for all the help.

**Comment by wookiem** [comment]
I faced similar issue and this approach appears to work:

```
const cardTarget = {
  drop(props, monitor, component) {
    const { cardId } = monitor.getItem();
    component.droppedCard(cardId)
  }
}

class Card extends Component {
  constructor(props) {
    super(props)
    this.droppedCard = this.droppedCard.bind(this)
  }

  droppedCard(cardId) {
    var store = this.context.store;
  }

  render () {
     ...
  }
}

Card.contextTypes = {
  store: PropTypes.object
}
```

**Comment by mordrax** [comment]
I've since moved on to Elm but loved the concept so much that I
reimplemented it in Elm. I've had none of the issues that I had with
react-dnd re debugging, passing ids etc. Here is my re-implementation that
I did 2 weeks after picking up Elm:
https://github.com/mordrax/cotwelm/blob/master/src/Utils/DragDrop.elm it
has served me very well.
