### ISSUE TITLE
Can I restrict dragging only in one axis ? 

### ISSUE THREAD

**Issue by GinoLlerena** [gaearon/react-dnd#397]
Hi my problem is that I am working in a project similar to google forms, and I want to know If  I can restrict the dragging only to one axis.

Thanks for your help

**Comment by mcrawshaw** [comment]
The default backend for react-dnd uses HTML5 drag-and-drop.  If you Google "constrain x/y for HTML5 drag-and-drop" you will find that it is not possible.

It may however be possible with the [react-dnd-touch-backend](https://github.com/yahoo/react-dnd-touch-backend).  It doesn't look to be a feature of this repo, but if you look at the code (very simple) you may be able make the appropriate change by ignoring event updates from a certain axis.

**Comment by cpunion** [comment]
@GinoLlerena I just finish a similar prototype using DragLayer, write a DragLayer and replace the default drag image to an empty image. you can view https://github.com/gaearon/react-dnd/blob/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer/CustomDragLayer.js .

I modified the `getItemStyles` to:
```js
function getItemStyles (props) {
  const { initialOffset, currentOffset } = props
  if (!initialOffset || !currentOffset) {
    return {
      display: 'none'
    }
  }

  let { x, y } = currentOffset
  y = initialOffset.y

  const transform = `translate(${x}px, ${y}px)`
  return {
    transform: transform,
    WebkitTransform: transform
  }
}
```
It was locked to X axis. It's that you want?

**Comment by gaearon** [comment]
Yes, drag layer makes it possible because it lets *you* draw (and control) the preview.
In fact [this example](http://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) has a “Snap to Grid” checkbox you can try.

**Comment by kaflan** [comment]
now example is die

**Comment by haxxxton** [comment]
updated link to the [snapping example](https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer)

**Comment by badasukerubin** [comment]
I wrote a tip for this here: https://toluwaniadewale.com/blog/constrain-react-dnd-to-the-horizontal-axis
