### ISSUE TITLE
Is it possible to change styling of drag preview?

### ISSUE THREAD

**Issue by igorrKurr** [gaearon/react-dnd#399]
Hey,

I want to change some styling of my drag preview. I mean use same element as drag source, but with different styling, like change color, borders, transforms. etc.
 Currently I'm using DragSourceConnector.dragPreview() for this and render same element with it but with different styles binded.
But it seems to be redundant for me.
Another possibility to customize drag preview is to use custom drag layer, what is even more redundant.
If I missed answers in docs, sorry :smile: 

So, Is it possible to customize only styling of drag preview?

P.S. Btw, really brilliant library :+1:

**Comment by gaearon** [comment]
You can’t do that with the HTML5 backend because browser APIs just don’t allow this.
Your options are either

* to write a custom backend based on `mousemove` and add that capability there
* or to use `DragLayer` which works around this problem by letting you draw the preview as a component.
