### ISSUE TITLE
UMD builds attached to releases?

### ISSUE THREAD

**Issue by pspeter3** [gaearon/react-dnd#400]
It would be awesome if ReactDnD and ReactDnD HTML5 Backend had the UMD builds attached to the Github releases.

**Comment by pspeter3** [comment]
After some point, it seems like they are no longer included in the dist directory.

**Comment by gaearon** [comment]
They are not in the repo. In general, checking build artifacts into the repo is not a great practice.
They are, however, available in the npm packages and, as a result, on npmcdn:

https://npmcdn.com/react-dnd@latest/dist/ReactDnD.min.js

**Comment by pspeter3** [comment]
Yeah, I just discovered that. It's great.
