### ISSUE TITLE
Overview document enhancement request

### ISSUE THREAD

**Issue by saschwarz** [gaearon/react-dnd#401]
I'm new to react-dnd and I'm reading http://gaearon.github.io/react-dnd/docs-overview.html 
In the Putting It All Together section I was looking at:

`// When dropped on a compatible target, do something`
`    const item = monitor.getItem();`
`    const dropResult = monitor.getDropResult();`
`    CardActions.moveCardToList(item.id, dropResult.listId);`

I was wondering where `dropResult.listId` is defined? 

`DropTarget` probably has a corollary to the `DragSource` item(?). If the overview had an implementation of a `DropTarget` it would help newbies like me see how it all ties together before we get to the tutorial. Thanks!

I'd be happy to put the answer in a doc pull request if anyone could help me out.

**Comment by gaearon** [comment]
If you would like to add a comment like

```js
// dropResult is any object drop target returns from its drop() method
var dropResult = monitor.getDropResult();
```

please send a PR.

I would prefer not to complicate the intro example with details because they are presented in the [tutorial](http://gaearon.github.io/react-dnd/docs-tutorial.html) which is much more detailed.
