### ISSUE TITLE
Accessing drop target component in `drop(props, monitor)`

### ISSUE THREAD

**Issue by ir-fuel** [gaearon/react-dnd#402]
I would like to integrate a confirmation dialog when someone drops an item, but in order to do this I would need to set the state on my drop target to pop up that dialog before running the actual drop logic. Is there a way of accessing the target component somehow in the `drop` function? I only seem to be able to access its `props`.

**Comment by gaearon** [comment]
`drop()` [receives the `component` as the third argument](https://github.com/gaearon/react-dnd/blob/ca227203f0e3896789fbc29141b75d91701c0c7d/src/createTargetFactory.js#L68).

**Comment by ir-fuel** [comment]
Aha. I didn't find that in any of the docs :/
Thanks!

**Comment by gaearon** [comment]
It is described [here](https://gaearon.github.io/react-dnd/docs-drop-target.html):

>`drop(props, monitor, component)`: Optional. Called when a compatible item is dropped on the target. You may either return undefined, or a plain object. If you return an object, it is going to become the drop result and will be available to the drag source in its endDrag method as monitor.getDropResult(). This is useful in case you want to perform different actions depending on which target received the drop. If you have nested drop targets, you can test whether a nested target has already handled drop by checking monitor.didDrop() and monitor.getDropResult(). Both this method and the source's endDrag method are good places to fire Flux actions. This method will not be called if canDrop() is defined and returns false.

>[ ... ]

>`component`: When specified, it is the instance of your component. Use it to access the underlying DOM node for position or size measurements, or to call setState, and other component methods. It is purposefully missing from canDrop because the instance may not be available by the time it is called. If you want this method to depend on the component's state, consider lifting the state to the parent component, so that you can just use props. Generally your code will be cleaner if you rely on props instead whenever possible.
