### ISSUE TITLE
DragLayer opacity 1

### ISSUE THREAD

**Issue by kasperpihl** [gaearon/react-dnd#405]
Is it possible to have the default draglayer image be fully opaque upon dragging?

Thanks for an awesome framework, still getting into it.

**Comment by billyjanitsch** [comment]
Hi @kasperpihl. Unfortunately there's no way to modify the appearance of the native drag layer (it's controlled completely by the browser), but you can [implement a custom drag layer](http://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) if you want to do more advanced tweaking. The linked example also has more info about why native tweaking isn't possible.

**Comment by kasperpihl** [comment]
Aha I see. Thanks a lot for the help. (y)

**Comment by csbarnes** [comment]
Updated link for implementing a custom drag layer: https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer
