### ISSUE TITLE
Nested DropTarget for different type prevents shallow isOver test.

### ISSUE THREAD

**Issue by rturnq** [gaearon/react-dnd#406]
When nesting DropTargets which handle different types, the inner DropTarget will prevent the outer DropTarget from successfully using the `shallow` option in a `monitor.isOver()` call when the dragging item is over the inner target.

Given this [example](https://jsfiddle.net/42f53xL8/7/), if you drag the orange box labeled _A_ over the target labeled _Intermediate (B)_, The target labeled _Outer A_ gets a true value for `monitor.isOver()` but a false value for `monitor.isOver({shallow: true})`.  Similarly this is the case for _Intermediate (B)_ while dragging _B_ on to _Inner (A)_.  Note: a light green background indicates the dragging item is over the target, a darker green background indicates it is over the target using the `shallow` option.

I would expect that a DropTarget that doesn't handle the current DragSource's type would not interfere with the is over monitoring - it would act as if it wasn't there at all.  Is this expected behavior or a bug?  Is there any way to handle this problem currently?

The issue stems from a scenario where the intermediate DropTarget completely covers the outer DropTarget but handle different types.  The intermediate DropTarget prevents the outer DropTarget from knowing if the dragging item is over it or over a third inner DropTarget which handles the same types as the outer target.

Preferably the intermediate DropTarget knows nothing of the other DropTargets as it is inside of a reusable component.

Thanks for the great project!

**Comment by froatsnook** [comment]
This is fixed in dnd-core 2.0.2 :).  If I understand it correctly, the example is now working properly!  Feel free to re-open if I've misunderstood.
