### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by ubald** [gaearon/react-dnd#412]
React changed their versionning scheme and npm complains about unmet peer dependencies when using react 15.0.0-rc.1

**Comment by ubald** [comment]
https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html

**Comment by billyjanitsch** [comment]
Hi @ubald! react-dnd hasn't been tested with React 15 yet, so the peer dep is pinned to React ^0.14.0. Once it's been confirmed to work, the dep range will be updated.

In the meantime, npm@3's unmet peer dependency notice is only a console warning, so there isn't anything stopping you if you want to try it out.

**Comment by ubald** [comment]
Yes, I finally was able to have my docker build script to use the right npm version and ignore that warning. react-dnd seems to work ok in my case with react 15.

Thanks!

**Comment by globexdesigns** [comment]
I've submitted a PR which adds React 15 support. After some limited testing, nothing appears to be broken as a result of the upgrade. Waiting on @gaearon to review and approve.

https://github.com/gaearon/react-dnd/pull/423

**Comment by billyjanitsch** [comment]
Merged in 8d1260e42d48def5b9d30f9b0881589082aeabd8. Thanks @globexdesigns!
