### ISSUE TITLE
Green plus sign in Chrome

### ISSUE THREAD

**Issue by fredguest** [gaearon/react-dnd#414]
Has anyone figured out how to get rid of the green plus sign that pops up momentarily at the beginning of a drag operation in Chrome?

![dnd quicktime player today at 8 24 18 pm](https://cloud.githubusercontent.com/assets/1145624/13867691/d4f442c4-ec7e-11e5-9b3b-429c3fb1be6d.png)

**Comment by jchristman** [comment]
+1

**Comment by globexdesigns** [comment]
Hmm. Cannot reproduce this issue on Chrome 49 on Mac, or Chrome 49 on Windows on this page: http://gaearon.github.io/react-dnd/examples-drag-around-naive.html

Is this still happening for you? What version of Chrome are you using and which OS?

**Comment by eliot-akira** [comment]
I'm seeing the issue on Chrome 49 on Mac, in all the examples. On drag start, the cursor changes to a green plus sign (usually displayed by `cursor: copy`); and then becomes the "move" cursor.

**Comment by billyjanitsch** [comment]
I'm able to reproduce this sporadically in the example you linked @globexdesigns (Chrome 49, OSX 10.11) -- it only appears for a split second before behaving as expected.

My guess is that it's either a short delay between React's batched render cycle and the browser's dnd implementation (in which case we might be able to fix it) or a bug in Chrome. I'll play around with other browsers (unless someone beats me to it) and see if I can get a repro there.

**Comment by jchristman** [comment]
I'm seeing the same thing on Chrome 49 OSX 10.11.4 - appears for a split second then returns to normal. The behavior does not happen for me in Safari or Firefox.

**Comment by fredguest** [comment]
@EvNaverniouk I'm on Chrome 49 OS X 10.11.4 and yes, still seeing the issue, and yes, I see the copy copy icon when expected in this link that you referenced http://gaearon.github.io/react-dnd/examples-customize-drop-effects.html

**Comment by pvande** [comment]
Also seeing this issue in Chrome 50 on OS X 10.11.2.

**Comment by goivemaster** [comment]
also seeing this Chrome  51 on OS X 10.10.1

**Comment by dwthomas77** [comment]
I'm also seeing this on Chrome Version 51 on OSX 10.11.4.  Last merge was April 8th is this still being actively managed?  The green plus thing is kind of a deal breaker.

**Comment by kesne** [comment]
I've seen this randomly in React DnD as well as other libraries and even just raw HTML5 draggable. My guess is that it has to do with us not setting `effectAllowed` in the dragstart.

**Comment by f0rr0** [comment]
Any updates on this? Facing the same issue on Chrome 53 OSX 10.10.5

**Comment by nbc-ux** [comment]
Seeing the same thing Chrome 54.0.2840.71 10.11.6, any updates?

**Comment by gvohra** [comment]
+1

Using `{dropEffect: 'copy'}` masks the problem; but doesn't make it go away. In addition, it seems `{dropEffect: 'move'}` doesn't appear to successfully make the cursor a 4-pointed cross-hair.

Chrome version: 55.0.2883.95 (Official Build) (64-bit)

**Comment by fredguest** [comment]
Closing this issue as it does not seem to be a function of this library.

**Comment by Yamikamisama** [comment]
@fredguest did you ever find a solution to this?

**Comment by fredguest** [comment]
@Yamikamisama sadly no.

**Comment by fej-snikduj** [comment]
The green plus button doesn't show up for me until my canDrop function returns false, then it appears.

**Comment by willb335** [comment]
This didn't help me
```
event.dataTransfer.dropEffect = 'none'
event.dataTransfer.effectAllowed = 'none'
```
It happens only for a moment between ```cursor: 'grab'``` and ```cursor: 'grabbing'```
It doesn't show in the gif format unfortunately but the pic below the gif shows the problem

![greenplus](https://user-images.githubusercontent.com/10157307/43536795-82820e64-958b-11e8-8060-c0279ffff555.gif)



<img width="600" alt="screen shot 2018-08-01 at 12 57 15 pm" src="https://user-images.githubusercontent.com/10157307/43536402-83d14664-958a-11e8-823c-f00dcf71b793.png">

**Comment by PawelDecowski** [comment]
I’m also experiencing this problem. It looks like a bug in Chrome.

**Comment by worsnupd** [comment]
+1

**Comment by Phinodel** [comment]
+1 chrome version 84.0.4147.89

**Comment by abdalla-rko** [comment]
Hey @Phinodel,
Could you please give an example in code for what you mean with implementing a preview.

**Comment by 55Cancri** [comment]
How to fix this issue in vanilla html drag n drop? It only appears if I drag over an element with a dragOver handler. 
This:
```
event.dataTransfer.dropEffect = 'none'
event.dataTransfer.effectAllowed = 'none'
```
hides it but it breaks my onDrop handler so I  can't use them. Any other ideas?

**Comment by angel442** [comment]
I fix this issue in the dragOver handler i set this:

e.dataTransfer.dropEffect = 'move';

The problem to use 

event.dataTransfer.dropEffect = 'none'

is that then means The item may not be dropped.
