### ISSUE TITLE
Auto scroll not working while dragging item in Firefox 

### ISSUE THREAD

**Issue by hshettigar632** [gaearon/react-dnd#415]
![sheet navigation](https://cloud.githubusercontent.com/assets/16552598/13877180/40145476-ed2f-11e5-9d44-f8c601d56992.gif)

**Comment by gokulkrishh** [comment]
@gaearon is any one looking into it ???

**Comment by globexdesigns** [comment]
I'm not sure this is necessarily an issue React DnD needs to solve. React DnD uses the browser's drag and drop API. On Chrome, the implementation of the API seems to automatically scroll the containers when the drag event is near the edge of a container, but on Firefox it does not. React DnD doesn't do anything special here.

This is either something that should be reported to the Firefox team, or alternatively you can implement custom container scrolling behaviours in your app.

**Comment by billyjanitsch** [comment]
I agree with @globexdesigns -- react-dnd defer's to the browser's implementation, including scrolling behavior. If you want to make sure this is consistent between browsers, you'll probably want to write your own scrolling behavior.

**Comment by gaearon** [comment]
From the “stress test” example notice:

>This example does not scroll automatically but you can add the scrolling with a parent drop target that compares <code>component.getBoundingClientRect()</code> with <code>monitor.getClientOffset()</code> inside its <code>hover</code> handler.

**Comment by nickclaw** [comment]
I ran into this problem too and built this solution: https://github.com/azuqua/react-dnd-scrollzone

Works smoothly in every browser I've tried.

**Comment by andrew-culver** [comment]
@nickclaw react-dnd-scrollzone does the trick nicely for at minimum chrome on windows and mac. thanks.

**Comment by XiaoBieThree** [comment]
不知您是否尝试过在拖动的同时滚动鼠标滚轮。我发现FF上，我在hover中编写的自动滚动代码失效了，但可以在拖动的同时操作鼠标滚轮，也算完成需求，曲线救国。
