### ISSUE TITLE
Methods with duplicate name will not fire/will flag as missing propType

### ISSUE THREAD

**Issue by js1599** [gaearon/react-dnd#416]
I noticed that if I write a method with (for example) isDragging in the dragSource, and then try to also write a monitor for it in the collect function, that it will result in React ignoring the method in the collect function, and flagging the value as false. I don't know if this was addressed in older issues, or in the docs (the docs state you can't call monitor.isDragging() within the dragSource), but I listed it below with my code where I tested it via color of the knight piece from the example. If the isDragging was true, it was supposed to turn blue, but instead it remains green, and when switching the method associated with the isDragging property in the collect function to monitor.canDrag, the warning goes away, and everything else fires off correctly. 

Code:

  `import React, { Component, PropTypes } from 'react';
import { ItemTypes } from './Constants';
import { DragSource } from 'react-dnd';

const knightSource = {
  beginDrag(props) {
    return {};
  },
  
  isDragging(props){
      return(console.log('dragging'))
  }
  
  
};

function collect(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  }
}

class Knight extends Component {
  render() {
    const { connectDragSource, isDragging } = this.props;
    return connectDragSource(
      <div style={{
        opacity: isDragging ? 0.5 : 1,
        fontSize: 100,
        fontWeight: 'bold',
        cursor: 'move',
        color: isDragging ? 'blue' : 'green'
      }}>
        ♘
      </div>
    );
  }
}

Knight.propTypes = {
  connectDragSource: PropTypes.func.isRequired,
  isDragging: PropTypes.bool.isRequired
};

export default DragSource(ItemTypes.STUDENT, knightSource, collect)(Knight);`

**Comment by froatsnook** [comment]
It's actually working properly!

Adding `isDragging` in your collect function is used to tell the component whether it's dragging, by providing it with `props.isDragging`.  Normally this is true while you're dragging it.  But since you defined the `isDragging` function in your `DragSource` as documented [here](https://gaearon.github.io/react-dnd/docs-drag-source.html), you're overriding the default behavior, and by always returning `undefined`, the `isDragging` in your component's `props` will also always be `undefined`, and your knight is doomed to be eternally green.

**Comment by gaearon** [comment]
(Off topic:)

@froatsnook 

Thanks for helping out with managing issues and thank you for the `dnd-core` bugfix. I made you a collaborator in case you’d like to help mofd. Feel free to close what doesn’t seem to be an issue and merge PRs that make sense to you and fit well into this library’s design. Please try to maintain the friendly tone I’ve been trying (and sometimes failing :disappointed: ) to set here. I’m excited to have you onboard!

cc @billyjanitsch who’s been helping in my absence as well—I’m very grateful to you!

**Comment by froatsnook** [comment]
Hello @gaearon.  No problem!  This library saved me so much time such that I don't mind pitching in a bit while I'm procrastinating ;).  I'll do my best.

@js1559, feel free to re-open if the above didn't answer your question.
