### ISSUE TITLE
newbie question: how to package and run just the Knight example

### ISSUE THREAD

**Issue by azadbolour** [gaearon/react-dnd#426]
Hi,

Thanks so much for the tutorial. I am quite new to much of the technology used in the react dnd examples. I am trying to get just the Knight example working. After some trial and error and browsing, I got the Knight example to be processed by webpack. But I have not been able to display the board yet, and suspect that some of the dependencies and webpack/babel options I was able to find by googling may not be correct. 

Would it be possible to provide a shell script with the required npm installs and any other required setup of the environment to allow just the Knight example to run?

Many thanks.

Azad

**Comment by billyjanitsch** [comment]
See the [examples readme](https://github.com/gaearon/react-dnd/tree/master/examples) -- you just need to clone the repo, and then in the root directory, run `npm install` and `npm start`.

(This will build all the examples, not just the Knight one. Is that a problem?)

**Comment by azadbolour** [comment]
Thanks so much for cluing me in. My aim is to create a paired down project
with the minimum required scaffolding to run just the knight application.
But I guess now that I am clued in, I can incrementally remove the stuff I
don't need from the project and add a dependency to react-dnd.

Thanks again.

Azad
