### ISSUE TITLE
Feature Request: Allow Multiple Handles With connectDragSource

### ISSUE THREAD

**Issue by jchristman** [gaearon/react-dnd#427]
Right now, if ```connectDragSource``` is called multiple times, only the last element gets the draggable property. It would be nice to be able to drag something by several different elements. A specific use case is this:

An html "window" where you can drag the window around by its titlebar and drag the edges to resize it. There would need to be nine "dragging" handles on this window so that you could move the window and resize it in 8 different directions. I'm primarily wanting to do it this way so I can use the CustomDragLayer to show a live preview of the resizing and moving. Having each of the handles "drag" the window would allow such behavior with ease.

Is this possible to implement easily and/or do you have any suggestions on how to force one DragSource to disappear when a second DragSource is being dragged, where the first DragSource is the parent component of the second DragSource?

**Comment by froatsnook** [comment]
You could either have multiple DragSource children of the parent, or make the parent many DragSources.  Then you can call `connectDragSource` multiple times.

```javascript
class Parent extends Component {
  render() {
    const { connectNWSource, connectNSource, ... } = this.props;

    return connectNWSource(connectNSource(...
      ...
    )))))))));
  }
}

const nwDragSource = {

};

const nDragSource = {

};

...

Parent = DragSource("nw", nwDragSource, (connect, monitor) => {
  connectNWSource: connect.dragSource(),
});

Parent = DragSource("n", nDragSource, (connect, monitor) => {
  connectNSource: connect.dragSource(),
});

...

```

Maybe you can use some for loops to clean that up.

If you decide to have multiple child DragSources, then in your source's `componentWillReceiveProps`, if `nextProps.isDragging && !this.props.isDragging`, call `this.props.onDrag(this.props.dragId)`. The parent would look like this:

```javascript
class Parent extends Component {
  dragChild = (id) => { this.setState({ currentId: id }); };

  render() {
    const dragSourceIds = ["nw", "n", "ne", ...];
    const dragSources = dragSourceIds.map((dragId) => {
      return (
        <Child dragId={dragId} onDrag={this.dragChild} />
      );
    });

    ...
  }
}
```

*phew*

**Comment by jchristman** [comment]
Those are two interesting ways of approaching the problem. I think the first solution you gave is the way to go - you could probably stick in a for loop and it would work rather well. I'm going to give that a try tomorrow!!

Thanks for the help!!

**Comment by froatsnook** [comment]
Hey @jchristman. Yeah, the first way is how I probably would have approached it too.  Good luck!  Feel free to re-open if it doesn't work :).

**Comment by wanliyunyan** [comment]
@froatsnook do you have complete source？ i need thanks
