### ISSUE TITLE
Version 2.0.2 upgraded to 2.1.2 causes immense lag & freezing

### ISSUE THREAD

**Issue by TheSisb** [gaearon/react-dnd#441]
Haven't debugged it yet, but felt like this was important enough to announce in case someone knows what it could be...  Recently upgraded from react-dnd 2.0.2 to 2.1.2 and when rendering >400 draggable elements the page freezes for a few seconds.

**Comment by froatsnook** [comment]
That sounds interesting!  Do you think you could you upload a minimal repro?

**Comment by TheSisb** [comment]
Closing because the referenced issue is more descriptive.
