### ISSUE TITLE
The "drop" method isn't called when dropping the dragged element on itself

### ISSUE THREAD

**Issue by Vadorequest** [gaearon/react-dnd#444]
Is there a way to know that we dropped the dragged element on itself? I have a bunch of elements, and I want to do something specific when dropping the element on itself (which would by default do nothing, but it may in my case) and I wonder if I can get an event or something.

Thanks.

**Comment by AndrewTHuang** [comment]
Can you wrap the element in both a `DragSource` and `DropTarget` (and register each for the same `type`), then do whatever you need to do within the `drop` method?

**Comment by bouwwouw** [comment]
I've prevented an element from being dragged onto itself by using its props.id in dragSource, and comparing props.id with monitor.getItem().id in the canDrop function. You can also do that in the drop function

`const dragSource = {
  beginDrag: ({ id }) => ({ id })
};`
`const dropTarget = {
  drop: ({ id }, monitor) => {
    if (monitor.getItem().id === id) { /* do something cool */ }
  }
};`

**Comment by Vadorequest** [comment]
Since I wrote this my specs have changed, but glad to know it's possible ;)
