### ISSUE TITLE
How to allow multiple type of draggable item to be dropped?

### ISSUE THREAD

**Issue by Vadorequest** [gaearon/react-dnd#447]
I don't understand how we can set the drop area to allow multiple types of draggable items.

I've taken a look at the doc and I understand that it's defined here: https://github.com/gaearon/react-dnd/blob/master/examples/01%20Dustbin/Multiple%20Targets/Dustbin.js

```js
@DropTarget(props => props.accepts, dustbinTarget, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver(),
  canDrop: monitor.canDrop()
}))
```

But I don't understand what that does. I think that's mainly unfamiliar with ES6 yet. It looks like the property `props.accepts` contains all the accepted types. Then it returns an object.

Here is how I did it for another of my app:
```cjsx
collectDrop = (connect, monitor) ->
    return {
        connectDropTarget: connect.dropTarget()
        isOver: monitor.isOver()
        canDrop: monitor.canDrop()
    }

...

module.exports = DragSource(TYPE_PATTERN, patternDrag, collectDrag)(
    DropTarget('RESOURCE', patternDrop, collectDrop)(PatternEditor)
)
```

Could you explain to me using ES5 or similar? (Without the `@`)
Thanks :)

**Comment by Vadorequest** [comment]
By writing the question, I actually understood my issue x)

It was so simple I hadn't thought of it. I just have to write:

```cjsx
module.exports = DragSource(TYPE_PATTERN, patternDrag, collectDrag)(
    DropTarget(['PATTERN', 'RESOURCE'], patternDrop, collectDrop)(PatternEditor)
)
```

It's basically an array of possible types.

**Comment by abelkbil** [comment]
@Vadorequest  are you using typescript. This work for me in jsx but not in typescript. If time permits can you look into https://github.com/react-dnd/react-dnd/issues/785#issuecomment-368897599

Thank you.

**Comment by Vadorequest** [comment]
@abelkbil No, I'm not using typescript, and I'm not using react DnD nowadays anymore so I won't be much help, sorry.
