### ISSUE TITLE
'draggable' HTML property recalculated on every prop update

### ISSUE THREAD

**Issue by jakemmarsh** [gaearon/react-dnd#459]
This library is great. I'm currently attempting to use it within a web audio player. Currently, the components being made draggable (track elements) are passed down props from the audio player. This includes things like current position in the song playback, which means a prop update nearly every second.

Looking at the DOM in the Chrome Dev Tools, it looks like the `draggable` property of my elements is being recalculated/updated on every prop update. The result of my `canDrag` method is not changing on these updates.

This may not be a problem in and of itself, I just can't imagine this being very performant. Is there any way to prevent the updating of this attribute unless the results of `canDrag` is different? Thanks

![draggable_flashing](https://cloud.githubusercontent.com/assets/2916671/15237295/5ffb041a-1881-11e6-8573-602a2a855106.gif)

**Comment by jakemmarsh** [comment]
Sorry, jumped the gun a bit with this issue. This was due to the component re-rendering on every prop (regardless of update), so I just implemented some smarter checking in `shouldComponentUpdate`. Seems to have solved this issue

**Comment by cvharris** [comment]
@jakemmarsh What did you do, exactly? I'm running into this same problem and feel like I missed something simple in the docs but can't tell what.

**Comment by jakemmarsh** [comment]
@cvharris I no longer have the code lying around, but as I mentioned above I basically implemented `shouldComponentUpdate` to only re-render if specific props have changed. I prevented re-rendering on the per-second prop updates from the top-level audio player.

**Comment by cvharris** [comment]
I eventually solved my issue by refactoring my draggable items which passed an entire object as a prop into multiple props with primitive types as values. It's a React best-practice and this library depends on it to be performant. If I needed to continue to pass a complex object still I probably could have added a shallow check in `shouldComponentUpdate` like you mentioned. Just was curious how you may have implemented it.
