### ISSUE TITLE
Connected lists with React-dnd

### ISSUE THREAD

**Issue by greggigon** [gaearon/react-dnd#460]
Hi
First of all, Thanks for such a fantastic library!
I followed your sortable example to achieve list sorting. Is is possible to achieve something similar to https://jqueryui.com/sortable/#connect-lists jQuery connected lists sorting ?

I followed your simple sortable example using changing move method to move between columns. 
This seems to work with one exception. As soon as item is moved to other column, monitor.isDragging starts returning False and I loose the nice opacity styling. 
Any pointers would be much appreciated :)

**Comment by tarkanlar** [comment]
I need something similar too, I will work on it in a few days If I can find a solution i can share here

**Comment by tarkanlar** [comment]
Hey @greggigon if you still haven't solve the issue, you can check this https://github.com/gaearon/react-dnd/issues/227

**Comment by 2rp** [comment]
Had the same issue. Fixed it for me. Thanks @tarkanlar.

**Comment by greggigon** [comment]
Sweet @tarkanlar, Thanks!
