### ISSUE TITLE
Usage of redux connect and react-dnd

### ISSUE THREAD

**Issue by jnrepo** [gaearon/react-dnd#461]
I'm having an issue where I have a component that needs to be aware of the app state tree using the `connect function` and it also needs to implement react-dnd. I'm noticing that both need to `export default`; however, can only be done once. Would there be a workaround so that a component can be connected to redux and have dragdropcontext, while not using decorator syntax?

**Comment by froatsnook** [comment]
Yes, you can do it like this:

```javascript
class Card extends component {
  ...
}

Card = DropTarget(...)(Card);
export default class connect(mapStateToProps)(Card);
```

**Comment by jnrepo** [comment]
ah I will try that way as well. Would using `flow` also be another acceptable method as well?

```
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import flow from 'lodash/flow'

export default flow(
  connect(selector),
  DragDropContext(HTML5Backend)
)(ExperienceEditor);
```

**Comment by froatsnook** [comment]
‎Yes, that would also work!                                                                                                                                                                                                                From: Joon HeoSent: Thursday, May 19, 2016 01:13To: gaearon/react-dndReply To: gaearon/react-dndCc: froatsnook; State changeSubject: Re: [gaearon/react-dnd] Usage of redux connect and react-dnd (#461)ah I will try that way as well. Would using flow also be another acceptable method as well?

import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import flow from 'lodash/flow'

export default flow(
  connect(selector),
  DragDropContext(HTML5Backend)
)(ExperienceEditor);


—You are receiving this because you modified the open/close state.Reply to this email directly or view it on GitHub

**Comment by longmfe** [comment]
It seems that it doesn't work for touch back end...
I tried
App = DragDropContext(TouchBackend({ enableMouseEvents: true }))(App);
export default connect(mapStateToProps, mapDispatchToProps)(App);
I am not sure if I should post this issue here. Thanks.

**Comment by jnrepo** [comment]
@longmfe how are you importing `App`?

**Comment by longmfe** [comment]
@jnrepo Thanks for replay.
I just import it
`import App from ../../somepath/App.js`
should I add something when I using it?
BTW, I create App like this
`import {connect} from 'react-redux'
import {bindActionsCreators} from 'redux'
class App extends Component {

}
App = DragDropContext(TouchBackend({ enableMouseEvents: true }))(App);
export default connect(mapStateToProps, mapDispatchToProps)(App);`
Thanks a lot. Have a nice day.

**Comment by withintheruins14** [comment]
I am having an issue wrapping my root component with the DragDropContext. In the console I get:
`Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

Any clues as to what might be causing this issue? I do not think I am including multiple copies of React. This was working perfectly before wrapping the root component with DragDropContext. Thanks!

I have root.js configured as:
`
import { Component } from 'react';
import { DragDropContext } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

class Root extends Component {
  render() {
    return <div>
      {React.cloneElement(this.props.children, this.props)}
    </div>;
  }
}

export default DragDropContext(HTML5Backend)(Root);
`

And App.js as:
`
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import Root from './root';

function mapStateToProps(state) {
  return {
   ...
  }
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    ... 
}, dispatch)
}

const App = connect(mapStateToProps, mapDispatchToProps)(Root);

export default App;
`

The React console lays out the components in this way...
<img width="936" alt="screen shot 2017-01-16 at 11 55 02 pm" src="https://cloud.githubusercontent.com/assets/2576699/22009238/44b7c898-dc47-11e6-9d43-44015a192c5d.png">
