### ISSUE TITLE
using multiple react-dnd components with flow will make connectDropTarget and connectDropSource undefined

### ISSUE THREAD

**Issue by jnrepo** [gaearon/react-dnd#462]
```
const DragSourceDecorator = DragSource(ItemTypes.CONTENT_BLOCK, contentBlockSource, collectSource)
const DragTargetDecorator = DropTarget(ItemTypes.CONTENT_BLOCK, contentBlockTarget, collectTarget)

export default DragSourceDecorator(DragTargetDecorator(mComponent))
```

or

```
export default flow(
  DragSource(ItemTypes.CONTENT_BLOCK, contentBlockSource, collectSource),
  DropTarget(ItemTypes.CONTENT_BLOCK, contentBlockTarget, collectTarget)
)(mComponent)
```

seems to not pass in `connectDragSource` and `connectDropTarget` into `this.props` of `mComponent`. 

I've also tried, sorry if this example is a little rough.

```
class mComponentList extends Component {
  ...
  render() {
    return (
            <mComponent />
    )
  }
}

const DragSourceDecorator = DragSource(ItemTypes.CONTENT_BLOCK, contentBlockSource, collectSource)
const DragTargetDecorator = DropTarget(ItemTypes.CONTENT_BLOCK, contentBlockTarget, collectTarget)
const mContentBlocksGroup = DragSourceDecorator(DragTargetDecorator(ContentBlocksGroup))

export default mContentBlocksGroup
```

which seems to not even render my component at all, would there be a better way to do this?

**Comment by froatsnook** [comment]
It's hard to tell exactly what's going on.  The first and second examples looks good.  Can you copy and paste your collecting functions?

The third example wouldn't work because you called the decorators on `ContentBlocksGroup` isntead of `mComponentList`, but maybe that's just because the example is rough :).

**Comment by jnrepo** [comment]
ah, I'll continue to play with the first two examples then.

My collecting functions:

```
const contentBlockSource = {
  beginDrag(props) {
    return {
      index: props.index
    }
  }
}

function collectSource(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  }
}

const contentBlockTarget = {
  drop(targetProps, monitor) {
    const sourceProps = monitor.getItem();
    const targetId = targetProps.index
    const sourceId = sourceProps.index

    if (sourceId !== targetId) {
      targetProps.onMove(sourceId, targetId)
    }
  }
};

function collectTarget(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    canDrop: monitor.canDrop(),
    isOver: monitor.isOver()
  }
}
```

Thank you for the help!

**Comment by froatsnook** [comment]
That looks OK...

Things to check:

1. Is it still true that `this.props.connectDropTarget` and `this.props.connectDragSource` are undefined in your `render`?
2. Are you sure that you're rendering the exported (i.e. decorated) component?  This could go wrong, for example, if you're rendering a nested component (e.g. a TreeView).
3. Are there any interesting errors in the console?
4. In your third example above, you didn't call `connectDropTarget` and `connectDragSource`.  Did you forget that?  Or take it out since they're undefined.  In other words, how do you know they're undefined?
5. How does this all relate to the title of this issue?  Does it work when you just have one of the two decorators in your call to `flow`?

**Comment by jnrepo** [comment]
```
class ContentBlock extends Component {

  render() {
    const { connectDragSource, isDragging, connectDropTarget, canDrop, isOver } = this.props
    return connectDragSource(connectDropTarget(
      <div>Drag Me!</div>
    ))
  }
}

export class ListOfContentBlocks extends Component {
  render() {
    const { dispatch, experience, contentBlocksStyle } = this.props
    return (
      <div id="cbListAccordion" role="tablist" className="panel-group">
        {Object.keys(contentBlocks).map((key, i) => {
          return (
            <ContentBlock
              ...
              dispatch={dispatch}
            />
          )
        }, this)}
      </div>
    )
  }
}

const contentBlockSource = {
  beginDrag(props) {
    return {
      index: props.index
    }
  }
}

function collectSource(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  }
}

const contentBlockTarget = {
  drop(targetProps, monitor) {
    const sourceProps = monitor.getItem();
    const targetId = targetProps.index
    const sourceId = sourceProps.index

    if (sourceId !== targetId) {
      targetProps.onMove(sourceId, targetId)
    }
  }
};

function collectTarget(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    canDrop: monitor.canDrop(),
    isOver: monitor.isOver()
  }
}

export default flow(
  DragSource(ItemTypes.CONTENT_BLOCK, contentBlockSource, collectSource),
  DropTarget(ItemTypes.CONTENT_BLOCK, contentBlockTarget, collectTarget)
)(ContentBlock)
```
felt that might be a better example of what I'm doing

1. Yes, they're returning as undefined.
<img width="830" alt="screen shot 2016-05-19 at 11 12 02 am" src="https://cloud.githubusercontent.com/assets/5111058/15404491/95b9867c-1db2-11e6-9bff-dbd177aa4ed5.png">

2. Yes, based on the error shown above, I'm sure the `ListOfContentBlocks` is being rendered.

3. Other than the one shown above, there doesn't seem to be any other errors or warnings.

4. Included how I'm using it the new example above.

5. When i used the decorator syntax like so...
```
...

@DragSource(ItemTypes.CONTENT_BLOCK, contentBlockSource, collectSource)
@DropTarget(ItemTypes.CONTENT_BLOCK, contentBlockTarget, collectTarget)
class ContentBlock extends Component {
...
```
it worked fine, but we're updating to a different version of babel, in which they removed the support for decorators :/

**Comment by froatsnook** [comment]
Ah, I understand the problem.  It's as I guessed in 2.  Your `ListOfContentBlocks` is rendering undecorated `ContentBlock`s.  You have two options:

1. Make sure you render the decorated component:

```javascript
class ContentBlock extends Component {
  ...
}
ContentBlock = flow(...)(ContentBlock);
```

2. Use babel6 decorators: https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy

**Comment by jnrepo** [comment]
I see the light! (its working!!)

Thank YOU! @froatsnook

**Comment by froatsnook** [comment]
Great :)
