### ISSUE TITLE
Examples in es5

### ISSUE THREAD

**Issue by cristian-dan** [gaearon/react-dnd#469]
Could you provide the examples in es5 please? I don't understand es7 very well and I would really appreciate if you could provide at least the example 04-sortable simple in es5. 

Or at least tell me how I make the card a drop source and a drop target.
Like this? 

> module.exports = DragSource(ItemTypes.CARD, cardSource, collectSource)(DropTarget(ItemTypes.CARD,cardTarget, collectTarget)(CardClass));

Thanks a lot!

**Comment by froatsnook** [comment]
Sorry about the new syntax!  But you'll love it once you get used to it :).

Yours looks fine to me.  I generally write it like this in ES5:

```javascript
var CardClass = React.createClass({ ... });
CardClass = DragSource(ItemTypes.CARD, cardSource, collectSource)(CardClass);
CardClass = DropTarget(ItemTypes.CARD, cardTarget, collectTarget)(CardClass);
module.exports = CardClass;
```

You could also use lodash's [`flow`](https://lodash.com/docs#flow).

Feel free to re-open.

**Comment by cristian-dan** [comment]
thanks a lot for help :D
