### ISSUE TITLE
require('react-dnd') causes type error on linux but not on os-x.

### ISSUE THREAD

**Issue by tthomas7** [gaearon/react-dnd#472]
I have an admittedly strange technology stack, but I'm hoping you can help me anyway. I'm using rails with browserify-rails to use recent versions of reactjs (15.0.2), redux (3.5.2), and react-dnd (2.1.4). 

On os-x it works great but on linux I get very strange behavior. The first time I require react-dnd I get the following stack trace, the second time I get an object with a function DragDropContext but DropTarget and DragSource are undefined.

![react-dnd-screenshot](https://cloud.githubusercontent.com/assets/6403103/16059145/bd678d0c-324f-11e6-9af4-0977868c50ee.png)

Failing on this line of code.
`arguments[4]["/home/thomas/checker-cruncher/node_modules/react-dnd-html5-backend/lib/shallowEqual.js"][0].apply(exports,arguments)`

I've previously had issues with capitalization on these two operating systems, osx doesn't care so require("react-DND") is the same as require("react-dnd") but I don't think that's the problem this time. Or at least I haven't found it. 

Do you have any ideas as to what I'm doing wrong, or how I can narrow down the problem? 
Thanks,
Thomas

**Comment by tthomas7** [comment]
Never mind, I'm just a moron. Clearing the browserify-rails cache solved the problem. I apparently just needed to wine to someone before I could figure it out.

**Comment by froatsnook** [comment]
It happens to the best of us!
