### ISSUE TITLE
Disable dnd

### ISSUE THREAD

**Issue by maxcc0** [gaearon/react-dnd#473]
Is there a hook with which dnd can be disabled? I'm trying to reuse a dnd component and want to disable dnd.

**Comment by froatsnook** [comment]
I'm not sure I understand your question.  Do you want to prevent a component from being dragged in some cases?  If so, you could implement this by giving your component a prop `canDrag`.

```javascript
// drag source spec
{
  ...
  canDrag: function(props, monitor) {
    return props.canDrag;
  },
  ...
}
```

Then you can either render your component with `canDrag={true}` or `canDrag={false}`.

```javascript
  <MyComponent canDrag={true} />
  <MyComponent canDrag={false} />
```

Let me know if you meant something else.

**Comment by kesne** [comment]
Hey @maxcc0, it looks like your issue has been resolved with the above sample (which is what I was going to recommend before I saw it had already been posted!). Feel free to open a new issue or comment here if you have more questions!

**Comment by donszek** [comment]
@froatsnook @kesne 
Hello, can I check, where should I implement the canDrag function? I am using a custom drag layer similar to the source [https://github.com/react-dnd/react-dnd/tree/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer](here). 

Thank you.

**Comment by sethmcleod** [comment]
@donszek Assuming your code is similar to the example you linked to, you would add the `canDrag` function [here](https://github.com/react-dnd/react-dnd/blob/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer/DraggableBox.js#L9), in the _spec function_ (is this case, boxSource) for your DragSource.

**Comment by s875515** [comment]
> I'm not sure I understand your question. Do you want to prevent a component from being dragged in some cases? If so, you could implement this by giving your component a prop `canDrag`.
> 
> ```js
> // drag source spec
> {
>   ...
>   canDrag: function(props, monitor) {
>     return props.canDrag;
>   },
>   ...
> }
> ```
> 
> Then you can either render your component with `canDrag={true}` or `canDrag={false}`.
> 
> ```js
>   <MyComponent canDrag={true} />
>   <MyComponent canDrag={false} />
> ```
> 
> Let me know if you meant something else.

it will be calling canDrop now
