### ISSUE TITLE
Testing: How to access wrapped component?

### ISSUE THREAD

**Issue by hakunin** [gaearon/react-dnd#488]
Hey guys,
I am using this to simulate the view in test environment and I need to access the underlying component, which I can't seem to find:

```
window.wrapInTestContext = (DecoratedComponent) => {
  return DragDropContext(TestBackend)(
    React.createClass({
      render: function () {
        return <DecoratedComponent {...this.props} />;
      }
    })
  );
};

var MockedFolderView = wrapInTestContext(InnerFolderView);

// enzyme wrapper
var wrapper = mount(
  <MockedFolderView
    folder={root_folder}
    connectDropTarget={pass}
  />
);

// enzyme returns the component with instance() call
wrapper.instance()/*... something... */.moveBoard(...);
````

So I am looking to find the component, what should I replace `/* ...something... */` with?

**Comment by cah-ricksuggs** [comment]
@hakunin I'm having the same issue. There doesn't seem to be a method built in to access it, but I was able to do, for example:

```
const instance = wrapper.instance();

const decoratedInstance = instance.getDecoratedComponentInstance()
      ._reactInternalInstance._renderedComponent._instance;
decoratedInstance.doSomething(...);

expect(decoratedInstance.state.something).to.equal('something');
```

**Comment by hakunin** [comment]
I ended up working it around so that I don't have to access instance.

Now that I think of it, can you try `wrapper.find(<YourComponent>).instance().doSomething()`?

**Comment by mcrawshaw** [comment]
There is a solution in the docs for this http://gaearon.github.io/react-dnd/docs-testing.html

**Comment by kesne** [comment]
You can call `.shallow()` on the HOC-wrapped component to get the instance of the wrapped component.
