### ISSUE TITLE
Unable to use scroll wheel while dragging

### ISSUE THREAD

**Issue by amoenk** [gaearon/react-dnd#49]
While an item is being dragged, simultaneously using the scroll wheel does not scroll the page.

**Comment by gaearon** [comment]
I'd need a mouse to reproduce this, right? Sadly I don't have one.

I have a feeling this may be an inherent limitation of HTML5 drag and drop API we currently use. You can verify by opening [this online demo](http://html5demos.com/drag), zooming in so scroll appears and trying to scroll.

If it is indeed an HTML5 API problem, it will be possible to work around when #48 is ready and alternative mousemove-based implementation is available.

**Comment by amoenk** [comment]
Yep, it appears to be an inherent limitation. I am able to reproduce the
problem on that link. Thanks.

I think you should be able to reproduce this using a two finger drag
gesture on a touchpad, but I'm finding that the same gesture is failing in
things like Mac OS Finder and Gnome Files. Click and begin the drag
movement, then touch with your second finger and scroll action. It's easier
when the mouse button is separate from the touchpad.

On Sat, Feb 7, 2015 at 9:49 AM, Dan Abramov <notifications@github.com>
wrote:

> I'd need a mouse to reproduce this, right? Sadly I don't have one.
>
> I have a feeling this may be an inherent limitation of HTML5 drag and drop
> API we currently use. You can verify by opening this online demo
> <http://html5demos.com/drag>, zooming in so scroll appears and trying to
> scroll.
>
> If it is indeed an HTML5 API problem, it will be possible to work around
> when #48 <https://github.com/gaearon/react-dnd/pull/48> is ready and
> alternative mousemove-based implementation is available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaearon/react-dnd/issues/49#issuecomment-73374547>.
>



-- 
Andrew Moenk

**Comment by gaearon** [comment]
You're okay with me closing this? Not much we can do until we implement mousemove backend.

**Comment by amoenk** [comment]
Yep, go ahead and close it.

On Sat, Feb 7, 2015 at 12:09 PM, Dan Abramov <notifications@github.com>
wrote:

> You're okay with me closing this? Not much we can do until we implement
> mousemove backend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaearon/react-dnd/issues/49#issuecomment-73380674>.
>



-- 
Andrew Moenk
