### ISSUE TITLE
ConnectDragSource throws exception when first JSX element is react component

### ISSUE THREAD

**Issue by ericp96** [gaearon/react-dnd#492]
Firstly - great library! I very much appreciate what you've done here.

Secondly, it appears that ConnectDragSource throws an exception when the first JSX element is a react component. i.e.:

Works:

return connectDragSource(
<div>
<ReactComponent1>
</ReactComponent1>
</div>
);

Breaks:

return connectDragSource(
<ReactComponent1>
<div>
</div>
</ReactComponent1>
);

I realize it's not a common use case for someone to wrap the entire react component children in another react component, but it has its place.

**Comment by kesne** [comment]
@ericp96 It looks like both your working and broken examples are the same?

**Comment by ericp96** [comment]
Sorry - git stripped out the tags.  This is what I'm dealing with:

This doesn't work:
`return connectDragSource(
      <MyComponent>
         <div id="top-level-div"></div>
      </MyComponent>
);`

Where MyComponent: 
`const MyComponent = (props) => (
    <div>
        {props.children}
    </div>
);`

This does work:
`return connectDragSource(
      <div id="top-level-div"></div>
);`

The errors generated are:
warning.js:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Please let me know if you need more specific information from me and I would be happy to help.

**Comment by kesne** [comment]
This is working as expected. This was changed in v2. You can read about this here: https://github.com/gaearon/react-dnd/releases/tag/v2.0.0
