### ISSUE TITLE
Cannot find dist folder

### ISSUE THREAD

**Issue by ankitrg** [gaearon/react-dnd#502]
The doc says that I can find the compiled version in the `dist` folder, but I was unable to fine one? Can anyone help.

**Comment by rparjun** [comment]
@ankitrg Please install the package using `npm install react-dnd` then goto `./node_modules/react-dnd/dist` you can get the files

**Comment by kesne** [comment]
As @rparjun mentioned, the dist folder is not checked into github, and is only in the published version of the module.

If you want to browse the dist files, you can either install the package and inspect it in `node_modules`, or you could use something like npmcdn to do it online: https://npmcdn.com/react-dnd@2.1.4/
