### ISSUE TITLE
Move html5 backend into a new package without react-dnd peer dep

### ISSUE THREAD

**Issue by Samsinite** [gaearon/react-dnd#513]
First off, just want to say thanks for building `react-dnd` and its core libraries. The abstractions are wonderful to work with and very flexible.

Currently using `dnd-core` and `react-dnd-html5-backend` inside of an ember addon and it works great! But, I am using bower to grab the `react-dnd-html5-backend` because the npm package has a `react-dnd` peer dependency, which makes sense due to the name of the package. I would like to propose moving the html5 backend into a package named something like `dnd-core-html5-backend` without the `react-dnd` peer dep, then updating `react-dnd-html5-backend` to use `dnd-core-html5-backend` with the `react-dnd` peer dependency. If this sounds reasonable, let me know if there is anything I can do to help.

**Comment by kesne** [comment]
I think this seems like a reasonable idea. Let's create an issue on the HTML5 backend project and track it there: https://github.com/gaearon/react-dnd-html5-backend/issues/40
