### ISSUE TITLE
Trello like board

### ISSUE THREAD

**Issue by VladimirPal** [gaearon/react-dnd#514]
Hi!
I've developed trello like board using react-dnd. https://github.com/web-pal/react-trello-board
I thought maybe @gaearon can add in examples section?

**Comment by kesne** [comment]
thanks for this @VladimirPal! While I think that the React Trello Board looks a little too complicated to host in the repo as an example, I'm planning on making a showcase in the next few weeks to highlight community projects that use React DnD, and I'd be happy to have that project there!

**Comment by kesne** [comment]
I'm closing this for now, but when I introduce the showcase, I'll be sure to tag you!

**Comment by VladimirPal** [comment]
@kesne Thank you.
