### ISSUE TITLE
React-dnd from NPM is quite large, let's drop lodash?

### ISSUE THREAD

**Issue by jakubzitny** [gaearon/react-dnd#516]
Hey there, we're using react-dnd from NPM and we're quite surprised by the size of the library. The whole `react-dnd` is taking 5.7M. 4.7M of that is only `lodash`. From lodash you're using only `flatten`, `shuffle`, `isArray` and `isPlainObject` functions. These are available separately from NPM taking only 100K.

I know there are separate minified versions of this library, however, would you be interested in a PR that replaces the whole lodash with only what you guys are using?

**Comment by kesne** [comment]
I'm not that interested in optimizing install time, but I understand that a lot of people these days seem to care about it. This change seems minor enough to bring in.

I'm on vacation now but I'll take a look at the PRs that solve this issue when I return.

**Comment by billyjanitsch** [comment]
Closing based on discussion in #517.
