### ISSUE TITLE
Nesting DropTarget in a non-immediate child

### ISSUE THREAD

**Issue by JasonEtco** [gaearon/react-dnd#518]
Hello! I'm having some problems with nested DropTargets; I have a similar situation to:

```js
@DragSource(...) // This also needs to be sortable
@DropTarget(...)
class HigherDropComp extends... {
  render() {
    return connectDragSource(connectDropTarget(
      <div> // Start of the higher-level drop target
        <FirstChild />
      </div>
    ));
  }
}

class FirstChild extends... {
  render() {
    return <SecondChild />
  }
}

@DropTarget(...)
class SecondChild extends... {
  render() {
     return connectDropTarget (
       <div></div>
     );
  }
}
```

Using `connectDropTarget()` within the `<FirstChild />` (on the `return`) works perfectly, but as soon as I try to add it to the `<SecondChild />` it is completely ignored. Is there a smarter way to be doing this? Let me know if you need to some more code to understand my problem.

Thank you!

**Comment by JasonEtco** [comment]
Even if I do use `<FirstChild />` as a DropTarget (which I don't want to do), I still can't get the second level nested child to be recognized as a DropTarget using the same exact setup. I'm using `monitor.isOver()` and `monitor.isOver({ shallow: true })` to check.

**Comment by kesne** [comment]
Can you get a repo up with minimal steps to reproduce this? The nested drop target example works for me, so I'm not sure why you'd be having issues: http://gaearon.github.io/react-dnd/examples-nesting-drop-targets.html

**Comment by JasonEtco** [comment]
Turns out it was just a silly `z-index` issue. Sorry to bother you all!
