### ISSUE TITLE
Change DragPreview opacity

### ISSUE THREAD

**Issue by optimatex** [gaearon/react-dnd#549]
Hi. Thank u for awesome solution. I would like to change an opacity of drag preview. It's dim by default. I read similar issues but there was mostly custom things like getting actual state for item in drag. I only wish to change opacity. I suppose it is dim cuz of some style's opacity. So, maybe it will be easy to change styles of preview image?

**Comment by kesne** [comment]
The browser is what is setting the lower opacity, so we can't override that unfortunately. One workaround would be to use a custom DragLayer, which lets you customize the look of the drag preview 100%.

**Comment by optimatex** [comment]
thanks

**Comment by Shubham-047** [comment]
as i am facing opacity issue in windows while dragging the item in react-dnd any soultion ?
