### ISSUE TITLE
Performance Issue with a timesheet app

### ISSUE THREAD

**Issue by 7HUND3RX** [gaearon/react-dnd#585]
I am building an interface which allows to drag and drop bookings in the timesheet. It needs to render around 1200 drop targets (1/4th of long white rectangle) and 50 drag sources.
The performance is really slow (lagging) at the moment, browser window becomes unresponsive for a few seconds and drag previews are laggy afterwards.

I want to understand if the issue is because of the number of drop targets  and drag sources, or more because of the implementation.

I have attached a screenshot to give an understanding of what I am trying to make.

![untitled](https://cloud.githubusercontent.com/assets/1748248/20552017/82b1a994-b16c-11e6-905d-2ab7b0a4069b.png)

**Comment by mdramos** [comment]
@7HUND3RX How did you solve this?

**Comment by nickwaelkens** [comment]
Any updates on this would be appreciated, @7HUND3RX !

**Comment by lednhatkhanh** [comment]
Any updates on this? Thank you.

**Comment by 7HUND3RX** [comment]
Hey, I already closed the ticket, the problem was the browser hangs up because of 1200 elements. So rather I made 12 rows and 12 columns and used drop targets for rows and columns rather than drop targets for cells.

I tried to make this comment through email earlier, but apparently it didn't go through

**Comment by lednhatkhanh** [comment]
Thanks for your reply

**Comment by mdramos** [comment]
I solved it by using react-virtualized
