### ISSUE TITLE
Prevent dragStart / dragging is started within textarea inside dragSource

### ISSUE THREAD

**Issue by Mangatt** [gaearon/react-dnd#602]
Hi,
when I place textarea inside dragSource, user is correctly able to select text inside textarea. Problem is that selection is possible only when user starts on text, not anywhere inside textarea (as is able usually).

Is there a way to prevent dragStart on certain descendant elements of dragSource? StopPropagation of mouseDown event certainly does not work.

**Comment by Mangatt** [comment]
Anyone? This is both important and simple, is there a waz how to stopPropagation of dragStart?

**Comment by Mavrin** [comment]
You could make something like:
```js
canDrag(props) {
    return props.textAreaIsNotFocused
}
```

**Comment by Mangatt** [comment]
This does not solve that problem, user can start selection of text without focusing textarea first.

**Comment by Mavrin** [comment]
Yes you are right. I can recommend try use https://www.npmjs.com/package/react-dnd-mouse-backend maybe it can help you.
If say about native-dnd-backend look likes it is browser behavior and it is not issuse react-dnd.
Other suggestion you can make explicit drag control for your block.

**Comment by Mangatt** [comment]
Thanks, I have tried mouse backend and unfortunately is much less smooth than HTML5 backend. I guess that I have to find other way around it.

**Comment by natenorberg** [comment]
What worked for me was to make the text box dragable and then cancel the event

```jsx
<textarea
  {/* ... */}
  draggable
  onDragStart={e => {
    e.preventDefault();
    e.stopPropagation();
  }}
/>
```
