### ISSUE TITLE
DragLayer + tbody: fires beingDrag then endDrag immediately

### ISSUE THREAD

**Issue by butchmarshall** [gaearon/react-dnd#613]
I'm attempting to drag-and-drop <tbody> elements but hitting a blocker.

I attempt to grab the dragSource from where the dragLayer would appear but immediately dragEnd fires immediately after dragStart.

Any idea what I'm doing wrong?  Using the regular screenshot from the HTML5 backend works fine.

I've built a sample application to demonstrate the issue [here](https://github.com/butchmarshall/react-dnd-dragbug)

![react-dnd](https://cloud.githubusercontent.com/assets/339763/21915110/b3c17b8e-d905-11e6-8b24-5f885e0a392d.gif)

**Comment by butchmarshall** [comment]
Fixed!  

I think it's because the dragPreview layer always needs to be 'fixed' position off screen, then moved only with transform?  Pushed my working branch.

**Comment by samkuehn** [comment]
@butchmarshall I am having this same issue and cannot seem to fix it (I am using connect.dragPreview() - not a custom DragLayer).

I have a few groups of items, much like your tables (items of divs within divs).  I can drag and drop items in the first few groups at the top of the page, however, items in groups lower on the page cannot be dragged.  endDrag fires immediately after beginDrag.

I tried removing the drag preview but it was still broke.

I tried looking at your code but there are a lot of changes in the commit that fixed it.  I was hoping that you could elaborate on underlying issue/solution for me.

Thanks in advance!

**Comment by samkuehn** [comment]
![dnd](https://cloud.githubusercontent.com/assets/263189/24941694/829e4b82-1f09-11e7-9b3f-bea6baccc360.png)


It turns out I can fix the issue if I change the type ('Item') of the DropTarget on the Category.   However, this is not a solution as it means that I cannot drop on the category.

**Comment by butchmarshall** [comment]
Huh, I'll have to get back to you on exactly what I did here - it was awhile ago!

I believe the only solution I could come up with though was using a custom drag layer.
