### ISSUE TITLE
Remove support for deprecated API

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#67]
Before proceeding with other issues like drag source key tracking, we need a PR against [1.0](https://github.com/gaearon/react-dnd/tree/1.0) branch that removes support for deprecated API.

@nelix Would you like to take this?

**Comment by nelix** [comment]
reopening this one

**Comment by gaearon** [comment]
Rewrote this on top of recent master in 1.0 branch. Thanks!

https://github.com/gaearon/react-dnd/commit/2147e8bb2e9ded39f7223c98ffbe1bdf5f30c6e4
