### ISSUE TITLE
Using react-dnd in production? Add your company to README!

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#83]
https://github.com/gaearon/react-dnd#production-usage

Feel free to send a PR adding your company and describing your user case.

**Comment by nelix** [comment]
I am eager to get react-dnd into production, but I do need to solve resurfacing first. I might put my fork into production until we get a chance to do 1.0.

**Comment by gaearon** [comment]
Please do so! I intend to get back to this ASAP but I've been swamped with our first public launch: http://stampsy.com :-)

**Comment by nelix** [comment]
I saw the launch video, stunning!
