### ISSUE TITLE
DropTarget to filter accepted dropped files

### ISSUE THREAD

**Issue by radubrehar** [gaearon/react-dnd#89]
First of all, thanks for the great work.

I've just used it to create a d&d area for files to be uploaded, and works just file. I have
```js
configureDragDrop: function(register) {
    register(NativeDragItemTypes.FILE, {
	dropTarget: {
	    enter: function(component){
                ...
	    },

            leave: function(component){
	          ...
            },

            acceptDrop: function(component, item) {
                component.addFiles(item.files)
            }
         }
    })
}
```
I also have a file input and keep the file input & drag-drop area in sync. So users can upload either via file input or via drag-drop.
My problem is that with the file input, I can filter files by specifing the `accept` attribute. Is there a way to specify the accept attribute for the droptarget? 

(I know I could filter them in the acceptDrop, but that is not idiomatic)

Thanks.

**Comment by gaearon** [comment]
>My problem is that with the file input, I can filter files by specifing the accept attribute. Is there a way to specify the accept attribute for the droptarget?

Do you mean filtering by extension? Sadly this won't work because browser only tells you filenames after you drop. I believe the reason for this is to avoid accidentally exposing private information.

**Comment by radubrehar** [comment]
Yes. So I think I have to implement this filtering in the acceptDrop function. I could turn this into a small npm module, if interested, maybe you could use that as well.

**Comment by gaearon** [comment]
I'm not sure if it's worth turning it into a standalone module, as you would still probably want to work with `File` objects yourself and it's not something that can be extracted away.
