### ISSUE TITLE
DND for Native File not working in Safari 8.0.3

### ISSUE THREAD

**Issue by eikeon** [gaearon/react-dnd#91]
For example, when dragging a file to the last bin in this example: http://gaearon.github.io/react-dnd/#/dustbin-interesting

**Comment by gaearon** [comment]
How do you tell it's not working?

This is what you should see in Safari:

![screen shot 2015-02-19 at 16 38 12](https://cloud.githubusercontent.com/assets/810438/6267512/c112a1c8-b855-11e4-82f4-5dcccbbff08d.png)

It's not empty, there's one object there.

The string representation is different than Chrome, but there's definitely `item.files[0]` there:

![screen shot 2015-02-19 at 16 39 30](https://cloud.githubusercontent.com/assets/810438/6267544/fc5c9cb6-b855-11e4-932d-f147d2c7b0f5.png)

**Comment by gaearon** [comment]
Whoops, sorry, here's the Safari devtools screenshot:

![screen shot 2015-02-19 at 16 43 19](https://cloud.githubusercontent.com/assets/810438/6267606/7a7ab402-b856-11e4-8149-023b52564e7c.png)

Nevermind the minified variable name.

**Comment by eikeon** [comment]
My bad. I was thrown off by Safari's representation. I do see that it's working. Thank you for the explanation.
