### ISSUE TITLE
Deprecate `e` parameter

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#93]
We should gather all valid use cases for it and allow to do the same via `context` passed to `configureDragDrop`. For example, you can already get the delta between start and current drag positions by calling  [`getCurrentOffsetDelta`](https://github.com/gaearon/react-dnd/blob/master/docs/API.md#getcurrentoffsetdelta).

This will be a breaking change in 1.0. We want to do this because doing something like `e.preventPropagation` was always bad (instead we need #87), and we want to hide internals better so people don't rely on particular drag and drop implementation, and adding touch support in future is easier.

**Comment by nelix** [comment]
Even atm you can do nested dragging without e.stopProp in most cases I think. see: #90

**Comment by gaearon** [comment]
This is done in 0.9.0.
