### ISSUE TITLE
Make record/replay possible

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#96]
As we work towards separating backend logic from the API, we might want to rewrite backend/API interaction in such a way that drag and drop actions can be recorded and later replayed by re-dispatching actions. It's a nice restriction that forces code to go into better shape, but we're far from ready for it, so I'll just keep it open.

**Comment by nelix** [comment]
Would this require that drag types are strings (rather than ```Symbol()```?

**Comment by gaearon** [comment]
Yeah, seems so. I think it's ok for now and we'll figure it out later as we get to this.

**Comment by gaearon** [comment]
Closing for now as I don't have interest in implementing this. Since `dnd-core` works on top of Redux now it is theoretically much more possible—just need to figure out a way how to pass time-travely Redux store to `dnd-core` instead of the one it creates internally.
